-- Additive storage for v2 Task authoring and inspection evidence. Existing task
-- definitions, connector projections and issue records are not rewritten.
alter table task_versions
  add column author_format text not null default 'json' check(author_format in('json','yaml')),
  add column author_source text,
  add column author_revision integer not null default 0 check(author_revision>=0),
  add column dsl_version text not null default 'aerosight/v1' check(dsl_version in('aerosight/v1','aerosight/v2')),
  add column definition_hash text check(definition_hash is null or definition_hash ~ '^[a-f0-9]{64}$');
alter table tasks
  add column authorized_by_user_id integer references users(id),
  add column schedule_evaluated_at timestamptz;

create table task_trigger_records (
  id bigint generated by default as identity primary key,
  project_id integer not null,
  team_id integer not null,
  task_id integer not null,
  task_version_id bigint not null,
  occurrence_key text not null,
  scheduled_for timestamptz,
  interval_end timestamptz,
  outcome text not null check(outcome in('accepted','missed','skipped','error')),
  reason text not null,
  task_run_id integer,
  created_at timestamptz not null default now(),
  foreign key(project_id,team_id) references projects(id,team_id) on delete cascade,
  foreign key(task_id,project_id) references tasks(id,project_id),
  foreign key(task_version_id,project_id) references task_versions(id,project_id),
  foreign key(task_run_id,project_id) references task_runs(id,project_id),
  unique(project_id,task_id,occurrence_key),
  check((outcome='accepted')=(task_run_id is not null)),
  check(interval_end is null or scheduled_for is not null and interval_end>=scheduled_for)
);

-- These keys let downstream records enforce run and asset-version scope in SQL.
alter table task_run_steps add constraint task_run_steps_run_project_unique unique(id,task_run_id,project_id);
alter table assets add constraint assets_version_project_unique unique(id,version,project_id);

create table inspection_observations (
  id uuid primary key default gen_random_uuid(),
  project_id integer not null,
  team_id integer not null,
  task_run_id integer not null,
  task_run_step_id bigint not null,
  source_mode text not null check(source_mode in('assets','existing-flight','flighthub-flight')),
  connector_instance_id bigint,
  remote_flight_id text,
  projected_run_id integer,
  completeness text not null default 'partial' check(completeness in('complete','partial','alert-only','unavailable')),
  scope_description text not null check(length(btrim(scope_description))>0),
  observed_from timestamptz not null,
  observed_to timestamptz not null,
  manifest_json jsonb not null default '{}'::jsonb check(jsonb_typeof(manifest_json)='object'),
  sealed_at timestamptz,
  limited_scope_confirmed_by integer references users(id),
  created_at timestamptz not null default now(),
  foreign key(project_id,team_id) references projects(id,team_id) on delete cascade,
  foreign key(task_run_step_id,task_run_id,project_id) references task_run_steps(id,task_run_id,project_id),
  foreign key(connector_instance_id,project_id) references device_adapters(id,project_id),
  foreign key(projected_run_id,project_id) references task_runs(id,project_id),
  unique(task_run_step_id,project_id),
  unique(id,task_run_id,project_id),
  unique(id,project_id),
  check(observed_to>=observed_from),
  check((source_mode='assets' and connector_instance_id is null and remote_flight_id is null and projected_run_id is null)
     or (source_mode<>'assets' and connector_instance_id is not null and remote_flight_id is not null and length(btrim(remote_flight_id))>0))
);

create table inspection_observation_assets (
  observation_id uuid not null,
  project_id integer not null,
  asset_id integer not null,
  asset_version integer not null,
  source_run_id integer,
  primary key(observation_id,asset_id),
  foreign key(observation_id,project_id) references inspection_observations(id,project_id) on delete cascade,
  foreign key(asset_id,asset_version,project_id) references assets(id,version,project_id),
  foreign key(source_run_id,project_id) references task_runs(id,project_id)
);

create table inspection_evidence_sets (
  id uuid primary key default gen_random_uuid(),
  project_id integer not null,
  team_id integer not null,
  task_run_id integer not null,
  task_run_step_id bigint not null,
  observation_id uuid not null,
  source text not null check(source in('flighthub-ai','external')),
  model_version text not null,
  completeness text not null default 'unavailable' check(completeness in('complete','partial','alert-only','unavailable')),
  target_algorithm_confirmed boolean not null default false,
  evidence_json jsonb not null default '{}'::jsonb check(jsonb_typeof(evidence_json)='object'),
  created_at timestamptz not null default now(),
  foreign key(project_id,team_id) references projects(id,team_id) on delete cascade,
  foreign key(task_run_step_id,task_run_id,project_id) references task_run_steps(id,task_run_id,project_id),
  foreign key(observation_id,task_run_id,project_id) references inspection_observations(id,task_run_id,project_id),
  unique(task_run_step_id,project_id),
  unique(id,task_run_id,project_id)
);

create table inspection_assessments (
  id uuid primary key default gen_random_uuid(),
  project_id integer not null,
  team_id integer not null,
  task_run_id integer not null,
  task_run_step_id bigint not null,
  evidence_set_id uuid not null,
  status text not null default 'pending' check(status in('pending','running','needs_review','succeeded','failed','canceled')),
  revision integer not null default 0 check(revision>=0),
  provider_id integer references ai_providers(id),
  model_version text,
  prompt_version text,
  evidence_hash text check(evidence_hash is null or evidence_hash ~ '^[a-f0-9]{64}$'),
  original_output text,
  failure_code text,
  created_at timestamptz not null default now(),
  foreign key(project_id,team_id) references projects(id,team_id) on delete cascade,
  foreign key(task_run_step_id,task_run_id,project_id) references task_run_steps(id,task_run_id,project_id),
  foreign key(evidence_set_id,task_run_id,project_id) references inspection_evidence_sets(id,task_run_id,project_id),
  unique(task_run_step_id,project_id),
  unique(id,project_id)
);

create table inspection_assessment_revisions (
  assessment_id uuid not null,
  project_id integer not null,
  revision integer not null check(revision>0),
  source text not null check(source in('model','human')),
  decisions_json jsonb not null check(jsonb_typeof(decisions_json)='array'),
  reviewed_by_user_id integer references users(id),
  idempotency_key text not null,
  created_at timestamptz not null default now(),
  primary key(assessment_id,revision),
  foreign key(assessment_id,project_id) references inspection_assessments(id,project_id),
  unique(assessment_id,idempotency_key),
  check((source='human')=(reviewed_by_user_id is not null))
);

create table inspection_issue_sources (
  project_id integer not null,
  source_key text not null,
  issue_id integer not null,
  assessment_id uuid not null,
  created_at timestamptz not null default now(),
  primary key(project_id,source_key),
  foreign key(issue_id,project_id) references issues(id,project_id),
  foreign key(assessment_id,project_id) references inspection_assessments(id,project_id)
);

-- Unknown flights are held for classification only when the connector explicitly
-- opts into task-managed alerts. The absence of a row preserves legacy behavior.
create table inspection_connector_policies (
  project_id integer not null,
  team_id integer not null,
  connector_instance_id bigint not null,
  task_managed_alerts boolean not null default false,
  primary key(project_id,connector_instance_id),
  foreign key(project_id,team_id) references projects(id,team_id) on delete cascade,
  foreign key(connector_instance_id,project_id) references device_adapters(id,project_id)
);

create table inspection_flight_ownership (
  project_id integer not null,
  connector_instance_id bigint not null,
  remote_flight_id text not null,
  ownership text not null check(ownership in('pending','task','legacy')),
  task_run_id integer,
  created_at timestamptz not null default now(),
  primary key(project_id,connector_instance_id,remote_flight_id),
  foreign key(connector_instance_id,project_id) references device_adapters(id,project_id),
  foreign key(task_run_id,project_id) references task_runs(id,project_id),
  check(ownership<>'task' or task_run_id is not null)
);
