import "server-only";
import {withAuditedProjectWrite} from "@/lib/audit";import {requireCurrentProjectPermission} from "@/lib/data";import {query} from "@/lib/db";import {correlationId} from "@/lib/observability";import {aggregateInspectionReport,planReportPublication,type ReportEvidenceReference} from "@/lib/report-aggregation-core";

export async function createTaskRunReportDraft(projectId:number,taskRunId:number,requestId?:string|null){const {user,access}=await requireCurrentProjectPermission(projectId,"mission:operate");
  const run=(await query<Record<string,unknown>>(`select run.id,run.status,run.state_version as "stateVersion",run.started_at as "startedAt",run.finished_at as "finishedAt",run.task_version_id as "taskVersionId",run.selected_device_id as "deviceId",task.name as "taskName",version.version as "taskVersion",version.definition_json as definition,device.name as "deviceName",device.type as "deviceType",device.updated_at as "deviceUpdatedAt" from task_runs run join tasks task on task.id=run.task_id and task.project_id=run.project_id left join task_versions version on version.id=run.task_version_id and version.project_id=run.project_id left join devices device on device.id=run.selected_device_id and device.project_id=run.project_id where run.project_id=$1 and run.id=$2`,[projectId,taskRunId])).rows[0];if(!run)throw new Error("TASK_RUN_NOT_FOUND");if(!["succeeded","failed","canceled"].includes(String(run.status)))throw new Error("REPORT_TASK_RUN_NOT_TERMINAL");
  const steps=(await query<Record<string,unknown>>(`select run_step.id,run_step.position,step.step_key as key,step.name,step.uses,
    run_step.status,run_step.input_snapshot_json as "inputSnapshot",run_step.output_snapshot_json as "outputSnapshot",
    run_step.condition_result_json as "conditionResult",run_step.result_json as result,run_step.finished_at as "finishedAt"
    from task_run_steps run_step join task_steps step on step.id=run_step.task_step_id and step.project_id=run_step.project_id
    where run_step.project_id=$1 and run_step.task_run_id=$2 order by run_step.position`,[projectId,taskRunId])).rows;
  const track=(await query<Record<string,unknown>>(`select count(*)::int as "pointCount",min(pose.captured_at) as "startedAt",max(pose.captured_at) as "endedAt",min(pose.spatial_quality) as quality from poses pose where pose.project_id=$1 and pose.device_id=$2 and ($3::timestamptz is null or pose.captured_at>=$3) and ($4::timestamptz is null or pose.captured_at<=$4) having count(*)>0`,[projectId,run.deviceId??null,run.startedAt??null,run.finishedAt??null])).rows[0]??null;
  const issues=(await query<Record<string,unknown>>(`select id,number,title,status,priority,condition_scope_key as "conditionScopeKey",
    task_version_id as "taskVersionId",created_at as "createdAt",updated_at as "updatedAt"
    from issues where project_id=$1 and task_run_id=$2 order by number`,[projectId,taskRunId])).rows;
  const issueIds=issues.map(issue=>Number(issue.id));
  const comments=issueIds.length?(await query<Record<string,unknown>>(`select event.id,event.issue_id as "issueId",event.event_type as "eventType",
    event.body,event.metadata_json as metadata,event.created_at as "createdAt",coalesce(actor.name,agent.name,'系统') as "actorName"
    from issue_events event left join users actor on actor.id=event.actor_user_id
    left join agents agent on agent.id=event.actor_agent_id and agent.project_id=event.project_id
    where event.project_id=$1 and event.issue_id=any($2::int[]) and event.event_type in(
      'comment.created','comment','status.changed','feedback.confirm','feedback.false_positive','feedback.category_correction','feedback.disposition','copilot.completed')
    order by event.created_at,event.id`,[projectId,issueIds])).rows:[];
  const feedback=issueIds.length?(await query<Record<string,unknown>>(`select id,issue_id as "issueId",detection_id as "detectionId",
    action,corrected_label as "correctedLabel",disposition,reason,evidence_snapshot_json as "evidenceSnapshot",created_at as "createdAt"
    from issue_feedback where project_id=$1 and issue_id=any($2::int[]) order by created_at,id`,[projectId,issueIds])).rows:[];
  const assets=(await query<Record<string,unknown>>(`select id,version,checksum_sha256 as checksum,captured_at as "capturedAt" from assets where project_id=$1 and task_run_id=$2 and status='available' and deleted_at is null order by created_at`,[projectId,taskRunId])).rows;
  const refs:ReportEvidenceReference[]=[
    {type:"task_run",id:String(run.id),version:`state:${String(run.stateVersion)}`,href:`/projects/${projectId}/tasks/runs/${taskRunId}`},
    ...(run.taskVersionId?[{type:"task_version" as const,id:String(run.taskVersionId),version:String(run.taskVersion),href:`/projects/${projectId}/tasks`}]:[]),
    ...(run.deviceId?[{type:"device" as const,id:String(run.deviceId),version:String(run.deviceUpdatedAt),href:`/projects/${projectId}/devices?selected=${String(run.deviceId)}`}]:[]),
    ...(track?[{type:"track" as const,id:String(run.deviceId),version:`${String(track.pointCount)}:${String(track.endedAt)}`,href:`/projects/${projectId}?selected=${String(run.deviceId)}`}]:[]),
    ...steps.map(step=>({type:"step" as const,id:String(step.id),version:String(step.status),href:`/projects/${projectId}/tasks/runs/${taskRunId}#step-${String(step.id)}`})),
    ...issues.map(issue=>({type:"event" as const,id:`issue:${String(issue.id)}`,version:String(issue.updatedAt),href:`/projects/${projectId}/issues/${String(issue.id)}`})),
    ...comments.map(item=>({type:"event" as const,id:`comment:${String(item.id)}`,version:String(item.createdAt),href:`/projects/${projectId}/issues/${String(item.issueId)}#activity`})),
    ...feedback.map(item=>({type:"feedback" as const,id:String(item.id),version:String(item.createdAt),href:`/projects/${projectId}/issues/${String(item.issueId)}`})),
    ...assets.map(asset=>({type:"asset" as const,id:String(asset.id),version:String(asset.checksum??`version:${String(asset.version)}`),assetId:Number(asset.id),checksumSha256:asset.checksum?String(asset.checksum):null,href:`/projects/${projectId}/assets?selected=${String(asset.id)}`}))
  ];
  const content=aggregateInspectionReport({projectId,taskRun:run,
    taskVersion:run.taskVersionId?{id:run.taskVersionId,version:run.taskVersion,definition:run.definition}:null,
    device:run.deviceId?{id:run.deviceId,name:run.deviceName,type:run.deviceType}:null,
    track,steps,issues,comments,feedback,evidence:refs});
  return withAuditedProjectWrite({projectId,teamId:access.teamId,actorUserId:user.id,requestId:correlationId(requestId),action:"generated_report.create_draft",resourceType:"task_run",resourceId:String(taskRunId),input:{completeness:content.completeness},policyResult:{permission:"mission:operate"}},async client=>{const report=(await client.query<{id:string}>(`insert into generated_reports(project_id,team_id,source_type,source_id,title,created_by_user_id) values($1,$2,'task_run',$3,$4,$5) on conflict(project_id,source_type,source_id) do update set title=excluded.title,updated_at=now() returning id`,[projectId,access.teamId,String(taskRunId),`${String(run.taskName)} 巡检报告`,user.id])).rows[0];await client.query(`update generated_report_versions set status='retired' where project_id=$1 and generated_report_id=$2 and status='draft'`,[projectId,report.id]);const next=(await client.query<{version:number}>(`select coalesce(max(version),0)::int+1 as version from generated_report_versions where generated_report_id=$1`,[report.id])).rows[0].version;const version=(await client.query<{id:string}>(`insert into generated_report_versions(project_id,team_id,generated_report_id,version,completeness,content_json,data_gaps_json,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8) returning id`,[projectId,access.teamId,report.id,next,content.completeness,content,content.dataGaps,user.id])).rows[0];for(const ref of refs)await client.query(`insert into generated_report_evidence(project_id,report_version_id,evidence_type,evidence_id,evidence_version,asset_id,checksum_sha256,href) values($1,$2,$3,$4,$5,$6,$7,$8)`,[projectId,version.id,ref.type,ref.id,ref.version,ref.assetId??null,ref.checksumSha256??null,ref.href]);return {reportId:report.id,versionId:version.id,version:next,completeness:content.completeness,dataGaps:content.dataGaps}})}

export async function publishGeneratedReport(projectId:number,reportId:string,allowIncomplete:boolean,requestId?:string|null){const {user,access}=await requireCurrentProjectPermission(projectId,"mission:operate");return withAuditedProjectWrite({projectId,teamId:access.teamId,actorUserId:user.id,requestId:correlationId(requestId),action:"generated_report.publish",resourceType:"generated_report",resourceId:reportId,input:{allowIncomplete},policyResult:{permission:"mission:operate"}},async client=>{const version=(await client.query<{id:string;completeness:"complete"|"incomplete"|"failed";content:{evidence:ReportEvidenceReference[]}}>(`select id,completeness,content_json as content from generated_report_versions where project_id=$1 and generated_report_id=$2 and status='draft' for update`,[projectId,reportId])).rows[0];if(!version)throw new Error("REPORT_DRAFT_NOT_FOUND");const plan=planReportPublication({completeness:version.completeness,evidence:version.content.evidence??[]},{allowIncomplete});await client.query(`update generated_report_versions set status='retired' where project_id=$1 and generated_report_id=$2 and status='published'`,[projectId,reportId]);await client.query(`update generated_report_versions set status='published',published_by_user_id=$3,published_at=now() where project_id=$1 and id=$2`,[projectId,version.id,user.id]);await client.query(`update generated_reports set current_published_version_id=$3,updated_at=now() where project_id=$1 and id=$2`,[projectId,reportId,version.id]);if(plan.retainedAssetIds.length)await client.query(`update assets set legal_hold=true,retention_reason='published-report:'||$2 where project_id=$1 and id=any($3::int[])`,[projectId,reportId,plan.retainedAssetIds]);return {reportId,versionId:version.id,status:plan.status,completeness:version.completeness,retainedAssetIds:plan.retainedAssetIds}})}

export async function exportGeneratedReport(projectId:number,reportId:string){await requireCurrentProjectPermission(projectId,"report:export");const report=(await query<Record<string,unknown>>(`select report.id,report.title,version.version,version.completeness,version.content_json as content,version.data_gaps_json as "dataGaps",version.published_at as "publishedAt" from generated_reports report join generated_report_versions version on version.id=report.current_published_version_id and version.project_id=report.project_id where report.project_id=$1 and report.id=$2 and version.status='published'`,[projectId,reportId])).rows[0];if(!report)throw new Error("PUBLISHED_REPORT_NOT_FOUND");return report}
