import { EvidenceImage } from "@/components/evidence-image";
import { Page } from "@/components/page";
import { Badge } from "@/components/ui/badge";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { readPerceptionEvent } from "@/lib/perception-events";

export default async function PerceptionEventPage({params}:{params:Promise<{id:string;eventId:string}>}){
  const {id,eventId}=await params;const projectId=Number(id);const model=await readPerceptionEvent(projectId,eventId);const event=model.event;
  return <Page title="疑似违建" description={String(event.disclaimer)}><div className="space-y-4">
    <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardDescription>处置状态</CardDescription><CardTitle><Badge>{String(event.status)}</Badge></CardTitle></CardHeader><CardContent>{String(event.severity)} · {String(event.occurrenceCount)} 次线索</CardContent></Card><Card><CardHeader><CardDescription>位置</CardDescription><CardTitle>{event.hasMapLocation?"可在地图展示":"仅影像级"}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{String(event.locationSummary)}</CardContent></Card><Card><CardHeader><CardDescription>规则依据</CardDescription><CardTitle>{String(event.ruleName)}</CardTitle></CardHeader><CardContent>规则版本 v{String(event.ruleVersion)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>证据链</CardTitle><CardDescription>原图、像素标注、位置质量与模型版本均固定到检测记录</CardDescription></CardHeader><CardContent className="space-y-5">{model.detections.map(detection=><div className="grid gap-4 border-b pb-5 last:border-0 lg:grid-cols-2" key={String(detection.id)}><EvidenceImage assetId={Number(detection.inputAssetId)} projectId={projectId}/><div className="space-y-2 text-sm"><div className="flex gap-2"><Badge variant="outline">{String(detection.label)}</Badge><Badge variant="outline">置信度 {Number(detection.confidence).toFixed(2)}</Badge></div><p>位置质量：{String(detection.locationQuality)} · 误差 {String(detection.horizontalErrorMeters??"-")} m</p><p>投影：{String(detection.projectionMethod)}</p><p>模型：{String(detection.modelOrProcess)} v{String(detection.modelVersion)} · mapping {String(detection.mappingVersion)}</p><p>原始资产：#{String(detection.inputAssetId)} v{String(detection.assetVersion)}</p><pre className="overflow-auto rounded-lg bg-muted p-3 text-xs">像素标注 {JSON.stringify(detection.pixelGeometry,null,2)}</pre></div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>处置记录</CardTitle></CardHeader><CardContent>{model.feedback.length?<div className="space-y-2">{model.feedback.map(item=><div className="rounded-lg border p-3 text-sm" key={String(item.id)}>{String(item.action)} · {String(item.actorName)}<p className="text-muted-foreground">{String(item.reason)}</p></div>)}</div>:<p className="text-sm text-muted-foreground">尚无人工处置记录</p>}</CardContent></Card>
  </div></Page>
}
