"use client";
import Link from "next/link";
import {Page} from "@/components/page";
import {StaticAPIPage,positiveParam,uuidParam} from "@/components/static-api-page";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
type Issue={id:number;title:string;status:string};
type Sections={taskRun?:{id:number};issues?:Issue[]};
type Model={id:string;title:string;version:number;status:string;completeness:string;dataGaps?:Array<string|{message?:string;code?:string;section?:string}>;evidence?:Array<{kind:string;id:string;availability:string}>;content?:Sections&{sections?:Sections;inspection?:{scopeNotice:string;evidenceSets?:Array<{id:string;source:string;modelVersion:string;completeness:string}>;observations?:Array<{id:string;mode:string;observedFrom:string;observedTo:string;scopeDescription:string;completeness:string;assets?:unknown[]}>;assessments?:Array<{id:string;status:string;revision:number;decisions:unknown}>}}};
export default function ReportPage(){return <StaticAPIPage<Model> endpoint={q=>{const pid=positiveParam(q),id=uuidParam(q,"reportId");return pid&&id?`/api/projects/${pid}/reports/${id}`:null;}}>{(report,q)=>{const pid=positiveParam(q)!;const content=report.content??{};const sections=content.sections??content;const issues=sections.issues??[];const run=sections.taskRun;const inspection=content.inspection;const gaps=report.dataGaps??[];return <Page title={report.title} description={`报告版本 ${report.version} · ${report.status} · ${report.completeness}`}>
 <div className="space-y-4">
 {run?.id&&<Link className="text-sm underline" href={`/projects/tasks/runs/detail/?projectId=${pid}&runId=${run.id}`}>返回任务运行</Link>}
 {inspection&&<Card><CardHeader><CardTitle>本次分析范围</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm">{inspection.scopeNotice}</p>{inspection.observations?.map(observation=><div className="rounded border p-3 text-sm" key={observation.id}><p>{observation.scopeDescription}</p><p>{observation.mode==="assets"?"既有图片":observation.mode==="existing-flight"?"司空已完成飞行":observation.mode==="flighthub-flight"?"司空飞行":"未标明来源"} · {(observation.assets??[]).length} 张图片 · {observation.completeness}</p><p>{observation.observedFrom} — {observation.observedTo}</p><a className="underline" href={`/projects/inspection/observation/?projectId=${pid}&observationId=${observation.id}`} target="_blank" rel="noreferrer">观察与原图版本</a></div>)}</CardContent></Card>}
 {gaps.length>0&&<Card><CardHeader><CardTitle>资料缺口</CardTitle></CardHeader><CardContent><ul className="list-inside list-disc text-sm">{gaps.map((gap,index)=><li key={index}>{typeof gap==="string"?gap:gap.message??[gap.section,gap.code].filter(Boolean).join(": ")}</li>)}</ul></CardContent></Card>}
 {(report.evidence??[]).some(e=>e.availability==="unavailable-or-version-changed")&&<p role="alert" className="text-sm text-destructive">部分原图已不可用或版本已变化。报告保留的是生成时的证据快照，不能用当前文件替代。</p>}
 {inspection?.evidenceSets?.map(evidence=><p key={evidence.id} className="text-sm"><Link className="underline" href={`/projects/inspection/evidence/?projectId=${pid}&evidenceSetId=${evidence.id}`}>查看识别证据</Link> · {evidence.source} · {evidence.modelVersion} · {evidence.completeness}</p>)}
 <Card><CardHeader><CardTitle>研判与复核</CardTitle></CardHeader><CardContent className="space-y-3">{inspection?.assessments?.map(assessment=><div key={assessment.id} className="rounded border p-3"><Link className="text-sm underline" href={`/projects/inspection/assessment/?projectId=${pid}&assessmentId=${assessment.id}`}>查看研判 · 修订 {assessment.revision} · {assessment.status}</Link><pre className="mt-2 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(assessment.decisions,null,2)}</pre></div>)}{!inspection?.assessments?.length&&<p className="text-sm text-muted-foreground">此报告没有已记录的研判结果。</p>}</CardContent></Card>
 <Card><CardHeader><CardTitle>关联案件（{issues.length}）</CardTitle></CardHeader><CardContent className="space-y-2">{issues.map(issue=><div key={issue.id}><Link className="text-sm underline" href={`/projects/issues/detail/?projectId=${pid}&issueId=${issue.id}`}>{issue.title}</Link><span className="ml-2 text-xs">{issue.status}</span></div>)}{!issues.length&&<p className="text-sm">未生成案件。请结合上方研判及分析范围理解这一结果。</p>}</CardContent></Card>
 </div>
 </Page>;}}</StaticAPIPage>;}
