package media

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestMediaAccessOriginalTSSignature(t *testing.T) {
	now, _ := time.Parse(time.RFC3339, "2026-08-27T00:00:00Z")
	result, err := IssueAccess("0123456789abcdef", 17, 42, "preview", now, 30)
	// Generated by the original TS MediaAccessSigner, rather than by this signer.
	signature := "091cb7a878d9bdb599281c2b6db1c15f1d78afa383badb790b444b533becd691"
	if err != nil || result.URL != "/api/projects/17/assets/42/content?action=preview&expires=1787788830000&signature="+signature || result.ExpiresAt != "2026-08-27T00:00:30.000Z" {
		t.Fatalf("fixture %+v %v", result, err)
	}
	if !VerifyAccess("0123456789abcdef", 17, 42, "preview", "1787788830000", signature, now) {
		t.Fatal("old signature rejected")
	}
	for _, v := range []struct {
		pid, aid             int32
		action, expires, sig string
		now                  time.Time
	}{{18, 42, "preview", "1787788830000", signature, now}, {17, 43, "preview", "1787788830000", signature, now}, {17, 42, "download", "1787788830000", signature, now}, {17, 42, "preview", "1787788830000", signature, now.Add(30 * time.Second)}, {17, 42, "preview", "1787788830000", signature + "x", now}} {
		if VerifyAccess("0123456789abcdef", v.pid, v.aid, v.action, v.expires, v.sig, v.now) {
			t.Fatalf("forged %+v", v)
		}
	}
	if AccessAllowed("download", "member", nil, true) || !AccessAllowed("preview", "member", nil, true) || !AccessAllowed("download", "member", map[string]bool{"event:handle": true}, true) {
		t.Fatal("media permission")
	}
	name := "Ａ frame\r\nattachment.exe"
	if SafeDownloadName(&name, "asset-42") != "A-frame-attachment.exe" {
		t.Fatal("filename normalization")
	}
}

func TestMediaProjectFileBoundary(t *testing.T) {
	root := t.TempDir()
	project := filepath.Join(root, "projects", "17")
	if err := os.MkdirAll(project, 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(project, "frame.jpg"), []byte("frame"), 0600); err != nil {
		t.Fatal(err)
	}
	file, err := OpenProjectObject(root, 17, "projects/17/frame.jpg")
	if err != nil {
		t.Fatal(err)
	}
	file.Close()
	for _, key := range []string{"projects/18/frame.jpg", "projects/17/../18/frame.jpg", "projects/17/../../outside", "projects/17/dir/../frame.jpg", `projects/17\frame.jpg`, "projects/17/frame.jpg:secret", "projects/17/"} {
		if file, err := OpenProjectObject(root, 17, key); err == nil {
			file.Close()
			t.Fatalf("accepted %s", key)
		}
	}
	outside := filepath.Join(t.TempDir(), "outside")
	os.WriteFile(outside, []byte("secret"), 0600)
	if err := os.Symlink(outside, filepath.Join(project, "escape")); err != nil {
		t.Logf("symlink setup unavailable: %v", err)
	} else if file, err := OpenProjectObject(root, 17, "projects/17/escape"); err == nil {
		file.Close()
		t.Fatal("symlink escaped project")
	}
	if strings.Contains(SafeDownloadName(nil, "asset-42"), "\n") {
		t.Fatal("unsafe fallback")
	}
}
