type AccessRow = {
    projectId: number;
    teamId: number;
    role: "owner" | "admin" | "member";
    canOperate: boolean;
};
type ConnectorRow = {
    id: string;
    name: string;
    status: string;
    lastCheckedAt: Date | string | null;
    actionEnabled: boolean;
    actionVerified: boolean;
};
type WaylineRow = {
    id: string;
    connectorId: string;
    taskId: number | null;
    name: string | null;
    status: string;
    deviceModelKey: string | null;
    templateTypes: unknown;
    payloadCount: number | string | null;
    sizeBytes: number | string | null;
    remoteUpdatedAt: Date | string | null;
    lastSeenAt: Date | string;
};
type FlightTaskRunRow = {
    id: string;
    connectorId: string;
    taskRunId: number;
    taskId: number;
    taskName: string;
    deviceId: number | null;
    deviceName: string | null;
    status: string;
    stateReason: string | null;
    taskType: string | null;
    mediaUploadStatus: string | null;
    resumableStatus: string | null;
    breakPointResume: boolean | null;
    currentWaypoint: number | string | null;
    totalWaypoints: number | string | null;
    exceptionCount: number | string | null;
    startedAt: Date | string | null;
    finishedAt: Date | string | null;
    remoteUpdatedAt: Date | string | null;
};
type TrackRow = {
    id: number;
    connectorId: string;
    taskRunId: number;
    taskName: string;
    deviceId: number;
    deviceName: string;
    pointCount: number | string;
    firstCapturedAt: Date | string;
    lastCapturedAt: Date | string;
};
type AssetRow = {
    id: string;
    connectorId: string;
    assetId: number;
    taskRunId: number | null;
    deviceId: number | null;
    name: string | null;
    kind: string;
    mimeType: string | null;
    status: string;
    fileType: string | null;
    suffix: string | null;
    sizeBytes: number | string | null;
    contentType: string | null;
    progress: number | string | null;
    fileTypes: unknown;
    failedReasonCode: string | null;
    capturedAt: Date | string | null;
    createdAt: Date | string;
};
type AlertRow = {
    id: string;
    connectorId: string;
    kind: string;
    taskRunId: number | null;
    perceptionEventId: string | null;
    issueId: number | null;
    title: string | null;
    severity: string | null;
    status: string | null;
    alertCount: number | string | null;
    confidence: number | string | null;
    hasMedia: boolean | null;
    occurredAt: Date | string | null;
    lastSeenAt: Date | string;
};
type ActionRow = {
    id: string;
    connectorId: string;
    taskRunId: number;
    deviceId: number;
    waylineResourceId: string | null;
    targetResourceId: string | null;
    resultResourceId: string | null;
    action: string;
    status: string;
    attemptCount: number;
    reconciliationCount: number;
    lastErrorCode: string | null;
    acceptedAt: Date | string | null;
    reconciledAt: Date | string | null;
    unknownAt: Date | string | null;
    completedAt: Date | string | null;
    createdAt: Date | string;
    updatedAt: Date | string;
};
export type FlightHubFlightOperations = ReturnType<typeof presentFlightOperations>;
declare function presentFlightOperations(access: AccessRow, connectors: ConnectorRow[], waylines: WaylineRow[], taskRuns: FlightTaskRunRow[], tracks: TrackRow[], media: AssetRow[], flightRecords: AssetRow[], alerts: AlertRow[], actions: ActionRow[]): {
    access: {
        mode: "operator" | "read-only";
        canOperate: boolean;
    };
    connectors: {
        id: string;
        name: string;
        status: string;
        lastCheckedAt: string | null;
        actionEnabled: boolean;
        actionVerified: boolean;
        actionReady: boolean;
        availableActions: ("flight-task-create" | "flight-task-status" | "flight-task-resumption")[];
    }[];
    waylines: {
        id: string;
        connectorId: string;
        taskId: number | null;
        name: string;
        status: string;
        deviceModelKey: string | null;
        templateTypes: string[];
        payloadCount: number | null;
        sizeBytes: number | null;
        remoteUpdatedAt: string | null;
        lastSeenAt: string | null;
    }[];
    taskRuns: {
        id: string;
        connectorId: string;
        taskRunId: number;
        taskId: number;
        taskName: string;
        deviceId: number | null;
        deviceName: string | null;
        status: string;
        stateReason: string | null;
        taskType: string | null;
        mediaUploadStatus: string | null;
        resumableStatus: string | null;
        breakPointResume: boolean | null;
        currentWaypoint: number | null;
        totalWaypoints: number | null;
        exceptionCount: number | null;
        startedAt: string | null;
        finishedAt: string | null;
        remoteUpdatedAt: string | null;
    }[];
    tracks: {
        id: number;
        connectorId: string;
        taskRunId: number;
        taskName: string;
        deviceId: number;
        deviceName: string;
        pointCount: number;
        firstCapturedAt: string | null;
        lastCapturedAt: string | null;
    }[];
    media: {
        id: string;
        connectorId: string;
        assetId: number;
        taskRunId: number | null;
        deviceId: number | null;
        name: string;
        kind: string;
        mimeType: string | null;
        status: string;
        fileType: string | null;
        suffix: string | null;
        sizeBytes: number | null;
        capturedAt: string | null;
        createdAt: string | null;
    }[];
    flightRecords: {
        id: string;
        connectorId: string;
        assetId: number;
        taskRunId: number | null;
        name: string;
        kind: string;
        mimeType: string | null;
        status: string;
        contentType: string | null;
        progress: number | null;
        fileTypes: string[];
        failedReasonCode: string | null;
        capturedAt: string | null;
        createdAt: string | null;
    }[];
    alerts: {
        id: string;
        connectorId: string;
        kind: string;
        taskRunId: number | null;
        perceptionEventId: string | null;
        issueId: number | null;
        title: string;
        severity: string | null;
        status: string | null;
        alertCount: number | null;
        confidence: number | null;
        hasMedia: boolean;
        occurredAt: string | null;
        lastSeenAt: string | null;
    }[];
    actions: {
        id: string;
        connectorId: string;
        taskRunId: number;
        deviceId: number;
        waylineResourceId: string | null;
        targetResourceId: string | null;
        resultResourceId: string | null;
        action: string;
        status: string;
        final: boolean;
        attemptCount: number;
        reconciliationCount: number;
        lastErrorCode: string | null;
        acceptedAt: string | null;
        reconciledAt: string | null;
        unknownAt: string | null;
        completedAt: string | null;
        createdAt: string | null;
        updatedAt: string | null;
    }[];
};
export {};
