type GeospatialKind = "map-element" | "flight-area" | "offline-map" | "air-sense-warning";
type Freshness = "fresh" | "stale" | "missing" | "unknown";
type AccessRow = {
    projectId: number;
    teamId: number;
    role: "owner" | "admin" | "member";
};
type ConnectorRow = {
    projectId: number;
    id: string;
    name: string;
    status: string;
    lastCheckedAt: Date | string | null;
};
type SyncRow = {
    projectId: number;
    connectorId: string;
    status: string;
    attemptCount: number | string;
    lastErrorCode: string | null;
    lastStartedAt: Date | string | null;
    lastSucceededAt: Date | string | null;
    nextAttemptAt: Date | string | null;
};
type ResourceRow = {
    projectId: number;
    id: string;
    connectorId: string;
    kind: GeospatialKind;
    status: string;
    remoteVersion: string | null;
    remoteUpdatedAt: Date | string | null;
    lastSeenAt: Date | string;
    missingAt: Date | string | null;
    name: string | null;
    geometry: unknown;
    coordinateReference: string | null;
    stateCode: string | null;
    display: string | null;
    areaType: string | null;
    progress: string | null;
    resultCode: string | null;
    modelCount: string | null;
    modelNames: unknown;
    warningLevel: string | null;
    deviceId: string | null;
    expiresAt: string | null;
    expired: string | null;
    issueId: number | string | null;
};
export type FlightHubGeospatialGeometry = {
    type: "Point" | "LineString" | "Polygon";
    coordinates: number[] | number[][] | number[][][];
};
export type FlightHubGeospatialWorkspace = ReturnType<typeof presentFlightHubGeospatial>;
export declare function presentFlightHubGeospatial(projectId: number, access: AccessRow, connectors: ConnectorRow[], syncStates: SyncRow[], resourceRows: ResourceRow[], now?: Date): {
    projectId: number;
    access: {
        role: "owner" | "admin" | "member";
        mode: "read-only";
    };
    source: "dji-flighthub-openapi";
    connectors: {
        id: string;
        name: string;
        status: string;
        lastCheckedAt: string | null;
    }[];
    syncStates: {
        connectorId: string;
        status: string;
        attemptCount: number;
        lastErrorCode: string | null;
        lastStartedAt: string | null;
        lastSucceededAt: string | null;
        nextAttemptAt: string | null;
    }[];
    mapElements: {
        stateCode: string | null;
        display: boolean | null;
        id: string;
        connectorId: string;
        name: string;
        source: "dji-flighthub-openapi";
        status: string;
        versionFingerprint: string | null;
        freshness: Freshness;
        coordinateReference: string | null;
        geometry: FlightHubGeospatialGeometry | null;
        geometryType: string | null;
        remoteUpdatedAt: string | null;
        lastSeenAt: string | null;
        missingAt: string | null;
    }[];
    flightAreas: {
        areaType: string | null;
        stateCode: string | null;
        id: string;
        connectorId: string;
        name: string;
        source: "dji-flighthub-openapi";
        status: string;
        versionFingerprint: string | null;
        freshness: Freshness;
        coordinateReference: string | null;
        geometry: FlightHubGeospatialGeometry | null;
        geometryType: string | null;
        remoteUpdatedAt: string | null;
        lastSeenAt: string | null;
        missingAt: string | null;
    }[];
    offlineMaps: {
        progress: number | null;
        resultCode: string | null;
        modelCount: number;
        modelNames: string[];
        stateCode: string | null;
        id: string;
        connectorId: string;
        name: string;
        source: "dji-flighthub-openapi";
        status: string;
        versionFingerprint: string | null;
        freshness: Freshness;
        coordinateReference: string | null;
        geometry: FlightHubGeospatialGeometry | null;
        geometryType: string | null;
        remoteUpdatedAt: string | null;
        lastSeenAt: string | null;
        missingAt: string | null;
    }[];
    airSenseWarnings: {
        warningLevel: number | null;
        deviceId: number | null;
        issueId: number | null;
        expiresAt: string | null;
        id: string;
        connectorId: string;
        name: string;
        source: "dji-flighthub-openapi";
        status: string;
        versionFingerprint: string | null;
        freshness: Freshness;
        coordinateReference: string | null;
        geometry: FlightHubGeospatialGeometry | null;
        geometryType: string | null;
        remoteUpdatedAt: string | null;
        lastSeenAt: string | null;
        missingAt: string | null;
    }[];
};
export {};
