// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const appendChatMessage = `-- name: AppendChatMessage :one
INSERT INTO agent_messages(session_id,role,content,tool_calls_json) VALUES($1,$2,$3,$4) RETURNING id,created_at
`

type AppendChatMessageParams struct {
	SessionID     int32           `json:"session_id"`
	Role          string          `json:"role"`
	Content       string          `json:"content"`
	ToolCallsJson json.RawMessage `json:"tool_calls_json"`
}

type AppendChatMessageRow struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AppendChatMessage(ctx context.Context, arg AppendChatMessageParams) (AppendChatMessageRow, error) {
	row := q.db.QueryRowContext(ctx, appendChatMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ToolCallsJson,
	)
	var i AppendChatMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO agent_sessions(project_id,status,started_by_user_id) VALUES($1,'open',$2) RETURNING id
`

type CreateChatSessionParams struct {
	ProjectID       int32         `json:"project_id"`
	StartedByUserID sql.NullInt32 `json:"started_by_user_id"`
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createChatSession, arg.ProjectID, arg.StartedByUserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT message.id,message.session_id,message.role,message.content,message.tool_calls_json,message.created_at
FROM agent_messages message JOIN agent_sessions session ON session.id=message.session_id
WHERE session.project_id=$1 AND session.started_by_user_id=$2 AND session.id=ANY($3::int[])
ORDER BY message.created_at,message.id
`

type ListChatMessagesParams struct {
	ProjectID       int32         `json:"project_id"`
	StartedByUserID sql.NullInt32 `json:"started_by_user_id"`
	SessionIds      []int32       `json:"session_ids"`
}

type ListChatMessagesRow struct {
	ID            int32           `json:"id"`
	SessionID     int32           `json:"session_id"`
	Role          string          `json:"role"`
	Content       string          `json:"content"`
	ToolCallsJson json.RawMessage `json:"tool_calls_json"`
	CreatedAt     time.Time       `json:"created_at"`
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ListChatMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessages, arg.ProjectID, arg.StartedByUserID, pq.Array(arg.SessionIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatMessagesRow{}
	for rows.Next() {
		var i ListChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.ToolCallsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatSessions = `-- name: ListChatSessions :many
SELECT id,status,summary,created_at FROM agent_sessions
WHERE project_id=$1 AND started_by_user_id=$2 ORDER BY created_at DESC,id DESC LIMIT 50
`

type ListChatSessionsParams struct {
	ProjectID       int32         `json:"project_id"`
	StartedByUserID sql.NullInt32 `json:"started_by_user_id"`
}

type ListChatSessionsRow struct {
	ID        int32          `json:"id"`
	Status    string         `json:"status"`
	Summary   sql.NullString `json:"summary"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) ListChatSessions(ctx context.Context, arg ListChatSessionsParams) ([]ListChatSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatSessions, arg.ProjectID, arg.StartedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatSessionsRow{}
	for rows.Next() {
		var i ListChatSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChatSession = `-- name: LockChatSession :one
SELECT id FROM agent_sessions WHERE id=$1 AND project_id=$2 AND started_by_user_id=$3 AND status='open' FOR UPDATE
`

type LockChatSessionParams struct {
	ID              int32         `json:"id"`
	ProjectID       int32         `json:"project_id"`
	StartedByUserID sql.NullInt32 `json:"started_by_user_id"`
}

func (q *Queries) LockChatSession(ctx context.Context, arg LockChatSessionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockChatSession, arg.ID, arg.ProjectID, arg.StartedByUserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const recentChatHistory = `-- name: RecentChatHistory :many
SELECT recent.role,recent.content FROM (
 SELECT message.id,message.role,message.content FROM agent_messages message
 JOIN agent_sessions session ON session.id=message.session_id
 WHERE session.id=$1 AND session.project_id=$2 AND session.started_by_user_id=$3 AND session.status='open'
 AND message.role IN ('user','assistant') ORDER BY message.id DESC LIMIT 20
) recent ORDER BY recent.id
`

type RecentChatHistoryParams struct {
	ID              int32         `json:"id"`
	ProjectID       int32         `json:"project_id"`
	StartedByUserID sql.NullInt32 `json:"started_by_user_id"`
}

type RecentChatHistoryRow struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) RecentChatHistory(ctx context.Context, arg RecentChatHistoryParams) ([]RecentChatHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, recentChatHistory, arg.ID, arg.ProjectID, arg.StartedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentChatHistoryRow{}
	for rows.Next() {
		var i RecentChatHistoryRow
		if err := rows.Scan(&i.Role, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
