// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_read_tools.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
)

const chatQueryAssets = `-- name: ChatQueryAssets :many
SELECT to_jsonb(result) FROM (
 SELECT asset.id,asset.kind,asset.mime_type AS "mimeType",asset.version,coalesce(asset.captured_at,asset.created_at) AS "observedAt",
 CASE WHEN asset.status='available' THEN 'verified-metadata' ELSE asset.status END AS quality
 FROM assets asset WHERE asset.project_id=$1 AND asset.status='available' AND asset.deleted_at IS NULL
 ORDER BY coalesce(asset.captured_at,asset.created_at) DESC,asset.id LIMIT 101
) result
`

func (q *Queries) ChatQueryAssets(ctx context.Context, projectID int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, chatQueryAssets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatQueryDevices = `-- name: ChatQueryDevices :many
SELECT to_jsonb(result) FROM (
 SELECT device.id,device.name,device.type,device.status,device_type.type_key AS "typeKey",device_type.version AS "typeVersion",
 driver.driver_key AS "driverKey",driver.version AS "driverVersion",device.last_seen_at AS "observedAt",coalesce(pose.spatial_quality,'unlocated') AS quality
 FROM devices device JOIN device_types device_type ON device_type.id=device.device_type_id
 JOIN driver_definitions driver ON driver.id=device_type.driver_definition_id
 LEFT JOIN LATERAL(SELECT p.spatial_quality FROM poses p WHERE p.project_id=$1 AND p.device_id=device.id ORDER BY p.captured_at DESC LIMIT 1) pose ON true
 WHERE device.project_id=$1 AND (NOT $2::boolean OR device.id=ANY($3::int[]))
 ORDER BY device.updated_at DESC,device.id LIMIT 101
) result
`

type ChatQueryDevicesParams struct {
	ProjectID     int32   `json:"project_id"`
	FilterDevices bool    `json:"filter_devices"`
	DeviceIds     []int32 `json:"device_ids"`
}

func (q *Queries) ChatQueryDevices(ctx context.Context, arg ChatQueryDevicesParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, chatQueryDevices, arg.ProjectID, arg.FilterDevices, pq.Array(arg.DeviceIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatQueryIssues = `-- name: ChatQueryIssues :many
SELECT to_jsonb(result) FROM (
 SELECT issue.id,issue.number,issue.title,issue.priority,issue.status,issue.occurrence_count AS "occurrenceCount",issue.last_seen_at AS "observedAt",
 CASE WHEN EXISTS(SELECT 1 FROM issue_links link JOIN detections detection
 ON detection.project_id=link.project_id AND detection.id=CASE WHEN link.target_id~'^[0-9]+$'
 AND (length(link.target_id)<=18 OR (length(link.target_id)=19 AND link.target_id COLLATE "C"<='9223372036854775807')) THEN link.target_id::bigint END
 WHERE link.project_id=issue.project_id AND link.issue_id=issue.id AND link.link_type='detection' AND detection.geographic_geometry IS NOT NULL)
 THEN 'mapped-evidence' ELSE 'image-evidence' END AS quality
 FROM issues issue WHERE issue.project_id=$1 ORDER BY issue.last_seen_at DESC,issue.id LIMIT $2::int
) result
`

type ChatQueryIssuesParams struct {
	ProjectID   int32 `json:"project_id"`
	ResultLimit int32 `json:"result_limit"`
}

func (q *Queries) ChatQueryIssues(ctx context.Context, arg ChatQueryIssuesParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, chatQueryIssues, arg.ProjectID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatQueryMapContext = `-- name: ChatQueryMapContext :many
SELECT to_jsonb(result) FROM (
 SELECT 'current' AS id,now() AS "observedAt",'aggregated' AS quality,
 (SELECT count(*)::int FROM devices d WHERE d.project_id=$1) AS "deviceCount",
 (SELECT count(*)::int FROM issues i WHERE i.project_id=$1 AND i.status='open') AS "openIssueCount",
 (SELECT count(*)::int FROM task_runs r WHERE r.project_id=$1 AND r.status IN('queued','ready','dispatching','running','paused')) AS "activeMissionCount"
) result
`

func (q *Queries) ChatQueryMapContext(ctx context.Context, projectID int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, chatQueryMapContext, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatQueryTasks = `-- name: ChatQueryTasks :many
SELECT to_jsonb(result) FROM (
 SELECT run.id,task.name,run.status,run.state_reason AS reason,coalesce(run.finished_at,run.started_at,run.created_at) AS "observedAt",'platform-state' AS quality
 FROM task_runs run JOIN tasks task ON task.id=run.task_id AND task.project_id=run.project_id
 WHERE run.project_id=$1 ORDER BY run.created_at DESC,run.id LIMIT $2::int
) result
`

type ChatQueryTasksParams struct {
	ProjectID   int32 `json:"project_id"`
	ResultLimit int32 `json:"result_limit"`
}

func (q *Queries) ChatQueryTasks(ctx context.Context, arg ChatQueryTasksParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, chatQueryTasks, arg.ProjectID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatQueryTracks = `-- name: ChatQueryTracks :many
SELECT to_jsonb(result) FROM (
 SELECT pose.device_id AS id,pose.device_id AS "deviceId",min(pose.captured_at) AS "startedAt",max(pose.captured_at) AS "observedAt",count(*)::int AS "pointCount",
 ST_AsGeoJSON(ST_MakeLine(pose.standard_position ORDER BY pose.captured_at))::json AS geometry,min(pose.spatial_quality) AS quality
 FROM poses pose WHERE pose.project_id=$1 AND pose.standard_position IS NOT NULL
 GROUP BY pose.device_id ORDER BY max(pose.captured_at) DESC,pose.device_id LIMIT 101
) result
`

func (q *Queries) ChatQueryTracks(ctx context.Context, projectID int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, chatQueryTracks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
