// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_providers.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const clearAIProviderDefault = `-- name: ClearAIProviderDefault :exec
UPDATE ai_providers SET is_default=false,updated_at=now() WHERE is_default
`

func (q *Queries) ClearAIProviderDefault(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAIProviderDefault)
	return err
}

const createAIProvider = `-- name: CreateAIProvider :one
INSERT INTO ai_providers(name,provider_type,base_url,model_id,credential_envelope_json,enabled,is_default,created_by_user_id,updated_by_user_id,realtime_protocol,realtime_model_id)
VALUES($1,'openai',$2,$3,'{}',$4,$5,$6,$6,$7,$8) RETURNING id
`

type CreateAIProviderParams struct {
	Name             string         `json:"name"`
	BaseUrl          sql.NullString `json:"base_url"`
	ModelID          string         `json:"model_id"`
	Enabled          bool           `json:"enabled"`
	IsDefault        bool           `json:"is_default"`
	CreatedByUserID  int32          `json:"created_by_user_id"`
	RealtimeProtocol string         `json:"realtime_protocol"`
	RealtimeModelID  string         `json:"realtime_model_id"`
}

func (q *Queries) CreateAIProvider(ctx context.Context, arg CreateAIProviderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAIProvider,
		arg.Name,
		arg.BaseUrl,
		arg.ModelID,
		arg.Enabled,
		arg.IsDefault,
		arg.CreatedByUserID,
		arg.RealtimeProtocol,
		arg.RealtimeModelID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAIProvider = `-- name: DeleteAIProvider :execrows
DELETE FROM ai_providers WHERE id=$1
`

func (q *Queries) DeleteAIProvider(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAIProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAIProviders = `-- name: ListAIProviders :many
SELECT to_jsonb(result) FROM (
 SELECT id::text,name,provider_type AS "providerType",base_url AS "baseUrl",model_id AS "modelId",realtime_protocol AS "realtimeProtocol",realtime_model_id AS "realtimeModelId",enabled,is_default AS "isDefault",status,health_json AS health,last_tested_at AS "lastTestedAt",updated_at AS "updatedAt"
 FROM ai_providers ORDER BY name
) result
`

func (q *Queries) ListAIProviders(ctx context.Context) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAIProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAIProvider = `-- name: LockAIProvider :one
SELECT id,base_url,model_id,credential_envelope_json,enabled FROM ai_providers WHERE id=$1 FOR UPDATE
`

type LockAIProviderRow struct {
	ID                     int64           `json:"id"`
	BaseUrl                sql.NullString  `json:"base_url"`
	ModelID                string          `json:"model_id"`
	CredentialEnvelopeJson json.RawMessage `json:"credential_envelope_json"`
	Enabled                bool            `json:"enabled"`
}

func (q *Queries) LockAIProvider(ctx context.Context, id int64) (LockAIProviderRow, error) {
	row := q.db.QueryRowContext(ctx, lockAIProvider, id)
	var i LockAIProviderRow
	err := row.Scan(
		&i.ID,
		&i.BaseUrl,
		&i.ModelID,
		&i.CredentialEnvelopeJson,
		&i.Enabled,
	)
	return i, err
}

const lockAIProviderRegistry = `-- name: LockAIProviderRegistry :exec
SELECT pg_advisory_xact_lock(hashtext('aerosight.ai-provider.registry'))
`

func (q *Queries) LockAIProviderRegistry(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lockAIProviderRegistry)
	return err
}

const lockPlatformUserRole = `-- name: LockPlatformUserRole :one
SELECT role FROM users WHERE id=$1 FOR SHARE
`

func (q *Queries) LockPlatformUserRole(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, lockPlatformUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const readAIProviderPublic = `-- name: ReadAIProviderPublic :one
SELECT to_jsonb(result) FROM (
 SELECT id::text,name,provider_type AS "providerType",base_url AS "baseUrl",model_id AS "modelId",realtime_protocol AS "realtimeProtocol",realtime_model_id AS "realtimeModelId",enabled,is_default AS "isDefault",status,health_json AS health,last_tested_at AS "lastTestedAt",updated_at AS "updatedAt"
 FROM ai_providers WHERE id=$1
) result
`

func (q *Queries) ReadAIProviderPublic(ctx context.Context, id int64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, readAIProviderPublic, id)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const readDefaultChatProvider = `-- name: ReadDefaultChatProvider :many
SELECT id,provider_type,base_url,model_id,realtime_protocol,realtime_model_id,credential_envelope_json FROM ai_providers WHERE enabled AND is_default LIMIT 2
`

type ReadDefaultChatProviderRow struct {
	ID                     int64           `json:"id"`
	ProviderType           string          `json:"provider_type"`
	BaseUrl                sql.NullString  `json:"base_url"`
	ModelID                string          `json:"model_id"`
	RealtimeProtocol       string          `json:"realtime_protocol"`
	RealtimeModelID        string          `json:"realtime_model_id"`
	CredentialEnvelopeJson json.RawMessage `json:"credential_envelope_json"`
}

func (q *Queries) ReadDefaultChatProvider(ctx context.Context) ([]ReadDefaultChatProviderRow, error) {
	rows, err := q.db.QueryContext(ctx, readDefaultChatProvider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadDefaultChatProviderRow{}
	for rows.Next() {
		var i ReadDefaultChatProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderType,
			&i.BaseUrl,
			&i.ModelID,
			&i.RealtimeProtocol,
			&i.RealtimeModelID,
			&i.CredentialEnvelopeJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAIProviderCredential = `-- name: SetAIProviderCredential :exec
UPDATE ai_providers SET credential_envelope_json=$2,status='untested' WHERE id=$1
`

type SetAIProviderCredentialParams struct {
	ID                     int64           `json:"id"`
	CredentialEnvelopeJson json.RawMessage `json:"credential_envelope_json"`
}

func (q *Queries) SetAIProviderCredential(ctx context.Context, arg SetAIProviderCredentialParams) error {
	_, err := q.db.ExecContext(ctx, setAIProviderCredential, arg.ID, arg.CredentialEnvelopeJson)
	return err
}

const setAIProviderHealth = `-- name: SetAIProviderHealth :exec
UPDATE ai_providers SET status=$2,health_json=$3,last_tested_at=now(),updated_by_user_id=$4,updated_at=now() WHERE id=$1
`

type SetAIProviderHealthParams struct {
	ID              int64           `json:"id"`
	Status          string          `json:"status"`
	HealthJson      json.RawMessage `json:"health_json"`
	UpdatedByUserID int32           `json:"updated_by_user_id"`
}

func (q *Queries) SetAIProviderHealth(ctx context.Context, arg SetAIProviderHealthParams) error {
	_, err := q.db.ExecContext(ctx, setAIProviderHealth,
		arg.ID,
		arg.Status,
		arg.HealthJson,
		arg.UpdatedByUserID,
	)
	return err
}

const updateAIProvider = `-- name: UpdateAIProvider :exec
UPDATE ai_providers SET name=$2,provider_type='openai',base_url=$3,model_id=$4,enabled=$5,is_default=$6,updated_by_user_id=$7,realtime_protocol=$8,realtime_model_id=$9,updated_at=now() WHERE id=$1
`

type UpdateAIProviderParams struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	BaseUrl          sql.NullString `json:"base_url"`
	ModelID          string         `json:"model_id"`
	Enabled          bool           `json:"enabled"`
	IsDefault        bool           `json:"is_default"`
	UpdatedByUserID  int32          `json:"updated_by_user_id"`
	RealtimeProtocol string         `json:"realtime_protocol"`
	RealtimeModelID  string         `json:"realtime_model_id"`
}

func (q *Queries) UpdateAIProvider(ctx context.Context, arg UpdateAIProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateAIProvider,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ModelID,
		arg.Enabled,
		arg.IsDefault,
		arg.UpdatedByUserID,
		arg.RealtimeProtocol,
		arg.RealtimeModelID,
	)
	return err
}
