// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: algorithm_definitions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createAlgorithmDefinition = `-- name: CreateAlgorithmDefinition :one
INSERT INTO algorithm_definitions(project_id,team_id,provider_id,name,capability_code,description,created_by_user_id)
VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id
`

type CreateAlgorithmDefinitionParams struct {
	ProjectID       int32          `json:"project_id"`
	TeamID          int32          `json:"team_id"`
	ProviderID      int64          `json:"provider_id"`
	Name            string         `json:"name"`
	CapabilityCode  string         `json:"capability_code"`
	Description     sql.NullString `json:"description"`
	CreatedByUserID sql.NullInt32  `json:"created_by_user_id"`
}

func (q *Queries) CreateAlgorithmDefinition(ctx context.Context, arg CreateAlgorithmDefinitionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAlgorithmDefinition,
		arg.ProjectID,
		arg.TeamID,
		arg.ProviderID,
		arg.Name,
		arg.CapabilityCode,
		arg.Description,
		arg.CreatedByUserID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAlgorithmConfiguration = `-- name: InsertAlgorithmConfiguration :one
INSERT INTO algorithm_definition_versions(project_id,team_id,algorithm_definition_id,version,status,execution_mode,model_or_process,
 input_requirements_json,parameters_schema_json,protocol_config_json,output_mapping_json,label_mapping_json,output_schema_json,display_metadata_json,publish_threshold,created_by_user_id,published_by_user_id,published_at)
VALUES($1,$2,$3,$4,'published',$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$15,now()) RETURNING id
`

type InsertAlgorithmConfigurationParams struct {
	ProjectID             int32           `json:"project_id"`
	TeamID                int32           `json:"team_id"`
	AlgorithmDefinitionID int64           `json:"algorithm_definition_id"`
	Version               int32           `json:"version"`
	ExecutionMode         string          `json:"execution_mode"`
	ModelOrProcess        string          `json:"model_or_process"`
	InputRequirementsJson json.RawMessage `json:"input_requirements_json"`
	ParametersSchemaJson  json.RawMessage `json:"parameters_schema_json"`
	ProtocolConfigJson    json.RawMessage `json:"protocol_config_json"`
	OutputMappingJson     json.RawMessage `json:"output_mapping_json"`
	LabelMappingJson      json.RawMessage `json:"label_mapping_json"`
	OutputSchemaJson      json.RawMessage `json:"output_schema_json"`
	DisplayMetadataJson   json.RawMessage `json:"display_metadata_json"`
	PublishThreshold      float64         `json:"publish_threshold"`
	ActorUserID           sql.NullInt32   `json:"actor_user_id"`
}

func (q *Queries) InsertAlgorithmConfiguration(ctx context.Context, arg InsertAlgorithmConfigurationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAlgorithmConfiguration,
		arg.ProjectID,
		arg.TeamID,
		arg.AlgorithmDefinitionID,
		arg.Version,
		arg.ExecutionMode,
		arg.ModelOrProcess,
		arg.InputRequirementsJson,
		arg.ParametersSchemaJson,
		arg.ProtocolConfigJson,
		arg.OutputMappingJson,
		arg.LabelMappingJson,
		arg.OutputSchemaJson,
		arg.DisplayMetadataJson,
		arg.PublishThreshold,
		arg.ActorUserID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAlgorithmCatalog = `-- name: ListAlgorithmCatalog :many
SELECT jsonb_build_object('id',definition.id::text,'configurationSnapshotId',version.id::text,'name',definition.name,'description',definition.description,
 'capabilityCode',definition.capability_code,'execution',jsonb_build_object('mode',version.execution_mode,'modelOrProcess',version.model_or_process),
 'provider',jsonb_build_object('type',provider.provider_type,'available',provider.status='active'),
 'schemas',jsonb_build_object('input',version.input_requirements_json,'parameters',version.parameters_schema_json,'output',version.output_schema_json),'display',version.display_metadata_json)
FROM algorithm_definitions definition
JOIN algorithm_definition_versions version ON version.id=definition.current_published_version_id AND version.project_id=definition.project_id
JOIN algorithm_providers provider ON provider.id=definition.provider_id AND provider.project_id=definition.project_id
WHERE definition.project_id=$1 AND version.status='published' ORDER BY definition.name
`

func (q *Queries) ListAlgorithmCatalog(ctx context.Context, projectID int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAlgorithmCatalog, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var jsonb_build_object json.RawMessage
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAlgorithmDefinition = `-- name: LockAlgorithmDefinition :one
SELECT id FROM algorithm_definitions WHERE project_id=$1 AND id=$2 FOR UPDATE
`

type LockAlgorithmDefinitionParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) LockAlgorithmDefinition(ctx context.Context, arg LockAlgorithmDefinitionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockAlgorithmDefinition, arg.ProjectID, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockAlgorithmDefinitionProvider = `-- name: LockAlgorithmDefinitionProvider :one
SELECT team_id FROM algorithm_providers WHERE project_id=$1 AND id=$2 FOR SHARE
`

type LockAlgorithmDefinitionProviderParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) LockAlgorithmDefinitionProvider(ctx context.Context, arg LockAlgorithmDefinitionProviderParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockAlgorithmDefinitionProvider, arg.ProjectID, arg.ID)
	var team_id int32
	err := row.Scan(&team_id)
	return team_id, err
}

const nextAlgorithmConfigurationVersion = `-- name: NextAlgorithmConfigurationVersion :one
SELECT (coalesce(max(version),0)+1)::int FROM algorithm_definition_versions WHERE project_id=$1 AND algorithm_definition_id=$2
`

type NextAlgorithmConfigurationVersionParams struct {
	ProjectID             int32 `json:"project_id"`
	AlgorithmDefinitionID int64 `json:"algorithm_definition_id"`
}

func (q *Queries) NextAlgorithmConfigurationVersion(ctx context.Context, arg NextAlgorithmConfigurationVersionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextAlgorithmConfigurationVersion, arg.ProjectID, arg.AlgorithmDefinitionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const retireAlgorithmConfigurations = `-- name: RetireAlgorithmConfigurations :exec
UPDATE algorithm_definition_versions SET status='retired' WHERE project_id=$1 AND algorithm_definition_id=$2 AND status='published'
`

type RetireAlgorithmConfigurationsParams struct {
	ProjectID             int32 `json:"project_id"`
	AlgorithmDefinitionID int64 `json:"algorithm_definition_id"`
}

func (q *Queries) RetireAlgorithmConfigurations(ctx context.Context, arg RetireAlgorithmConfigurationsParams) error {
	_, err := q.db.ExecContext(ctx, retireAlgorithmConfigurations, arg.ProjectID, arg.AlgorithmDefinitionID)
	return err
}

const setAlgorithmCurrentConfiguration = `-- name: SetAlgorithmCurrentConfiguration :exec
UPDATE algorithm_definitions SET current_published_version_id=$3,updated_at=now() WHERE project_id=$1 AND id=$2
`

type SetAlgorithmCurrentConfigurationParams struct {
	ProjectID                 int32         `json:"project_id"`
	ID                        int64         `json:"id"`
	CurrentPublishedVersionID sql.NullInt64 `json:"current_published_version_id"`
}

func (q *Queries) SetAlgorithmCurrentConfiguration(ctx context.Context, arg SetAlgorithmCurrentConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, setAlgorithmCurrentConfiguration, arg.ProjectID, arg.ID, arg.CurrentPublishedVersionID)
	return err
}

const updateAlgorithmDefinition = `-- name: UpdateAlgorithmDefinition :exec
UPDATE algorithm_definitions SET provider_id=$3,name=$4,capability_code=$5,description=$6,updated_at=now() WHERE project_id=$1 AND id=$2
`

type UpdateAlgorithmDefinitionParams struct {
	ProjectID      int32          `json:"project_id"`
	ID             int64          `json:"id"`
	ProviderID     int64          `json:"provider_id"`
	Name           string         `json:"name"`
	CapabilityCode string         `json:"capability_code"`
	Description    sql.NullString `json:"description"`
}

func (q *Queries) UpdateAlgorithmDefinition(ctx context.Context, arg UpdateAlgorithmDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, updateAlgorithmDefinition,
		arg.ProjectID,
		arg.ID,
		arg.ProviderID,
		arg.Name,
		arg.CapabilityCode,
		arg.Description,
	)
	return err
}
