// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: algorithm_providers.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const createAlgorithmProvider = `-- name: CreateAlgorithmProvider :one
INSERT INTO algorithm_providers(project_id,team_id,name,provider_type,base_url,auth_type,allowed_headers_json,timeout_seconds,concurrency_limit,rate_limit_per_minute,created_by_user_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id
`

type CreateAlgorithmProviderParams struct {
	ProjectID          int32           `json:"project_id"`
	TeamID             int32           `json:"team_id"`
	Name               string          `json:"name"`
	ProviderType       string          `json:"provider_type"`
	BaseUrl            string          `json:"base_url"`
	AuthType           string          `json:"auth_type"`
	AllowedHeadersJson json.RawMessage `json:"allowed_headers_json"`
	TimeoutSeconds     int32           `json:"timeout_seconds"`
	ConcurrencyLimit   int32           `json:"concurrency_limit"`
	RateLimitPerMinute int32           `json:"rate_limit_per_minute"`
	CreatedByUserID    sql.NullInt32   `json:"created_by_user_id"`
}

func (q *Queries) CreateAlgorithmProvider(ctx context.Context, arg CreateAlgorithmProviderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAlgorithmProvider,
		arg.ProjectID,
		arg.TeamID,
		arg.Name,
		arg.ProviderType,
		arg.BaseUrl,
		arg.AuthType,
		arg.AllowedHeadersJson,
		arg.TimeoutSeconds,
		arg.ConcurrencyLimit,
		arg.RateLimitPerMinute,
		arg.CreatedByUserID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAlgorithmProviders = `-- name: ListAlgorithmProviders :many
SELECT to_jsonb(result) FROM (
 SELECT id::text,project_id AS "projectId",name,provider_type AS "providerType",base_url AS "baseUrl",auth_type AS "authType",
 allowed_headers_json AS "allowedHeaders",timeout_seconds AS "timeoutSeconds",concurrency_limit AS "concurrencyLimit",rate_limit_per_minute AS "rateLimitPerMinute",status,health_json AS health,updated_at AS "updatedAt"
 FROM algorithm_providers WHERE project_id=$1 ORDER BY name
) result
`

func (q *Queries) ListAlgorithmProviders(ctx context.Context, projectID int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAlgorithmProviders, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAlgorithmProviderCredential = `-- name: LockAlgorithmProviderCredential :one
SELECT auth_type,(credential_envelope_json IS NOT NULL)::boolean AS has_credential FROM algorithm_providers WHERE project_id=$1 AND id=$2 FOR UPDATE
`

type LockAlgorithmProviderCredentialParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

type LockAlgorithmProviderCredentialRow struct {
	AuthType      string `json:"auth_type"`
	HasCredential bool   `json:"has_credential"`
}

func (q *Queries) LockAlgorithmProviderCredential(ctx context.Context, arg LockAlgorithmProviderCredentialParams) (LockAlgorithmProviderCredentialRow, error) {
	row := q.db.QueryRowContext(ctx, lockAlgorithmProviderCredential, arg.ProjectID, arg.ID)
	var i LockAlgorithmProviderCredentialRow
	err := row.Scan(&i.AuthType, &i.HasCredential)
	return i, err
}

const readAlgorithmProviderEndpoint = `-- name: ReadAlgorithmProviderEndpoint :one
SELECT base_url,provider_type FROM algorithm_providers WHERE project_id=$1 AND id=$2
`

type ReadAlgorithmProviderEndpointParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

type ReadAlgorithmProviderEndpointRow struct {
	BaseUrl      string `json:"base_url"`
	ProviderType string `json:"provider_type"`
}

func (q *Queries) ReadAlgorithmProviderEndpoint(ctx context.Context, arg ReadAlgorithmProviderEndpointParams) (ReadAlgorithmProviderEndpointRow, error) {
	row := q.db.QueryRowContext(ctx, readAlgorithmProviderEndpoint, arg.ProjectID, arg.ID)
	var i ReadAlgorithmProviderEndpointRow
	err := row.Scan(&i.BaseUrl, &i.ProviderType)
	return i, err
}

const readAlgorithmProviderPublic = `-- name: ReadAlgorithmProviderPublic :one
SELECT to_jsonb(result) FROM (
 SELECT id::text,project_id AS "projectId",name,provider_type AS "providerType",base_url AS "baseUrl",auth_type AS "authType",
 allowed_headers_json AS "allowedHeaders",timeout_seconds AS "timeoutSeconds",concurrency_limit AS "concurrencyLimit",rate_limit_per_minute AS "rateLimitPerMinute",status,health_json AS health,updated_at AS "updatedAt"
 FROM algorithm_providers WHERE project_id=$1 AND id=$2
) result
`

type ReadAlgorithmProviderPublicParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) ReadAlgorithmProviderPublic(ctx context.Context, arg ReadAlgorithmProviderPublicParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, readAlgorithmProviderPublic, arg.ProjectID, arg.ID)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const setAlgorithmProviderCredential = `-- name: SetAlgorithmProviderCredential :exec
UPDATE algorithm_providers SET credential_envelope_json=$3 WHERE project_id=$1 AND id=$2
`

type SetAlgorithmProviderCredentialParams struct {
	ProjectID              int32                 `json:"project_id"`
	ID                     int64                 `json:"id"`
	CredentialEnvelopeJson pqtype.NullRawMessage `json:"credential_envelope_json"`
}

func (q *Queries) SetAlgorithmProviderCredential(ctx context.Context, arg SetAlgorithmProviderCredentialParams) error {
	_, err := q.db.ExecContext(ctx, setAlgorithmProviderCredential, arg.ProjectID, arg.ID, arg.CredentialEnvelopeJson)
	return err
}

const updateAlgorithmProvider = `-- name: UpdateAlgorithmProvider :exec
UPDATE algorithm_providers SET name=$3,provider_type=$4,base_url=$5,auth_type=$6,allowed_headers_json=$7,timeout_seconds=$8,concurrency_limit=$9,rate_limit_per_minute=$10,updated_at=now() WHERE project_id=$1 AND id=$2
`

type UpdateAlgorithmProviderParams struct {
	ProjectID          int32           `json:"project_id"`
	ID                 int64           `json:"id"`
	Name               string          `json:"name"`
	ProviderType       string          `json:"provider_type"`
	BaseUrl            string          `json:"base_url"`
	AuthType           string          `json:"auth_type"`
	AllowedHeadersJson json.RawMessage `json:"allowed_headers_json"`
	TimeoutSeconds     int32           `json:"timeout_seconds"`
	ConcurrencyLimit   int32           `json:"concurrency_limit"`
	RateLimitPerMinute int32           `json:"rate_limit_per_minute"`
}

func (q *Queries) UpdateAlgorithmProvider(ctx context.Context, arg UpdateAlgorithmProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateAlgorithmProvider,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.ProviderType,
		arg.BaseUrl,
		arg.AuthType,
		arg.AllowedHeadersJson,
		arg.TimeoutSeconds,
		arg.ConcurrencyLimit,
		arg.RateLimitPerMinute,
	)
	return err
}
