// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: algorithm_asset_access.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const readAlgorithmAccessAsset = `-- name: ReadAlgorithmAccessAsset :one
SELECT storage_key, mime_type FROM assets
WHERE id=$1 AND project_id=$2 AND version=$3 AND status='available' AND deleted_at IS NULL
`

type ReadAlgorithmAccessAssetParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
	Version   int32 `json:"version"`
}

type ReadAlgorithmAccessAssetRow struct {
	StorageKey string         `json:"storage_key"`
	MimeType   sql.NullString `json:"mime_type"`
}

func (q *Queries) ReadAlgorithmAccessAsset(ctx context.Context, arg ReadAlgorithmAccessAssetParams) (ReadAlgorithmAccessAssetRow, error) {
	row := q.db.QueryRowContext(ctx, readAlgorithmAccessAsset, arg.ID, arg.ProjectID, arg.Version)
	var i ReadAlgorithmAccessAssetRow
	err := row.Scan(&i.StorageKey, &i.MimeType)
	return i, err
}
