// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: algorithm_runs.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const insertCatalogAlgorithmRun = `-- name: InsertCatalogAlgorithmRun :exec
INSERT INTO algorithm_runs(id,project_id,team_id,algorithm_definition_version_id,input_asset_id,task_run_id,device_id,idempotency_key,parameters_json,input_snapshot_json)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertCatalogAlgorithmRunParams struct {
	ID                           uuid.UUID       `json:"id"`
	ProjectID                    int32           `json:"project_id"`
	TeamID                       int32           `json:"team_id"`
	AlgorithmDefinitionVersionID int64           `json:"algorithm_definition_version_id"`
	InputAssetID                 int32           `json:"input_asset_id"`
	TaskRunID                    sql.NullInt32   `json:"task_run_id"`
	DeviceID                     sql.NullInt32   `json:"device_id"`
	IdempotencyKey               string          `json:"idempotency_key"`
	Parameters                   json.RawMessage `json:"parameters"`
	Snapshot                     json.RawMessage `json:"snapshot"`
}

func (q *Queries) InsertCatalogAlgorithmRun(ctx context.Context, arg InsertCatalogAlgorithmRunParams) error {
	_, err := q.db.ExecContext(ctx, insertCatalogAlgorithmRun,
		arg.ID,
		arg.ProjectID,
		arg.TeamID,
		arg.AlgorithmDefinitionVersionID,
		arg.InputAssetID,
		arg.TaskRunID,
		arg.DeviceID,
		arg.IdempotencyKey,
		arg.Parameters,
		arg.Snapshot,
	)
	return err
}

const listAlgorithmRuns = `-- name: ListAlgorithmRuns :many
SELECT to_jsonb(result) FROM (
 SELECT run.id,run.status,run.input_asset_id AS "inputAssetId",run.task_run_id AS "taskRunId",run.device_id AS "deviceId",
 run.canonical_result_json AS "canonicalResult",run.external_job_id AS "externalJobId",run.raw_result_object_key AS "rawResultObjectKey",
 run.raw_result_checksum_sha256 AS "rawResultChecksumSha256",run.error_code AS "errorCode",run.error_message AS "errorMessage",
 run.created_at AS "createdAt",run.started_at AS "startedAt",run.finished_at AS "finishedAt",definition.name AS "definitionName",
 provider.name AS "providerName",provider.provider_type AS "providerType"
 FROM algorithm_runs run
 JOIN algorithm_definition_versions version ON version.id=run.algorithm_definition_version_id AND version.project_id=run.project_id
 JOIN algorithm_definitions definition ON definition.id=version.algorithm_definition_id AND definition.project_id=run.project_id
 JOIN algorithm_providers provider ON provider.id=definition.provider_id
 WHERE run.project_id=$1 ORDER BY run.created_at DESC LIMIT 100
) result
`

func (q *Queries) ListAlgorithmRuns(ctx context.Context, projectID int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAlgorithmRuns, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAlgorithmRetrySource = `-- name: LockAlgorithmRetrySource :one
SELECT team_id,algorithm_definition_version_id,input_asset_id,task_run_id,device_id,parameters_json,input_snapshot_json,status
FROM algorithm_runs WHERE project_id=$1 AND id=$2 FOR UPDATE
`

type LockAlgorithmRetrySourceParams struct {
	ProjectID int32     `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

type LockAlgorithmRetrySourceRow struct {
	TeamID                       int32           `json:"team_id"`
	AlgorithmDefinitionVersionID int64           `json:"algorithm_definition_version_id"`
	InputAssetID                 int32           `json:"input_asset_id"`
	TaskRunID                    sql.NullInt32   `json:"task_run_id"`
	DeviceID                     sql.NullInt32   `json:"device_id"`
	ParametersJson               json.RawMessage `json:"parameters_json"`
	InputSnapshotJson            json.RawMessage `json:"input_snapshot_json"`
	Status                       string          `json:"status"`
}

func (q *Queries) LockAlgorithmRetrySource(ctx context.Context, arg LockAlgorithmRetrySourceParams) (LockAlgorithmRetrySourceRow, error) {
	row := q.db.QueryRowContext(ctx, lockAlgorithmRetrySource, arg.ProjectID, arg.ID)
	var i LockAlgorithmRetrySourceRow
	err := row.Scan(
		&i.TeamID,
		&i.AlgorithmDefinitionVersionID,
		&i.InputAssetID,
		&i.TaskRunID,
		&i.DeviceID,
		&i.ParametersJson,
		&i.InputSnapshotJson,
		&i.Status,
	)
	return i, err
}

const readAlgorithmRunAttempts = `-- name: ReadAlgorithmRunAttempts :many
SELECT to_jsonb(result) FROM (
 SELECT attempt,status,response_status AS "responseStatus",duration_ms AS "durationMs",error_category AS "errorCategory",external_job_id AS "externalJobId",started_at AS "startedAt",finished_at AS "finishedAt"
 FROM algorithm_run_attempts WHERE project_id=$1 AND algorithm_run_id=$2 ORDER BY attempt
) result
`

type ReadAlgorithmRunAttemptsParams struct {
	ProjectID      int32     `json:"project_id"`
	AlgorithmRunID uuid.UUID `json:"algorithm_run_id"`
}

func (q *Queries) ReadAlgorithmRunAttempts(ctx context.Context, arg ReadAlgorithmRunAttemptsParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, readAlgorithmRunAttempts, arg.ProjectID, arg.AlgorithmRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readAlgorithmRunDetail = `-- name: ReadAlgorithmRunDetail :one
SELECT to_jsonb(result) FROM (
 SELECT run.id,run.status,run.input_asset_id AS "inputAssetId",run.task_run_id AS "taskRunId",run.device_id AS "deviceId",
 run.input_snapshot_json AS "inputSnapshot",run.canonical_result_json AS "canonicalResult",run.external_job_id AS "externalJobId",run.raw_result_object_key AS "rawResultObjectKey",
 run.raw_result_checksum_sha256 AS "rawResultChecksumSha256",run.error_code AS "errorCode",run.error_message AS "errorMessage",
 run.created_at AS "createdAt",run.started_at AS "startedAt",run.finished_at AS "finishedAt",definition.name AS "definitionName",
 provider.name AS "providerName",provider.provider_type AS "providerType"
 FROM algorithm_runs run
 JOIN algorithm_definition_versions version ON version.id=run.algorithm_definition_version_id AND version.project_id=run.project_id
 JOIN algorithm_definitions definition ON definition.id=version.algorithm_definition_id AND definition.project_id=run.project_id
 JOIN algorithm_providers provider ON provider.id=definition.provider_id
 WHERE run.project_id=$1 AND run.id=$2
) result
`

type ReadAlgorithmRunDetailParams struct {
	ProjectID int32     `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) ReadAlgorithmRunDetail(ctx context.Context, arg ReadAlgorithmRunDetailParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, readAlgorithmRunDetail, arg.ProjectID, arg.ID)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const readAlgorithmRunSource = `-- name: ReadAlgorithmRunSource :one
SELECT definition.team_id,version.id AS configuration_snapshot_id,provider.provider_type,version.model_or_process,
 version.execution_mode,coalesce(version.protocol_config_json->>'mappingVersion','v1')::text AS mapping_version,
 asset.id AS asset_id,asset.version AS asset_version,coalesce(asset.checksum_sha256,asset.checksum,'')::text AS checksum_sha256,
 coalesce(asset.mime_type,'application/octet-stream')::text AS mime_type
FROM algorithm_definition_versions version
JOIN algorithm_definitions definition ON definition.id=version.algorithm_definition_id AND definition.project_id=version.project_id AND definition.current_published_version_id=version.id
JOIN algorithm_providers provider ON provider.id=definition.provider_id AND provider.status='active'
JOIN assets asset ON asset.project_id=version.project_id AND asset.id=$1 AND asset.status='available'
WHERE version.project_id=$2 AND version.id=$3 AND version.status='published'
FOR SHARE OF version,definition,provider,asset
`

type ReadAlgorithmRunSourceParams struct {
	AssetID    int32 `json:"asset_id"`
	ProjectID  int32 `json:"project_id"`
	SnapshotID int64 `json:"snapshot_id"`
}

type ReadAlgorithmRunSourceRow struct {
	TeamID                  int32  `json:"team_id"`
	ConfigurationSnapshotID int64  `json:"configuration_snapshot_id"`
	ProviderType            string `json:"provider_type"`
	ModelOrProcess          string `json:"model_or_process"`
	ExecutionMode           string `json:"execution_mode"`
	MappingVersion          string `json:"mapping_version"`
	AssetID                 int32  `json:"asset_id"`
	AssetVersion            int32  `json:"asset_version"`
	ChecksumSha256          string `json:"checksum_sha256"`
	MimeType                string `json:"mime_type"`
}

func (q *Queries) ReadAlgorithmRunSource(ctx context.Context, arg ReadAlgorithmRunSourceParams) (ReadAlgorithmRunSourceRow, error) {
	row := q.db.QueryRowContext(ctx, readAlgorithmRunSource, arg.AssetID, arg.ProjectID, arg.SnapshotID)
	var i ReadAlgorithmRunSourceRow
	err := row.Scan(
		&i.TeamID,
		&i.ConfigurationSnapshotID,
		&i.ProviderType,
		&i.ModelOrProcess,
		&i.ExecutionMode,
		&i.MappingVersion,
		&i.AssetID,
		&i.AssetVersion,
		&i.ChecksumSha256,
		&i.MimeType,
	)
	return i, err
}
