// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createDefaultAdmin = `-- name: CreateDefaultAdmin :exec
INSERT INTO users (name, email, password, role) VALUES ('admin', 'admin@example.com', $1, 'admin')
`

func (q *Queries) CreateDefaultAdmin(ctx context.Context, password sql.NullString) error {
	_, err := q.db.ExecContext(ctx, createDefaultAdmin, password)
	return err
}

const findLoginUser = `-- name: FindLoginUser :one
SELECT id, name, email, phone, password, role FROM users
WHERE lower(email) = lower($1::text) OR phone = $1::text
LIMIT 1
`

type FindLoginUserRow struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Password sql.NullString `json:"password"`
	Role     string         `json:"role"`
}

func (q *Queries) FindLoginUser(ctx context.Context, username string) (FindLoginUserRow, error) {
	row := q.db.QueryRowContext(ctx, findLoginUser, username)
	var i FindLoginUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Role,
	)
	return i, err
}

const getProjectAccess = `-- name: GetProjectAccess :one
SELECT p.id AS project_id, p.team_id, tm.role,
 coalesce(array_agg(pp.permission) FILTER (WHERE pp.permission IS NOT NULL), '{}'::text[])::text[] AS permissions
FROM projects p
JOIN team_members tm ON tm.team_id = p.team_id AND tm.user_id = $1
LEFT JOIN project_permissions pp ON pp.project_id = p.id AND pp.team_id = p.team_id AND pp.user_id = tm.user_id
WHERE p.id = $2
GROUP BY p.id, p.team_id, tm.role
`

type GetProjectAccessParams struct {
	UserID    int32 `json:"user_id"`
	ProjectID int32 `json:"project_id"`
}

type GetProjectAccessRow struct {
	ProjectID   int32    `json:"project_id"`
	TeamID      int32    `json:"team_id"`
	Role        string   `json:"role"`
	Permissions []string `json:"permissions"`
}

func (q *Queries) GetProjectAccess(ctx context.Context, arg GetProjectAccessParams) (GetProjectAccessRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectAccess, arg.UserID, arg.ProjectID)
	var i GetProjectAccessRow
	err := row.Scan(
		&i.ProjectID,
		&i.TeamID,
		&i.Role,
		pq.Array(&i.Permissions),
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, phone, role FROM users WHERE id = $1
`

type GetUserRow struct {
	ID    int32          `json:"id"`
	Name  string         `json:"name"`
	Email sql.NullString `json:"email"`
	Phone sql.NullString `json:"phone"`
	Role  string         `json:"role"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
	)
	return i, err
}

const hasUsers = `-- name: HasUsers :one
SELECT EXISTS(SELECT 1 FROM users)
`

func (q *Queries) HasUsers(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUsers)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
