// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_adapters.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const insertDeviceAdapter = `-- name: InsertDeviceAdapter :one
WITH inserted AS (
 INSERT INTO device_adapters(project_id,team_id,name,adapter_type,vendor,protocol_version,config_json)
 VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id, project_id, team_id, name, adapter_type, vendor, protocol_version, status, secret_ref, config_json, capabilities_json, last_health_json, last_checked_at, created_at, updated_at, network_profile_id, lease_owner, lease_expires_at, connection_epoch, last_connected_at, connector_definition_id, onboarding_policy, discovery_scope_json, sync_cursor_json, credential_envelope_json, external_scope_key
)
SELECT to_jsonb(r) FROM (
 SELECT id::text AS id,project_id AS "projectId",name,adapter_type AS "adapterType",vendor,
 protocol_version AS "protocolVersion",status,config_json AS config,last_health_json AS "lastHealth",
 last_checked_at AS "lastCheckedAt",updated_at AS "updatedAt" FROM inserted
) r
`

type InsertDeviceAdapterParams struct {
	ProjectID       int32           `json:"project_id"`
	TeamID          int32           `json:"team_id"`
	Name            string          `json:"name"`
	AdapterType     string          `json:"adapter_type"`
	Vendor          sql.NullString  `json:"vendor"`
	ProtocolVersion string          `json:"protocol_version"`
	ConfigJson      json.RawMessage `json:"config_json"`
}

func (q *Queries) InsertDeviceAdapter(ctx context.Context, arg InsertDeviceAdapterParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, insertDeviceAdapter,
		arg.ProjectID,
		arg.TeamID,
		arg.Name,
		arg.AdapterType,
		arg.Vendor,
		arg.ProtocolVersion,
		arg.ConfigJson,
	)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const listDeviceAdapters = `-- name: ListDeviceAdapters :many
SELECT to_jsonb(r) FROM (
 SELECT id::text AS id,project_id AS "projectId",name,adapter_type AS "adapterType",vendor,
 protocol_version AS "protocolVersion",status,config_json AS config,last_health_json AS "lastHealth",
 last_checked_at AS "lastCheckedAt",updated_at AS "updatedAt"
 FROM device_adapters WHERE project_id=$1 ORDER BY name
) r
`

func (q *Queries) ListDeviceAdapters(ctx context.Context, projectID int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceAdapters, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDJIAdapterEnvelope = `-- name: LockDJIAdapterEnvelope :one
SELECT credential_envelope_json FROM device_adapters WHERE project_id=$1 AND id=$2 AND adapter_type='dji' FOR UPDATE
`

type LockDJIAdapterEnvelopeParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) LockDJIAdapterEnvelope(ctx context.Context, arg LockDJIAdapterEnvelopeParams) (pqtype.NullRawMessage, error) {
	row := q.db.QueryRowContext(ctx, lockDJIAdapterEnvelope, arg.ProjectID, arg.ID)
	var credential_envelope_json pqtype.NullRawMessage
	err := row.Scan(&credential_envelope_json)
	return credential_envelope_json, err
}

const setDeviceAdapterEnabled = `-- name: SetDeviceAdapterEnabled :one
UPDATE device_adapters SET status=$3,updated_at=now() WHERE project_id=$1 AND id=$2 RETURNING id::text,status
`

type SetDeviceAdapterEnabledParams struct {
	ProjectID int32  `json:"project_id"`
	ID        int64  `json:"id"`
	Status    string `json:"status"`
}

type SetDeviceAdapterEnabledRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetDeviceAdapterEnabled(ctx context.Context, arg SetDeviceAdapterEnabledParams) (SetDeviceAdapterEnabledRow, error) {
	row := q.db.QueryRowContext(ctx, setDeviceAdapterEnabled, arg.ProjectID, arg.ID, arg.Status)
	var i SetDeviceAdapterEnabledRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const storeDeviceAdapterEnvelope = `-- name: StoreDeviceAdapterEnvelope :exec
UPDATE device_adapters SET credential_envelope_json=$3::jsonb WHERE project_id=$1 AND id=$2
`

type StoreDeviceAdapterEnvelopeParams struct {
	ProjectID int32           `json:"project_id"`
	ID        int64           `json:"id"`
	Envelope  json.RawMessage `json:"envelope"`
}

func (q *Queries) StoreDeviceAdapterEnvelope(ctx context.Context, arg StoreDeviceAdapterEnvelopeParams) error {
	_, err := q.db.ExecContext(ctx, storeDeviceAdapterEnvelope, arg.ProjectID, arg.ID, arg.Envelope)
	return err
}

const updateDJIAdapterEnvelope = `-- name: UpdateDJIAdapterEnvelope :exec
UPDATE device_adapters SET credential_envelope_json=$3::jsonb,status='connecting',updated_at=now() WHERE project_id=$1 AND id=$2
`

type UpdateDJIAdapterEnvelopeParams struct {
	ProjectID int32           `json:"project_id"`
	ID        int64           `json:"id"`
	Envelope  json.RawMessage `json:"envelope"`
}

func (q *Queries) UpdateDJIAdapterEnvelope(ctx context.Context, arg UpdateDJIAdapterEnvelopeParams) error {
	_, err := q.db.ExecContext(ctx, updateDJIAdapterEnvelope, arg.ProjectID, arg.ID, arg.Envelope)
	return err
}
