// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_commands.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const countDeviceCommandConflicts = `-- name: CountDeviceCommandConflicts :one
SELECT count(*)::int AS count FROM task_runs run
WHERE run.project_id=$1 AND run.status IN ('dispatching','running','paused','canceling')
AND (run.selected_device_id=$2 OR run.selected_device_id IN (
SELECT relation.to_device_id FROM device_relationships relation WHERE relation.project_id=$1 AND relation.from_device_id=$2 AND relation.valid_until IS NULL))
`

type CountDeviceCommandConflictsParams struct {
	ProjectID        int32         `json:"project_id"`
	SelectedDeviceID sql.NullInt32 `json:"selected_device_id"`
}

func (q *Queries) CountDeviceCommandConflicts(ctx context.Context, arg CountDeviceCommandConflictsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countDeviceCommandConflicts, arg.ProjectID, arg.SelectedDeviceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const findExistingDeviceCommand = `-- name: FindExistingDeviceCommand :one
SELECT id::text,status FROM device_commands WHERE project_id=$1 AND device_id=$2 AND idempotency_key=$3 FOR UPDATE
`

type FindExistingDeviceCommandParams struct {
	ProjectID      int32  `json:"project_id"`
	DeviceID       int32  `json:"device_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type FindExistingDeviceCommandRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FindExistingDeviceCommand(ctx context.Context, arg FindExistingDeviceCommandParams) (FindExistingDeviceCommandRow, error) {
	row := q.db.QueryRowContext(ctx, findExistingDeviceCommand, arg.ProjectID, arg.DeviceID, arg.IdempotencyKey)
	var i FindExistingDeviceCommandRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const insertDeviceCommand = `-- name: InsertDeviceCommand :one
INSERT INTO device_commands(id,project_id,team_id,device_id,command_key,idempotency_key,capability_code,parameters_json,safety_context_json,status,priority,deadline_at,requested_by_user_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'dispatchable',$10,now()+($11::double precision*interval '1 second'),$12)
ON CONFLICT(device_id,idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING id::text,status
`

type InsertDeviceCommandParams struct {
	ID              uuid.UUID       `json:"id"`
	ProjectID       int32           `json:"project_id"`
	TeamID          int32           `json:"team_id"`
	DeviceID        int32           `json:"device_id"`
	CommandKey      string          `json:"command_key"`
	IdempotencyKey  string          `json:"idempotency_key"`
	CapabilityCode  string          `json:"capability_code"`
	Parameters      json.RawMessage `json:"parameters"`
	Safety          json.RawMessage `json:"safety"`
	Priority        int32           `json:"priority"`
	DeadlineSeconds float64         `json:"deadline_seconds"`
	UserID          sql.NullInt32   `json:"user_id"`
}

type InsertDeviceCommandRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) InsertDeviceCommand(ctx context.Context, arg InsertDeviceCommandParams) (InsertDeviceCommandRow, error) {
	row := q.db.QueryRowContext(ctx, insertDeviceCommand,
		arg.ID,
		arg.ProjectID,
		arg.TeamID,
		arg.DeviceID,
		arg.CommandKey,
		arg.IdempotencyKey,
		arg.CapabilityCode,
		arg.Parameters,
		arg.Safety,
		arg.Priority,
		arg.DeadlineSeconds,
		arg.UserID,
	)
	var i InsertDeviceCommandRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const lockDeviceCommandGrants = `-- name: LockDeviceCommandGrants :many
SELECT action_pattern,effect FROM device_capability_grants
WHERE project_id=$1 AND team_id=$2 AND user_id=$3
AND (expires_at IS NULL OR expires_at>now())
AND (scope_type='project' OR (scope_type='device_type' AND device_type_id=$4) OR (scope_type='device' AND device_id=$5)) FOR SHARE
`

type LockDeviceCommandGrantsParams struct {
	ProjectID    int32         `json:"project_id"`
	TeamID       int32         `json:"team_id"`
	UserID       int32         `json:"user_id"`
	DeviceTypeID sql.NullInt64 `json:"device_type_id"`
	DeviceID     sql.NullInt32 `json:"device_id"`
}

type LockDeviceCommandGrantsRow struct {
	ActionPattern string `json:"action_pattern"`
	Effect        string `json:"effect"`
}

func (q *Queries) LockDeviceCommandGrants(ctx context.Context, arg LockDeviceCommandGrantsParams) ([]LockDeviceCommandGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, lockDeviceCommandGrants,
		arg.ProjectID,
		arg.TeamID,
		arg.UserID,
		arg.DeviceTypeID,
		arg.DeviceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockDeviceCommandGrantsRow{}
	for rows.Next() {
		var i LockDeviceCommandGrantsRow
		if err := rows.Scan(&i.ActionPattern, &i.Effect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeviceCommandTarget = `-- name: LockDeviceCommandTarget :one
SELECT device.project_id,device.device_type_id,device_type.type_key,device.status,capability.availability,capability.risk_level
FROM devices device JOIN device_types device_type ON device_type.id=device.device_type_id JOIN device_capabilities capability ON capability.device_id=device.id AND capability.project_id=device.project_id
WHERE device.project_id=$1 AND device.id=$2 AND capability.capability_code=$3 FOR UPDATE OF device,capability
`

type LockDeviceCommandTargetParams struct {
	ProjectID      int32  `json:"project_id"`
	ID             int32  `json:"id"`
	CapabilityCode string `json:"capability_code"`
}

type LockDeviceCommandTargetRow struct {
	ProjectID    int32  `json:"project_id"`
	DeviceTypeID int64  `json:"device_type_id"`
	TypeKey      string `json:"type_key"`
	Status       string `json:"status"`
	Availability string `json:"availability"`
	RiskLevel    string `json:"risk_level"`
}

func (q *Queries) LockDeviceCommandTarget(ctx context.Context, arg LockDeviceCommandTargetParams) (LockDeviceCommandTargetRow, error) {
	row := q.db.QueryRowContext(ctx, lockDeviceCommandTarget, arg.ProjectID, arg.ID, arg.CapabilityCode)
	var i LockDeviceCommandTargetRow
	err := row.Scan(
		&i.ProjectID,
		&i.DeviceTypeID,
		&i.TypeKey,
		&i.Status,
		&i.Availability,
		&i.RiskLevel,
	)
	return i, err
}
