// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_type_presentation.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const listDeviceTypePresentation = `-- name: ListDeviceTypePresentation :many
SELECT to_jsonb(r) FROM (
  SELECT id::text, type_key AS "typeKey", version, display_name AS "displayName", icon, status
  FROM device_types ORDER BY display_name, version DESC, id
) r
`

func (q *Queries) ListDeviceTypePresentation(ctx context.Context) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceTypePresentation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceTypeIcon = `-- name: UpdateDeviceTypeIcon :one
UPDATE device_types SET icon = $1, updated_at = now()
WHERE id = $2
RETURNING id::text
`

type UpdateDeviceTypeIconParams struct {
	Icon string `json:"icon"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateDeviceTypeIcon(ctx context.Context, arg UpdateDeviceTypeIconParams) (string, error) {
	row := q.db.QueryRowContext(ctx, updateDeviceTypeIcon, arg.Icon, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}
