// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_network.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const getAdapterNetworkProfile = `-- name: GetAdapterNetworkProfile :one
SELECT a.adapter_type,a.network_profile_id,p.mode,p.mqtt_endpoint,p.api_public_base_url,p.websocket_public_url,
 p.media_ingest_base_url,p.media_playback_base_url,p.tls_required,p.config_json,
 (a.credential_envelope_json IS NOT NULL)::boolean AS has_credential
FROM device_adapters a LEFT JOIN device_network_profiles p ON p.id=a.network_profile_id AND p.project_id=a.project_id
WHERE a.project_id=$1 AND a.id=$2
`

type GetAdapterNetworkProfileParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

type GetAdapterNetworkProfileRow struct {
	AdapterType          string                `json:"adapter_type"`
	NetworkProfileID     sql.NullInt64         `json:"network_profile_id"`
	Mode                 sql.NullString        `json:"mode"`
	MqttEndpoint         sql.NullString        `json:"mqtt_endpoint"`
	ApiPublicBaseUrl     sql.NullString        `json:"api_public_base_url"`
	WebsocketPublicUrl   sql.NullString        `json:"websocket_public_url"`
	MediaIngestBaseUrl   sql.NullString        `json:"media_ingest_base_url"`
	MediaPlaybackBaseUrl sql.NullString        `json:"media_playback_base_url"`
	TlsRequired          sql.NullBool          `json:"tls_required"`
	ConfigJson           pqtype.NullRawMessage `json:"config_json"`
	HasCredential        bool                  `json:"has_credential"`
}

func (q *Queries) GetAdapterNetworkProfile(ctx context.Context, arg GetAdapterNetworkProfileParams) (GetAdapterNetworkProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getAdapterNetworkProfile, arg.ProjectID, arg.ID)
	var i GetAdapterNetworkProfileRow
	err := row.Scan(
		&i.AdapterType,
		&i.NetworkProfileID,
		&i.Mode,
		&i.MqttEndpoint,
		&i.ApiPublicBaseUrl,
		&i.WebsocketPublicUrl,
		&i.MediaIngestBaseUrl,
		&i.MediaPlaybackBaseUrl,
		&i.TlsRequired,
		&i.ConfigJson,
		&i.HasCredential,
	)
	return i, err
}

const insertDJINetworkProfile = `-- name: InsertDJINetworkProfile :one
INSERT INTO device_network_profiles(project_id,team_id,name,mode,mqtt_endpoint,api_public_base_url,websocket_public_url,
 media_ingest_base_url,media_playback_base_url,tls_required,status,config_json,last_validation_json)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'unverified',$11,'{"status":"unverified","policyIssues":[]}') RETURNING id
`

type InsertDJINetworkProfileParams struct {
	ProjectID            int32           `json:"project_id"`
	TeamID               int32           `json:"team_id"`
	Name                 string          `json:"name"`
	Mode                 string          `json:"mode"`
	MqttEndpoint         sql.NullString  `json:"mqtt_endpoint"`
	ApiPublicBaseUrl     sql.NullString  `json:"api_public_base_url"`
	WebsocketPublicUrl   sql.NullString  `json:"websocket_public_url"`
	MediaIngestBaseUrl   sql.NullString  `json:"media_ingest_base_url"`
	MediaPlaybackBaseUrl sql.NullString  `json:"media_playback_base_url"`
	TlsRequired          bool            `json:"tls_required"`
	ConfigJson           json.RawMessage `json:"config_json"`
}

func (q *Queries) InsertDJINetworkProfile(ctx context.Context, arg InsertDJINetworkProfileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDJINetworkProfile,
		arg.ProjectID,
		arg.TeamID,
		arg.Name,
		arg.Mode,
		arg.MqttEndpoint,
		arg.ApiPublicBaseUrl,
		arg.WebsocketPublicUrl,
		arg.MediaIngestBaseUrl,
		arg.MediaPlaybackBaseUrl,
		arg.TlsRequired,
		arg.ConfigJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDJISetupAdapter = `-- name: InsertDJISetupAdapter :one
WITH inserted AS (
 INSERT INTO device_adapters(project_id,team_id,name,adapter_type,vendor,protocol_version,status,config_json,network_profile_id)
 VALUES($1,$2,$3,'dji','dji','cloud-api-mqtt5','connecting',$4,$5) RETURNING id, project_id, team_id, name, adapter_type, vendor, protocol_version, status, secret_ref, config_json, capabilities_json, last_health_json, last_checked_at, created_at, updated_at, lease_owner, lease_expires_at, connection_epoch, last_connected_at, network_profile_id, connector_definition_id, onboarding_policy, discovery_scope_json, sync_cursor_json, credential_envelope_json, external_scope_key
)
SELECT to_jsonb(r) FROM (
 SELECT id::text AS id,project_id AS "projectId",name,adapter_type AS "adapterType",vendor,
 protocol_version AS "protocolVersion",status,config_json AS config,last_health_json AS "lastHealth",
 last_checked_at AS "lastCheckedAt",updated_at AS "updatedAt" FROM inserted
) r
`

type InsertDJISetupAdapterParams struct {
	ProjectID        int32           `json:"project_id"`
	TeamID           int32           `json:"team_id"`
	Name             string          `json:"name"`
	ConfigJson       json.RawMessage `json:"config_json"`
	NetworkProfileID sql.NullInt64   `json:"network_profile_id"`
}

func (q *Queries) InsertDJISetupAdapter(ctx context.Context, arg InsertDJISetupAdapterParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, insertDJISetupAdapter,
		arg.ProjectID,
		arg.TeamID,
		arg.Name,
		arg.ConfigJson,
		arg.NetworkProfileID,
	)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const recordAdapterHealth = `-- name: RecordAdapterHealth :exec
UPDATE device_adapters SET last_health_json=$3,last_checked_at=now(),updated_at=now()
WHERE project_id=$1 AND id=$2
`

type RecordAdapterHealthParams struct {
	ProjectID      int32           `json:"project_id"`
	ID             int64           `json:"id"`
	LastHealthJson json.RawMessage `json:"last_health_json"`
}

func (q *Queries) RecordAdapterHealth(ctx context.Context, arg RecordAdapterHealthParams) error {
	_, err := q.db.ExecContext(ctx, recordAdapterHealth, arg.ProjectID, arg.ID, arg.LastHealthJson)
	return err
}

const recordNetworkValidation = `-- name: RecordNetworkValidation :exec
UPDATE device_network_profiles SET status=$3,last_validation_json=$4,last_validated_at=now(),updated_at=now()
WHERE project_id=$1 AND id=$2
`

type RecordNetworkValidationParams struct {
	ProjectID          int32           `json:"project_id"`
	ID                 int64           `json:"id"`
	Status             string          `json:"status"`
	LastValidationJson json.RawMessage `json:"last_validation_json"`
}

func (q *Queries) RecordNetworkValidation(ctx context.Context, arg RecordNetworkValidationParams) error {
	_, err := q.db.ExecContext(ctx, recordNetworkValidation,
		arg.ProjectID,
		arg.ID,
		arg.Status,
		arg.LastValidationJson,
	)
	return err
}
