// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_binding.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const bindDiscoveredDevice = `-- name: BindDiscoveredDevice :exec
UPDATE device_external_identities SET device_id=$3,bound_at=now() WHERE project_id=$1 AND id=$2
`

type BindDiscoveredDeviceParams struct {
	ProjectID int32         `json:"project_id"`
	ID        int64         `json:"id"`
	DeviceID  sql.NullInt32 `json:"device_id"`
}

func (q *Queries) BindDiscoveredDevice(ctx context.Context, arg BindDiscoveredDeviceParams) error {
	_, err := q.db.ExecContext(ctx, bindDiscoveredDevice, arg.ProjectID, arg.ID, arg.DeviceID)
	return err
}

const declareDiscoveredCapability = `-- name: DeclareDiscoveredCapability :exec
INSERT INTO device_capabilities(device_id,project_id,capability_code,declared_by_adapter_id)
VALUES($1,$2,$3,$4) ON CONFLICT(device_id,capability_code) DO UPDATE
SET version_number=device_capabilities.version_number+1,declared_by_adapter_id=excluded.declared_by_adapter_id,updated_at=now()
`

type DeclareDiscoveredCapabilityParams struct {
	DeviceID            int32         `json:"device_id"`
	ProjectID           int32         `json:"project_id"`
	CapabilityCode      string        `json:"capability_code"`
	DeclaredByAdapterID sql.NullInt64 `json:"declared_by_adapter_id"`
}

func (q *Queries) DeclareDiscoveredCapability(ctx context.Context, arg DeclareDiscoveredCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, declareDiscoveredCapability,
		arg.DeviceID,
		arg.ProjectID,
		arg.CapabilityCode,
		arg.DeclaredByAdapterID,
	)
	return err
}

const insertDiscoveredDevice = `-- name: InsertDiscoveredDevice :one
WITH selected_type AS (
 SELECT id FROM device_types WHERE status='active' AND type_key IN ($6::text,'legacy.device')
 ORDER BY CASE WHEN type_key=$6::text THEN 0 ELSE 1 END,version DESC LIMIT 1
)
INSERT INTO devices(project_id,adapter_id,device_type_id,name,type,status,metadata_json)
SELECT $1,$2,selected_type.id,$3,$4,'unknown',
 jsonb_build_object('identityId',$5::bigint,'requestedDeviceTypeKey',$6::text)
FROM selected_type RETURNING id
`

type InsertDiscoveredDeviceParams struct {
	ProjectID  int32         `json:"project_id"`
	AdapterID  sql.NullInt64 `json:"adapter_id"`
	Name       string        `json:"name"`
	DeviceType string        `json:"device_type"`
	IdentityID int64         `json:"identity_id"`
	TypeKey    string        `json:"type_key"`
}

func (q *Queries) InsertDiscoveredDevice(ctx context.Context, arg InsertDiscoveredDeviceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertDiscoveredDevice,
		arg.ProjectID,
		arg.AdapterID,
		arg.Name,
		arg.DeviceType,
		arg.IdentityID,
		arg.TypeKey,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const lockDiscoveredDevice = `-- name: LockDiscoveredDevice :one
SELECT id,adapter_id,device_id,identity_json FROM device_external_identities
WHERE project_id=$1 AND id=$2 FOR UPDATE
`

type LockDiscoveredDeviceParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

type LockDiscoveredDeviceRow struct {
	ID           int64           `json:"id"`
	AdapterID    int64           `json:"adapter_id"`
	DeviceID     sql.NullInt32   `json:"device_id"`
	IdentityJson json.RawMessage `json:"identity_json"`
}

func (q *Queries) LockDiscoveredDevice(ctx context.Context, arg LockDiscoveredDeviceParams) (LockDiscoveredDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, lockDiscoveredDevice, arg.ProjectID, arg.ID)
	var i LockDiscoveredDeviceRow
	err := row.Scan(
		&i.ID,
		&i.AdapterID,
		&i.DeviceID,
		&i.IdentityJson,
	)
	return i, err
}
