// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_type_presentation.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const listDeviceCatalogDrivers = `-- name: ListDeviceCatalogDrivers :many
SELECT to_jsonb(r) FROM (
 SELECT id::text, driver_key AS "driverKey", version, display_name AS "displayName", status, manifest_json AS manifest
 FROM driver_definitions ORDER BY driver_key,version,id
) r
`

func (q *Queries) ListDeviceCatalogDrivers(ctx context.Context) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceCatalogDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTypePresentation = `-- name: ListDeviceTypePresentation :many
SELECT to_jsonb(r) FROM (
  SELECT t.id::text, t.type_key AS "typeKey", t.version, t.display_name AS "displayName", t.icon, t.status,
    t.category, t.vendor, t.model, d.driver_key AS "driverKey", d.version AS "driverVersion",
    t.driver_version_constraint AS "driverVersionConstraint", t.capability_profile_json AS "capabilityProfile"
  FROM device_types t JOIN driver_definitions d ON d.id=t.driver_definition_id
  ORDER BY t.display_name, t.version DESC, t.id
) r
`

func (q *Queries) ListDeviceTypePresentation(ctx context.Context) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceTypePresentation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceTypeIcon = `-- name: UpdateDeviceTypeIcon :one
UPDATE device_types SET icon = $1, updated_at = now()
WHERE id = $2
RETURNING id::text
`

type UpdateDeviceTypeIconParams struct {
	Icon string `json:"icon"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateDeviceTypeIcon(ctx context.Context, arg UpdateDeviceTypeIconParams) (string, error) {
	row := q.db.QueryRowContext(ctx, updateDeviceTypeIcon, arg.Icon, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}
