// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const adminOverview = `-- name: AdminOverview :one
SELECT (SELECT count(*)::int FROM users) AS users,
 (SELECT count(*)::int FROM teams) AS teams,(SELECT count(*)::int FROM projects) AS projects
`

type AdminOverviewRow struct {
	Users    int32 `json:"users"`
	Teams    int32 `json:"teams"`
	Projects int32 `json:"projects"`
}

func (q *Queries) AdminOverview(ctx context.Context) (AdminOverviewRow, error) {
	row := q.db.QueryRowContext(ctx, adminOverview)
	var i AdminOverviewRow
	err := row.Scan(&i.Users, &i.Teams, &i.Projects)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects(team_id,name,created_by_user_id) VALUES($1,$2,$3) RETURNING id
`

type CreateProjectParams struct {
	TeamID          int32         `json:"team_id"`
	Name            string        `json:"name"`
	CreatedByUserID sql.NullInt32 `json:"created_by_user_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.TeamID, arg.Name, arg.CreatedByUserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams(name) VALUES($1) RETURNING id
`

func (q *Queries) CreateTeam(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRowContext(ctx, createTeam, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createTeamOwner = `-- name: CreateTeamOwner :exec
INSERT INTO team_members(team_id,user_id,role) VALUES($1,$2,'owner')
`

type CreateTeamOwnerParams struct {
	TeamID int32 `json:"team_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) CreateTeamOwner(ctx context.Context, arg CreateTeamOwnerParams) error {
	_, err := q.db.ExecContext(ctx, createTeamOwner, arg.TeamID, arg.UserID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT p.id,p.team_id,p.name,p.description,t.name AS team_name,tm.role,
 coalesce(array_agg(DISTINCT pp.permission) FILTER(WHERE pp.permission IS NOT NULL),'{}'::text[])::text[] AS permissions,
 p.updated_at
FROM projects p JOIN teams t ON t.id=p.team_id
JOIN team_members tm ON tm.team_id=t.id AND tm.user_id=$1
LEFT JOIN project_permissions pp ON pp.project_id=p.id AND pp.team_id=p.team_id AND pp.user_id=$1
WHERE p.id=$2 GROUP BY p.id,t.name,tm.role
`

type GetProjectParams struct {
	UserID    int32 `json:"user_id"`
	ProjectID int32 `json:"project_id"`
}

type GetProjectRow struct {
	ID          int32          `json:"id"`
	TeamID      int32          `json:"team_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	TeamName    string         `json:"team_name"`
	Role        string         `json:"role"`
	Permissions []string       `json:"permissions"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.UserID, arg.ProjectID)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.TeamName,
		&i.Role,
		pq.Array(&i.Permissions),
		&i.UpdatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT t.id, t.name, current_members.role,
 count(all_members.id)::int AS member_count, t.created_at, t.updated_at
FROM teams t
JOIN team_members current_members ON current_members.team_id=t.id AND current_members.user_id=$1
LEFT JOIN team_members all_members ON all_members.team_id=t.id
WHERE t.id=$2 GROUP BY t.id,current_members.role
`

type GetTeamParams struct {
	UserID int32 `json:"user_id"`
	TeamID int32 `json:"team_id"`
}

type GetTeamRow struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Role        string    `json:"role"`
	MemberCount int32     `json:"member_count"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (GetTeamRow, error) {
	row := q.db.QueryRowContext(ctx, getTeam, arg.UserID, arg.TeamID)
	var i GetTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamManager = `-- name: GetTeamManager :one
SELECT id FROM team_members WHERE team_id=$1 AND user_id=$2 AND role IN ('owner','admin') FOR UPDATE
`

type GetTeamManagerParams struct {
	TeamID int32 `json:"team_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetTeamManager(ctx context.Context, arg GetTeamManagerParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getTeamManager, arg.TeamID, arg.UserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listAdminProjects = `-- name: ListAdminProjects :many
SELECT p.id,p.name,p.description,t.name AS team_name,u.name AS created_by_name,p.created_at
FROM projects p JOIN teams t ON t.id=p.team_id LEFT JOIN users u ON u.id=p.created_by_user_id ORDER BY p.created_at DESC
`

type ListAdminProjectsRow struct {
	ID            int32          `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	TeamName      string         `json:"team_name"`
	CreatedByName sql.NullString `json:"created_by_name"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) ListAdminProjects(ctx context.Context) ([]ListAdminProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminProjectsRow{}
	for rows.Next() {
		var i ListAdminProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TeamName,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminTeams = `-- name: ListAdminTeams :many
SELECT t.id,t.name,count(DISTINCT tm.id)::int AS member_count,u.id AS owner_user_id,u.name AS owner_name
FROM teams t LEFT JOIN team_members tm ON tm.team_id=t.id
LEFT JOIN team_members owners ON owners.team_id=t.id AND owners.role='owner'
LEFT JOIN users u ON u.id=owners.user_id GROUP BY t.id,u.id,u.name ORDER BY t.name
`

type ListAdminTeamsRow struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	MemberCount int32          `json:"member_count"`
	OwnerUserID sql.NullInt32  `json:"owner_user_id"`
	OwnerName   sql.NullString `json:"owner_name"`
}

func (q *Queries) ListAdminTeams(ctx context.Context) ([]ListAdminTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminTeamsRow{}
	for rows.Next() {
		var i ListAdminTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MemberCount,
			&i.OwnerUserID,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id,name,email,phone,role,created_at FROM users ORDER BY created_at DESC
`

type ListAdminUsersRow struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Role      string         `json:"role"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileTeams = `-- name: ListProfileTeams :many
SELECT t.id,t.name,tm.role,tm.created_at AS joined_at FROM teams t
JOIN team_members tm ON tm.team_id=t.id WHERE tm.user_id=$1 ORDER BY t.name
`

type ListProfileTeamsRow struct {
	ID       int32     `json:"id"`
	Name     string    `json:"name"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) ListProfileTeams(ctx context.Context, userID int32) ([]ListProfileTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfileTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileTeamsRow{}
	for rows.Next() {
		var i ListProfileTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id,p.team_id,p.name,p.description,t.name AS team_name,tm.role,
 coalesce(array_agg(DISTINCT pp.permission) FILTER(WHERE pp.permission IS NOT NULL),'{}'::text[])::text[] AS permissions,
 p.updated_at
FROM projects p JOIN teams t ON t.id=p.team_id
JOIN team_members tm ON tm.team_id=t.id AND tm.user_id=$1
LEFT JOIN project_permissions pp ON pp.project_id=p.id AND pp.team_id=p.team_id AND pp.user_id=$1
WHERE ($2::text<>'joined' OR tm.role='member')
 AND ($2::text<>'managed' OR tm.role IN ('owner','admin'))
 AND ($3::text='' OR p.name ILIKE '%'||$3::text||'%' OR coalesce(p.description,'') ILIKE '%'||$3::text||'%' OR t.name ILIKE '%'||$3::text||'%')
GROUP BY p.id,t.name,tm.role ORDER BY p.updated_at DESC
`

type ListProjectsParams struct {
	UserID int32  `json:"user_id"`
	Scope  string `json:"scope"`
	Search string `json:"search"`
}

type ListProjectsRow struct {
	ID          int32          `json:"id"`
	TeamID      int32          `json:"team_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	TeamName    string         `json:"team_name"`
	Role        string         `json:"role"`
	Permissions []string       `json:"permissions"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.UserID, arg.Scope, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.TeamName,
			&i.Role,
			pq.Array(&i.Permissions),
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamProjects = `-- name: ListTeamProjects :many
SELECT id,name,description,updated_at FROM projects WHERE team_id=$1 ORDER BY updated_at DESC
`

type ListTeamProjectsRow struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) ListTeamProjects(ctx context.Context, teamID int32) ([]ListTeamProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamProjects, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamProjectsRow{}
	for rows.Next() {
		var i ListTeamProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.name, current_members.role,
 count(all_members.id)::int AS member_count, t.created_at, t.updated_at
FROM teams t
JOIN team_members current_members ON current_members.team_id=t.id AND current_members.user_id=$1
LEFT JOIN team_members all_members ON all_members.team_id=t.id
WHERE ($2::text='' OR t.name ILIKE '%'||$2::text||'%')
 AND ($3::text<>'managed' OR current_members.role IN ('owner','admin'))
GROUP BY t.id,current_members.role ORDER BY t.name
`

type ListTeamsParams struct {
	UserID int32  `json:"user_id"`
	Search string `json:"search"`
	Scope  string `json:"scope"`
}

type ListTeamsRow struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Role        string    `json:"role"`
	MemberCount int32     `json:"member_count"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeams, arg.UserID, arg.Search, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
