// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery_main.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const discoveryBind = `-- name: DiscoveryBind :exec
update device_external_identities set device_id=$1,suggested_device_type_id=$2,
      match_confidence=1,discovery_status='managed',bound_at=now()
      where project_id=$3 and id=$4 and device_id is null
`

type DiscoveryBindParams struct {
	P3 sql.NullInt32 `json:"p3"`
	P4 sql.NullInt64 `json:"p4"`
	P1 int32         `json:"p1"`
	P2 int64         `json:"p2"`
}

func (q *Queries) DiscoveryBind(ctx context.Context, arg DiscoveryBindParams) error {
	_, err := q.db.ExecContext(ctx, discoveryBind,
		arg.P3,
		arg.P4,
		arg.P1,
		arg.P2,
	)
	return err
}

const discoveryCapabilities = `-- name: DiscoveryCapabilities :exec
insert into device_capabilities(
      device_id,project_id,capability_code,version,declared_by_adapter_id,params_schema_json,
      input_schema_json,output_schema_json,risk_level,source_json
    ) select $1,$2,capability->>'code',driver.version,$3,
      coalesce(capability->'inputSchema','{}'),coalesce(capability->'inputSchema','{}'),
      coalesce(capability->'outputSchema','{}'),coalesce(capability->>'risk','low'),
      jsonb_build_object('driver',driver.driver_key,'typeKey',type.type_key)
      from device_types type join driver_definitions driver on driver.id=type.driver_definition_id
      cross join lateral jsonb_array_elements(case when jsonb_typeof(driver.manifest_json->'capabilities')='array'
        then driver.manifest_json->'capabilities' else '[]'::jsonb end) capability
      where type.id=$4 and type.capability_profile_json ? (capability->>'code')
      on conflict(device_id,capability_code) do update set declared_by_adapter_id=excluded.declared_by_adapter_id,
        availability='available',availability_reason=null,updated_at=now()
`

type DiscoveryCapabilitiesParams struct {
	P1 int32         `json:"p1"`
	P2 int32         `json:"p2"`
	P3 sql.NullInt64 `json:"p3"`
	P4 int64         `json:"p4"`
}

func (q *Queries) DiscoveryCapabilities(ctx context.Context, arg DiscoveryCapabilitiesParams) error {
	_, err := q.db.ExecContext(ctx, discoveryCapabilities,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
	)
	return err
}

const discoveryConnectors = `-- name: DiscoveryConnectors :many
SELECT to_jsonb(r) FROM (
select adapter.id::text,adapter.name,definition.connector_key as "connectorKey",adapter.status,
      (definition.connector_key='dji.flighthub2' and definition.status='active' and adapter.status in('connecting','connected','degraded')) as "canScan"
      from device_adapters adapter join connector_definitions definition on definition.id=adapter.connector_definition_id
      where adapter.project_id=$1 order by adapter.name
) r
`

func (q *Queries) DiscoveryConnectors(ctx context.Context, p1 int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, discoveryConnectors, p1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoveryCreate = `-- name: DiscoveryCreate :one
insert into devices(
        project_id,adapter_id,device_type_id,name,type,status,metadata_json
      ) values($1,$2,$3,$4,$5,'unknown',$6) returning id
`

type DiscoveryCreateParams struct {
	P1 int32           `json:"p1"`
	P2 sql.NullInt64   `json:"p2"`
	P3 int64           `json:"p3"`
	P4 string          `json:"p4"`
	P5 string          `json:"p5"`
	P6 json.RawMessage `json:"p6"`
}

func (q *Queries) DiscoveryCreate(ctx context.Context, arg DiscoveryCreateParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, discoveryCreate,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const discoveryIgnore = `-- name: DiscoveryIgnore :exec
update device_external_identities set discovery_status='ignored'
        where project_id=$1 and id=$2
`

type DiscoveryIgnoreParams struct {
	P1 int32 `json:"p1"`
	P2 int64 `json:"p2"`
}

func (q *Queries) DiscoveryIgnore(ctx context.Context, arg DiscoveryIgnoreParams) error {
	_, err := q.db.ExecContext(ctx, discoveryIgnore, arg.P1, arg.P2)
	return err
}

const discoveryList = `-- name: DiscoveryList :many
SELECT to_jsonb(r) FROM (
select identity.id::text,identity.adapter_id::text as "connectorId",adapter.name as "connectorName",
             definition.connector_key as "connectorKey",identity.external_device_id as "externalDeviceId",
             identity.external_device_type as "externalDeviceType",
             nullif(identity.identity_json->>'parentExternalId','') as "parentExternalId",
             identity.discovery_status as status,type.type_key as "suggestedTypeKey",
             type.display_name as "suggestedTypeName",identity.match_confidence::float8 as "matchConfidence",
             identity.device_id as "deviceId",identity.last_seen_at::text as "lastSeenAt"
        from device_external_identities identity
        join device_adapters adapter on adapter.id=identity.adapter_id and adapter.project_id=identity.project_id
        join connector_definitions definition on definition.id=adapter.connector_definition_id
        left join device_types type on type.id=identity.suggested_device_type_id
       where identity.project_id=$1
       order by case identity.discovery_status when 'conflicted' then 0 when 'discovered' then 1 when 'missing' then 2 when 'managed' then 3 else 4 end,
                identity.last_seen_at desc,identity.id
) r
`

func (q *Queries) DiscoveryList(ctx context.Context, p1 int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, discoveryList, p1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoveryLockBinding = `-- name: DiscoveryLockBinding :many
SELECT to_jsonb(r) FROM (
select identity.id::text,adapter_id::text as "adapterId",device_id as "deviceId",discovery_status as status,
		nullif(identity.identity_json->>'parentExternalId','') as "parentExternalId",identity.team_id as "teamId",
		adapter.status as "connectorStatus"
		from device_external_identities identity
		join device_adapters adapter on adapter.id=identity.adapter_id and adapter.project_id=identity.project_id
		where identity.project_id=$1 and identity.id=$2 for update of identity,adapter
) r
`

type DiscoveryLockBindingParams struct {
	P1 int32 `json:"p1"`
	P2 int64 `json:"p2"`
}

func (q *Queries) DiscoveryLockBinding(ctx context.Context, arg DiscoveryLockBindingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, discoveryLockBinding, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoveryLockStatus = `-- name: DiscoveryLockStatus :many
SELECT to_jsonb(r) FROM (
select discovery_status as status,device_id as "deviceId" from device_external_identities
        where project_id=$1 and id=$2 for update
) r
`

type DiscoveryLockStatusParams struct {
	P1 int32 `json:"p1"`
	P2 int64 `json:"p2"`
}

func (q *Queries) DiscoveryLockStatus(ctx context.Context, arg DiscoveryLockStatusParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, discoveryLockStatus, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoveryLockTarget = `-- name: DiscoveryLockTarget :many
SELECT to_jsonb(r) FROM (
select id from devices where project_id=$1 and id=$2 for update
) r
`

type DiscoveryLockTargetParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
}

func (q *Queries) DiscoveryLockTarget(ctx context.Context, arg DiscoveryLockTargetParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, discoveryLockTarget, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoveryMatch = `-- name: DiscoveryMatch :many
SELECT to_jsonb(r) FROM (
select type.id::text,type.type_key as "typeKey"
      from device_external_identities identity join device_types type on type.type_key=identity.external_device_type
      where identity.project_id=$1 and identity.id=$2 and type.status='active'
      order by type.version desc limit 1
) r
`

type DiscoveryMatchParams struct {
	P1 int32 `json:"p1"`
	P2 int64 `json:"p2"`
}

func (q *Queries) DiscoveryMatch(ctx context.Context, arg DiscoveryMatchParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, discoveryMatch, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoveryRelationship = `-- name: DiscoveryRelationship :exec
insert into device_relationships(
      project_id,team_id,from_device_id,to_device_id,relation_type,source_type,metadata_json
    ) select $1,$2,parent.device_id,$3,'contains','discovery',$4
      from device_external_identities parent where parent.project_id=$1 and parent.adapter_id=$5
        and parent.external_device_id=$6 and parent.device_id is not null
        and not exists(select 1 from device_relationships relation where relation.project_id=$1
          and relation.from_device_id=parent.device_id and relation.to_device_id=$3 and relation.valid_until is null)
`

type DiscoveryRelationshipParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 int32           `json:"p3"`
	P6 json.RawMessage `json:"p6"`
	P4 int64           `json:"p4"`
	P5 string          `json:"p5"`
}

func (q *Queries) DiscoveryRelationship(ctx context.Context, arg DiscoveryRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, discoveryRelationship,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P6,
		arg.P4,
		arg.P5,
	)
	return err
}

const discoveryRematch = `-- name: DiscoveryRematch :exec
update device_external_identities
      set suggested_device_type_id=$1,match_confidence=case when $1::bigint is null then null else 1 end,discovery_status=$2
      where project_id=$3 and id=$4
`

type DiscoveryRematchParams struct {
	P3 sql.NullInt64 `json:"p3"`
	P4 string        `json:"p4"`
	P1 int32         `json:"p1"`
	P2 int64         `json:"p2"`
}

func (q *Queries) DiscoveryRematch(ctx context.Context, arg DiscoveryRematchParams) error {
	_, err := q.db.ExecContext(ctx, discoveryRematch,
		arg.P3,
		arg.P4,
		arg.P1,
		arg.P2,
	)
	return err
}

const discoveryRoute = `-- name: DiscoveryRoute :exec
insert into device_connector_bindings(
      project_id,team_id,device_id,connector_instance_id,external_identity_id,route_role,priority,status,metadata_json
    ) values($1,$2,$3,$4,$5,$6,
      coalesce((select max(priority)+10 from device_connector_bindings where project_id=$1 and device_id=$3),100),
      'active',$7)
    on conflict(device_id,connector_instance_id) do update set external_identity_id=excluded.external_identity_id,
      route_role=excluded.route_role,priority=excluded.priority,status='active',unbound_at=null,metadata_json=excluded.metadata_json
`

type DiscoveryRouteParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 int32           `json:"p3"`
	P4 int64           `json:"p4"`
	P5 int64           `json:"p5"`
	P6 string          `json:"p6"`
	P7 json.RawMessage `json:"p7"`
}

func (q *Queries) DiscoveryRoute(ctx context.Context, arg DiscoveryRouteParams) error {
	_, err := q.db.ExecContext(ctx, discoveryRoute,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
	)
	return err
}

const discoveryStandby = `-- name: DiscoveryStandby :exec
update device_connector_bindings set status='standby'
        where project_id=$1 and device_id=$2 and status='active'
`

type DiscoveryStandbyParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
}

func (q *Queries) DiscoveryStandby(ctx context.Context, arg DiscoveryStandbyParams) error {
	_, err := q.db.ExecContext(ctx, discoveryStandby, arg.P1, arg.P2)
	return err
}

const discoveryType = `-- name: DiscoveryType :many
SELECT to_jsonb(r) FROM (
select id::text,category from device_types
      where type_key=$1 and status='active' order by version desc limit 1
) r
`

func (q *Queries) DiscoveryType(ctx context.Context, p1 string) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, discoveryType, p1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoveryTypes = `-- name: DiscoveryTypes :many
SELECT to_jsonb(r) FROM (
select id::text,type_key as "typeKey",display_name as "displayName",category
      from device_types where status='active' order by display_name,version desc
) r
`

func (q *Queries) DiscoveryTypes(ctx context.Context) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, discoveryTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoveryUpdateAdapter = `-- name: DiscoveryUpdateAdapter :exec
update devices set adapter_id=$1,updated_at=now() where project_id=$2 and id=$3
`

type DiscoveryUpdateAdapterParams struct {
	P3 sql.NullInt64 `json:"p3"`
	P1 int32         `json:"p1"`
	P2 int32         `json:"p2"`
}

func (q *Queries) DiscoveryUpdateAdapter(ctx context.Context, arg DiscoveryUpdateAdapterParams) error {
	_, err := q.db.ExecContext(ctx, discoveryUpdateAdapter, arg.P3, arg.P1, arg.P2)
	return err
}
