// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_control_sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const fHControlAuthorize = `-- name: FHControlAuthorize :many
SELECT to_jsonb(r) FROM (
select adapter.project_id as "connectorProjectId",adapter.team_id as "connectorTeamId",
        device.project_id as "deviceProjectId",adapter.status as "connectorStatus",
        coalesce(flags.flighthub_action_flags_json @> '{"device.control":true}'::jsonb,false) as "featureEnabled",
        exists(select 1 from connector_capability_snapshots capability where capability.project_id=adapter.project_id
          and capability.connector_instance_id=adapter.id and capability.capability_code='device.control'
		  and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
		  and capability.region='cn' and capability.deployment='cn-public-cloud'
		  and capability.device_model=device.device_model and capability.firmware_version=device.firmware_version
          and capability.status='supported' and capability.evidence_level='field-write'
          and (capability.expires_at is null or capability.expires_at>now())) as "capabilityFieldVerified",
        device.status='online' as "deviceOnline",latest.captured_at as "stateCapturedAt",
        project.current_safety_policy_version_id::text as "currentSafetyPolicyVersionId",
        approval.project_id as "approvalProjectId",approval.team_id as "approvalTeamId",
        approval.resource_type as "approvalResourceType",approval.resource_id as "approvalResourceId",
        approval.action as "approvalAction",approval.status as "approvalStatus",
        coalesce(approval.expires_at>now(),false) as "approvalUnexpired",
        (select count(*)::int from connector_control_sessions session where session.project_id=device.project_id
          and session.device_id=device.id and session.status in('requested','acquiring','active','releasing')) as "conflictingSessionCount"
       from device_adapters adapter
       join projects project on project.id=adapter.project_id and project.team_id=adapter.team_id
       join devices device on device.project_id=adapter.project_id and device.id=$1
       join device_external_identities identity on identity.project_id=adapter.project_id and identity.adapter_id=adapter.id
         and identity.device_id=device.id
       left join project_feature_flags flags on flags.project_id=adapter.project_id
       left join device_latest_telemetry latest on latest.project_id=device.project_id and latest.device_id=device.id and latest.adapter_id=adapter.id
       left join approval_requests approval on approval.id::text=$2 and approval.project_id=adapter.project_id
       where adapter.project_id=$3 and adapter.id=$4
) r
`

type FHControlAuthorizeParams struct {
	P2 int32     `json:"p2"`
	P4 uuid.UUID `json:"p4"`
	P1 int32     `json:"p1"`
	P3 int64     `json:"p3"`
}

func (q *Queries) FHControlAuthorize(ctx context.Context, arg FHControlAuthorizeParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHControlAuthorize,
		arg.P2,
		arg.P4,
		arg.P1,
		arg.P3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHControlClaim = `-- name: FHControlClaim :one
update connector_control_sessions set
      operation_count=case when operation_window_started_at<=now()-interval '1 second' then 1 else operation_count+1 end,
      operation_window_started_at=case when operation_window_started_at<=now()-interval '1 second' then now() else operation_window_started_at end,
      last_operation_at=now(),updated_at=now()
     where project_id=$1 and id=$2::uuid and device_id=$3 and holder_user_id=$4 and status='active'
       and lease_expires_at>now() and absolute_expires_at>now()
       and (operation_window_started_at<=now()-interval '1 second' or operation_count<$5)
     returning id
`

type FHControlClaimParams struct {
	P1 int32     `json:"p1"`
	P2 uuid.UUID `json:"p2"`
	P3 int32     `json:"p3"`
	P4 int32     `json:"p4"`
	P5 int32     `json:"p5"`
}

func (q *Queries) FHControlClaim(ctx context.Context, arg FHControlClaimParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, fHControlClaim,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const fHControlEnqueueAcquire = `-- name: FHControlEnqueueAcquire :exec
insert into outbox_events(project_id,team_id,event_id,event_type,aggregate_type,aggregate_id,payload_json,max_attempts)
       values($1,$2,$3,'flighthub.control_session.reconcile','connector_control_session',$4,$5,8)
       on conflict(event_id) do nothing
`

type FHControlEnqueueAcquireParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
	P4 sql.NullString  `json:"p4"`
	P5 json.RawMessage `json:"p5"`
}

func (q *Queries) FHControlEnqueueAcquire(ctx context.Context, arg FHControlEnqueueAcquireParams) error {
	_, err := q.db.ExecContext(ctx, fHControlEnqueueAcquire,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
	)
	return err
}

const fHControlEnqueueRelease = `-- name: FHControlEnqueueRelease :exec
insert into outbox_events(project_id,team_id,event_id,event_type,aggregate_type,aggregate_id,payload_json,max_attempts)
       values($1,$2,$3,'flighthub.control_session.reconcile','connector_control_session',$4,$5,8)
       on conflict(event_id) do nothing
`

type FHControlEnqueueReleaseParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
	P4 sql.NullString  `json:"p4"`
	P5 json.RawMessage `json:"p5"`
}

func (q *Queries) FHControlEnqueueRelease(ctx context.Context, arg FHControlEnqueueReleaseParams) error {
	_, err := q.db.ExecContext(ctx, fHControlEnqueueRelease,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
	)
	return err
}

const fHControlExisting = `-- name: FHControlExisting :many
SELECT to_jsonb(r) FROM (
select id::text,status,holder_user_id as "holderUserId",connector_instance_id::text as "connectorInstanceId",
        approval_request_id::text as "approvalRequestId",safety_policy_version_id::text as "safetyPolicyVersionId",
        controls_json=$1::jsonb as "controlsMatch" from connector_control_sessions
       where project_id=$2 and device_id=$3 and idempotency_key=$4
) r
`

type FHControlExistingParams struct {
	P4 json.RawMessage `json:"p4"`
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
}

func (q *Queries) FHControlExisting(ctx context.Context, arg FHControlExistingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHControlExisting,
		arg.P4,
		arg.P1,
		arg.P2,
		arg.P3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHControlHeartbeat = `-- name: FHControlHeartbeat :one
update connector_control_sessions set last_heartbeat_at=$1,
      lease_expires_at=least(absolute_expires_at,$1+($2*interval '1 millisecond')),updated_at=now()
     where project_id=$3 and id=$4::uuid and device_id=$5 and holder_user_id=$6 and status='active'
       and lease_expires_at>$1 and absolute_expires_at>$1
       and last_heartbeat_at<=$1-($7*interval '1 millisecond')
     returning id::text,status,lease_expires_at as "leaseExpiresAt"
`

type FHControlHeartbeatParams struct {
	P3 time.Time   `json:"p3"`
	P4 interface{} `json:"p4"`
	P1 int32       `json:"p1"`
	P2 uuid.UUID   `json:"p2"`
	P7 int32       `json:"p7"`
	P5 int32       `json:"p5"`
	P6 interface{} `json:"p6"`
}

type FHControlHeartbeatRow struct {
	ID             string    `json:"id"`
	Status         string    `json:"status"`
	LeaseExpiresAt time.Time `json:"leaseExpiresAt"`
}

func (q *Queries) FHControlHeartbeat(ctx context.Context, arg FHControlHeartbeatParams) (FHControlHeartbeatRow, error) {
	row := q.db.QueryRowContext(ctx, fHControlHeartbeat,
		arg.P3,
		arg.P4,
		arg.P1,
		arg.P2,
		arg.P7,
		arg.P5,
		arg.P6,
	)
	var i FHControlHeartbeatRow
	err := row.Scan(&i.ID, &i.Status, &i.LeaseExpiresAt)
	return i, err
}

const fHControlInsert = `-- name: FHControlInsert :one
insert into connector_control_sessions(
        id,project_id,team_id,connector_instance_id,device_id,holder_user_id,approval_request_id,
        safety_policy_version_id,idempotency_key,controls_json,last_heartbeat_at,lease_expires_at,
        absolute_expires_at,operation_window_started_at
      ) values($1,$2,$3,$4,$5,$6,$7::uuid,$8,$9,$10::jsonb,$11,$12,$13,$11) returning id::text,status
`

type FHControlInsertParams struct {
	P1  uuid.UUID       `json:"p1"`
	P2  int32           `json:"p2"`
	P3  int32           `json:"p3"`
	P4  int64           `json:"p4"`
	P5  int32           `json:"p5"`
	P6  int32           `json:"p6"`
	P7  uuid.UUID       `json:"p7"`
	P8  int64           `json:"p8"`
	P9  string          `json:"p9"`
	P10 json.RawMessage `json:"p10"`
	P11 time.Time       `json:"p11"`
	P12 time.Time       `json:"p12"`
	P13 time.Time       `json:"p13"`
}

type FHControlInsertRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FHControlInsert(ctx context.Context, arg FHControlInsertParams) (FHControlInsertRow, error) {
	row := q.db.QueryRowContext(ctx, fHControlInsert,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
		arg.P11,
		arg.P12,
		arg.P13,
	)
	var i FHControlInsertRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const fHControlLockDevice = `-- name: FHControlLockDevice :many
SELECT to_jsonb(r) FROM (
select id from devices where project_id=$1 and id=$2 for update
) r
`

type FHControlLockDeviceParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
}

func (q *Queries) FHControlLockDevice(ctx context.Context, arg FHControlLockDeviceParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHControlLockDevice, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHControlLockSession = `-- name: FHControlLockSession :many
SELECT to_jsonb(r) FROM (
select status,holder_user_id as "holderUserId" from connector_control_sessions
       where project_id=$1 and device_id=$2 and id=$3::uuid for update
) r
`

type FHControlLockSessionParams struct {
	P1 int32     `json:"p1"`
	P3 int32     `json:"p3"`
	P2 uuid.UUID `json:"p2"`
}

func (q *Queries) FHControlLockSession(ctx context.Context, arg FHControlLockSessionParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHControlLockSession, arg.P1, arg.P3, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHControlRelease = `-- name: FHControlRelease :exec
update connector_control_sessions set status='releasing',release_requested_at=coalesce(release_requested_at,now()),updated_at=now()
      where project_id=$1 and id=$2::uuid
`

type FHControlReleaseParams struct {
	P1 int32     `json:"p1"`
	P2 uuid.UUID `json:"p2"`
}

func (q *Queries) FHControlRelease(ctx context.Context, arg FHControlReleaseParams) error {
	_, err := q.db.ExecContext(ctx, fHControlRelease, arg.P1, arg.P2)
	return err
}
