// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_diagnostics_workspace.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const readFHDiagnosticsAccess = `-- name: ReadFHDiagnosticsAccess :many
SELECT to_jsonb(r) FROM (
select adapter.id::text,adapter.name,adapter.status,
             adapter.last_health_json->>'code' as "lastErrorCode",adapter.last_checked_at as "lastCheckedAt"
        from device_adapters adapter
        join connector_definitions definition on definition.id=adapter.connector_definition_id
        join projects project on project.id=adapter.project_id and project.team_id=adapter.team_id
        join team_members membership on membership.team_id=project.team_id and membership.user_id=$1
       where adapter.project_id=$2 and adapter.id=$3
         and definition.connector_key='dji.flighthub2' and definition.version='1.0.0'
) r
`

type ReadFHDiagnosticsAccessParams struct {
	UserID      int32 `json:"user_id"`
	ProjectID   int32 `json:"project_id"`
	ConnectorID int64 `json:"connector_id"`
}

func (q *Queries) ReadFHDiagnosticsAccess(ctx context.Context, arg ReadFHDiagnosticsAccessParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, readFHDiagnosticsAccess, arg.UserID, arg.ProjectID, arg.ConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readFHDiagnosticsCapabilities = `-- name: ReadFHDiagnosticsCapabilities :many
SELECT to_jsonb(r) FROM (
select capability_code as "capabilityCode",status,evidence_level as "evidenceLevel",region,deployment,
               device_model as "deviceModel",firmware_version as "firmwareVersion",
               details_json->>'reason' as reason,details_json->>'endpointId' as "endpointId",
               details_json->'layers' as layers,verified_at as "verifiedAt",expires_at as "expiresAt",
               (expires_at is not null and expires_at<=now()) as expired
          from connector_capability_snapshots capability
         where capability.project_id=$1 and capability.connector_instance_id=$2
		   and ((account_fingerprint is null and evidence_level in('documented','fixture'))
		     or account_fingerprint=(select discovery_scope_json->>'accountFingerprint' from device_adapters
		       where id=$2 and project_id=$1))
         order by capability_code,verified_at desc
         limit 500
) r
`

type ReadFHDiagnosticsCapabilitiesParams struct {
	ProjectID   int32 `json:"project_id"`
	ConnectorID int64 `json:"connector_id"`
}

func (q *Queries) ReadFHDiagnosticsCapabilities(ctx context.Context, arg ReadFHDiagnosticsCapabilitiesParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, readFHDiagnosticsCapabilities, arg.ProjectID, arg.ConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readFHDiagnosticsWatermarks = `-- name: ReadFHDiagnosticsWatermarks :many
SELECT to_jsonb(r) FROM (
select resource_kind as "resourceKind",status,attempt_count::int as "attemptCount",
               last_error_code as "lastErrorCode",last_started_at as "lastStartedAt",
               last_succeeded_at as "lastSucceededAt",next_attempt_at as "nextAttemptAt"
          from connector_resource_sync_states
         where project_id=$1 and connector_instance_id=$2
         order by resource_kind
) r
`

type ReadFHDiagnosticsWatermarksParams struct {
	ProjectID   int32 `json:"project_id"`
	ConnectorID int64 `json:"connector_id"`
}

func (q *Queries) ReadFHDiagnosticsWatermarks(ctx context.Context, arg ReadFHDiagnosticsWatermarksParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, readFHDiagnosticsWatermarks, arg.ProjectID, arg.ConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
