// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_deviceadmin_actions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const fHDeviceAdminAuthorize = `-- name: FHDeviceAdminAuthorize :many
SELECT to_jsonb(r) FROM (
select $1::int as "teamId",member.role,adapter.project_id as "connectorProjectId",adapter.team_id as "connectorTeamId",
    adapter.status as "connectorStatus",coalesce(flags.flighthub_action_flags_json @> jsonb_build_object($2::text,true),false) as "featureEnabled",
    exists(select 1 from connector_capability_snapshots capability where capability.project_id=adapter.project_id
      and capability.connector_instance_id=adapter.id and capability.capability_code=$3 and capability.status='supported'
	  and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
	  and capability.region='cn' and capability.deployment='cn-public-cloud'
      and capability.evidence_level='field-write' and (capability.expires_at is null or capability.expires_at>now())
      and (($4::int is null and capability.device_model is null and capability.firmware_version is null)
        or ($4::int is not null and capability.device_model=device.device_model and capability.firmware_version=device.firmware_version))) as "capabilityVerified",
    device.project_id as "deviceProjectId",identity.id is not null as "identityPresent",coalesce(device.status='online',false) as "deviceOnline",
    coalesce(latest.captured_at>now()-interval '30 seconds' and latest.captured_at<=now()+interval '1 second',false) as "stateFresh",
    approval.project_id as "approvalProjectId",approval.team_id as "approvalTeamId",approval.resource_type as "approvalResourceType",
    approval.resource_id as "approvalResourceId",approval.action as "approvalAction",approval.status as "approvalStatus",
    coalesce(approval.expires_at>now(),false) as "approvalUnexpired"
   from device_adapters adapter join team_members member on member.team_id=adapter.team_id and member.user_id=$5
   left join project_feature_flags flags on flags.project_id=adapter.project_id
   left join devices device on device.id=$4 and device.project_id=adapter.project_id
   left join device_external_identities identity on identity.project_id=adapter.project_id and identity.adapter_id=adapter.id and identity.device_id=device.id
   left join device_latest_telemetry latest on latest.project_id=adapter.project_id and latest.adapter_id=adapter.id and latest.device_id=device.id
   left join approval_requests approval on approval.id=$6::uuid and approval.project_id=adapter.project_id
   where adapter.id=$7 and adapter.project_id=$8 and adapter.team_id=$1
) r
`

type FHDeviceAdminAuthorizeParams struct {
	P3 int32         `json:"p3"`
	P7 string        `json:"p7"`
	P6 string        `json:"p6"`
	P5 sql.NullInt32 `json:"p5"`
	P4 int32         `json:"p4"`
	P8 uuid.UUID     `json:"p8"`
	P2 int64         `json:"p2"`
	P1 int32         `json:"p1"`
}

func (q *Queries) FHDeviceAdminAuthorize(ctx context.Context, arg FHDeviceAdminAuthorizeParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHDeviceAdminAuthorize,
		arg.P3,
		arg.P7,
		arg.P6,
		arg.P5,
		arg.P4,
		arg.P8,
		arg.P2,
		arg.P1,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHDeviceAdminEnqueue = `-- name: FHDeviceAdminEnqueue :exec
insert into outbox_events(project_id,team_id,event_id,event_type,aggregate_type,aggregate_id,payload_json,max_attempts) values($1,$2,$3,'flighthub.device_admin.requested','connector_device_admin_job',$4,$5,8) on conflict(event_id) do nothing
`

type FHDeviceAdminEnqueueParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
	P4 sql.NullString  `json:"p4"`
	P5 json.RawMessage `json:"p5"`
}

func (q *Queries) FHDeviceAdminEnqueue(ctx context.Context, arg FHDeviceAdminEnqueueParams) error {
	_, err := q.db.ExecContext(ctx, fHDeviceAdminEnqueue,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
	)
	return err
}

const fHDeviceAdminExisting = `-- name: FHDeviceAdminExisting :many
SELECT to_jsonb(r) FROM (
select id::text,status,request_digest as "requestDigest",requested_by_user_id as "requestedByUserId" from connector_device_admin_jobs where project_id=$1 and connector_instance_id=$2 and action_kind=$3 and idempotency_key=$4
) r
`

type FHDeviceAdminExistingParams struct {
	P1 int32  `json:"p1"`
	P2 int64  `json:"p2"`
	P3 string `json:"p3"`
	P4 string `json:"p4"`
}

func (q *Queries) FHDeviceAdminExisting(ctx context.Context, arg FHDeviceAdminExistingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHDeviceAdminExisting,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHDeviceAdminInsert = `-- name: FHDeviceAdminInsert :one
insert into connector_device_admin_jobs(
      id,project_id,team_id,connector_instance_id,device_id,requested_by_user_id,approval_request_id,action_kind,
      capability_code,feature_flag,idempotency_key,request_digest,request_envelope_json
    ) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) on conflict(project_id,connector_instance_id,action_kind,idempotency_key) do nothing returning id::text,status
`

type FHDeviceAdminInsertParams struct {
	P1  uuid.UUID       `json:"p1"`
	P2  int32           `json:"p2"`
	P3  int32           `json:"p3"`
	P4  int64           `json:"p4"`
	P5  sql.NullInt32   `json:"p5"`
	P6  int32           `json:"p6"`
	P7  uuid.UUID       `json:"p7"`
	P8  string          `json:"p8"`
	P9  string          `json:"p9"`
	P10 string          `json:"p10"`
	P11 string          `json:"p11"`
	P12 string          `json:"p12"`
	P13 json.RawMessage `json:"p13"`
}

type FHDeviceAdminInsertRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FHDeviceAdminInsert(ctx context.Context, arg FHDeviceAdminInsertParams) (FHDeviceAdminInsertRow, error) {
	row := q.db.QueryRowContext(ctx, fHDeviceAdminInsert,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
		arg.P11,
		arg.P12,
		arg.P13,
	)
	var i FHDeviceAdminInsertRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const fHDeviceAdminRead = `-- name: FHDeviceAdminRead :many
SELECT to_jsonb(r) FROM (
select action_kind as action,status,attempt_count as "attemptCount",last_error_code as "lastErrorCode",result_json as result,result_envelope_json as "resultEnvelope" from connector_device_admin_jobs where id=$1::uuid and project_id=$2 and connector_instance_id=$3
) r
`

type FHDeviceAdminReadParams struct {
	P1 uuid.UUID `json:"p1"`
	P2 int32     `json:"p2"`
	P3 int64     `json:"p3"`
}

func (q *Queries) FHDeviceAdminRead(ctx context.Context, arg FHDeviceAdminReadParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHDeviceAdminRead, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
