// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_device_commands.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const fHCommandGovernance = `-- name: FHCommandGovernance :many
SELECT to_jsonb(r) FROM (
select coalesce(flags.flighthub_action_flags_json @> jsonb_build_object($1::text,true),false) as "featureEnabled",
          exists(select 1 from connector_capability_snapshots capability where capability.project_id=$2
            and capability.connector_instance_id=$3::bigint and capability.capability_code=$4
			and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
			and capability.region='cn' and capability.deployment='cn-public-cloud'
            and capability.status='supported' and capability.evidence_level='field-write'
            and capability.device_model=device.device_model and capability.firmware_version=device.firmware_version
            and (capability.expires_at is null or capability.expires_at>now())) as "capabilityFieldVerified",
          latest.captured_at as "stateCapturedAt",project.current_safety_policy_version_id::text as "currentSafetyPolicyVersionId",
          approval.project_id as "approvalProjectId",approval.team_id as "approvalTeamId",
          approval.resource_type as "approvalResourceType",approval.resource_id as "approvalResourceId",
          approval.action as "approvalAction",approval.status as "approvalStatus",
          coalesce(approval.expires_at>now(),false) as "approvalUnexpired"
        from projects project
        join devices device on device.project_id=project.id and device.id=$5
		join device_adapters adapter on adapter.id=$3::bigint and adapter.project_id=project.id
        left join project_feature_flags flags on flags.project_id=project.id
        left join device_latest_telemetry latest on latest.project_id=project.id and latest.device_id=$5 and latest.adapter_id=$3::bigint
        left join approval_requests approval on approval.id=$6::uuid and approval.project_id=project.id
        where project.id=$2
) r
`

type FHCommandGovernanceParams struct {
	P5 string        `json:"p5"`
	P1 int32         `json:"p1"`
	P3 int64         `json:"p3"`
	P6 string        `json:"p6"`
	P2 int32         `json:"p2"`
	P4 uuid.NullUUID `json:"p4"`
}

func (q *Queries) FHCommandGovernance(ctx context.Context, arg FHCommandGovernanceParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHCommandGovernance,
		arg.P5,
		arg.P1,
		arg.P3,
		arg.P6,
		arg.P2,
		arg.P4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHCommandRoutes = `-- name: FHCommandRoutes :many
SELECT to_jsonb(r) FROM (
select binding.connector_instance_id::text as "connectorInstanceId",definition.connector_key as "connectorKey",
              adapter.status as "connectorStatus",binding.priority
         from device_connector_bindings binding
         join device_adapters adapter on adapter.id=binding.connector_instance_id and adapter.project_id=binding.project_id
         join connector_definitions definition on definition.id=adapter.connector_definition_id
        where binding.project_id=$1 and binding.device_id=$2 and binding.status='active'
        order by binding.priority desc,binding.connector_instance_id limit 2
) r
`

type FHCommandRoutesParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
}

func (q *Queries) FHCommandRoutes(ctx context.Context, arg FHCommandRoutesParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHCommandRoutes, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
