// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_flight_actions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const fHFlightAuthorize = `-- name: FHFlightAuthorize :many
SELECT to_jsonb(r) FROM (
select (member.role in('owner','admin') or exists(select 1 from project_permissions permission
        where permission.project_id=run.project_id and permission.team_id=run.team_id
          and permission.user_id=member.user_id and permission.permission='mission:operate')) as "hasPermission",$1::int as "teamId",
      adapter.project_id as "connectorProjectId",adapter.team_id as "connectorTeamId",adapter.status as "connectorStatus",
      coalesce(flags.flighthub_action_flags_json @> '{"flight.execute":true}'::jsonb,false) as "actionEnabled",
      exists(select 1 from connector_capability_snapshots capability
        where capability.project_id=adapter.project_id and capability.connector_instance_id=adapter.id
          and capability.capability_code='flight.execute' and capability.status='supported'
		  and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
		  and capability.region='cn' and capability.deployment='cn-public-cloud'
		  and capability.device_model=device.device_model and capability.firmware_version=device.firmware_version
          and capability.evidence_level='field-write' and (capability.expires_at is null or capability.expires_at>now())) as "capabilityFieldVerified",
      run.project_id as "taskRunProjectId",run.team_id as "taskRunTeamId",run.status as "taskRunStatus",
      run.selected_device_id as "selectedDeviceId",run.safety_policy_version_id as "safetyPolicyVersionId",
      coalesce((run.preflight_snapshot_json->>'allowed')::boolean,false) as "preflightAllowed",
      identity.id is not null as "deviceIdentityPresent",
      approval.project_id as "approvalProjectId",approval.team_id as "approvalTeamId",approval.status as "approvalStatus",
      approval.resource_type as "approvalResourceType",approval.resource_id as "approvalResourceId",approval.action as "approvalAction",
      coalesce(approval.expires_at>now(),false) as "approvalUnexpired",
      coalesce((approval.context_json#>>'{preflight,allowed}')::boolean,false) as "approvalPreflightAllowed",
      wayline.project_id as "waylineProjectId",wayline.connector_instance_id as "waylineConnectorId",wayline.resource_kind as "waylineKind",
      target.project_id as "targetProjectId",target.connector_instance_id as "targetConnectorId",target.resource_kind as "targetKind",
      target.canonical_target_id as "targetTaskRunId"
    from task_runs run
    join device_adapters adapter on adapter.id=$2 and adapter.project_id=run.project_id
	join devices device on device.id=run.selected_device_id and device.project_id=run.project_id
    join team_members member on member.team_id=run.team_id and member.user_id=$3
    left join project_feature_flags flags on flags.project_id=run.project_id
    left join device_external_identities identity on identity.project_id=run.project_id
      and identity.adapter_id=adapter.id and identity.device_id=run.selected_device_id
    left join approval_requests approval on approval.id=$4 and approval.project_id=run.project_id
    left join connector_remote_resources wayline on wayline.id=$5 and wayline.project_id=run.project_id
      and wayline.status='active'
    left join connector_remote_resources target on target.id=$6 and target.project_id=run.project_id
      and target.status='active'
    where run.project_id=$7 and run.id=$8
) r
`

type FHFlightAuthorizeParams struct {
	P3 int32     `json:"p3"`
	P4 int64     `json:"p4"`
	P8 int32     `json:"p8"`
	P5 uuid.UUID `json:"p5"`
	P6 int64     `json:"p6"`
	P7 int64     `json:"p7"`
	P1 int32     `json:"p1"`
	P2 int32     `json:"p2"`
}

func (q *Queries) FHFlightAuthorize(ctx context.Context, arg FHFlightAuthorizeParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHFlightAuthorize,
		arg.P3,
		arg.P4,
		arg.P8,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P1,
		arg.P2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHFlightEnqueue = `-- name: FHFlightEnqueue :exec
insert into outbox_events(project_id,team_id,event_id,event_type,aggregate_type,aggregate_id,payload_json,max_attempts)
       values($1,$2,$3,'flighthub.flight_action.requested','connector_action_job',$4,$5,16)
       on conflict(event_id) do nothing
`

type FHFlightEnqueueParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
	P4 sql.NullString  `json:"p4"`
	P5 json.RawMessage `json:"p5"`
}

func (q *Queries) FHFlightEnqueue(ctx context.Context, arg FHFlightEnqueueParams) error {
	_, err := q.db.ExecContext(ctx, fHFlightEnqueue,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
	)
	return err
}

const fHFlightExisting = `-- name: FHFlightExisting :many
SELECT to_jsonb(r) FROM (
select id::text,status,request_digest as "requestDigest",task_run_id as "taskRunId",device_id as "deviceId",
          approval_request_id::text as "approvalRequestId",requested_by_user_id as "requestedByUserId",
          wayline_resource_id as "waylineResourceId",target_resource_id as "targetResourceId"
        from connector_action_jobs where project_id=$1 and connector_instance_id=$2 and action_kind=$3 and idempotency_key=$4
) r
`

type FHFlightExistingParams struct {
	P1 int32  `json:"p1"`
	P2 int64  `json:"p2"`
	P3 string `json:"p3"`
	P4 string `json:"p4"`
}

func (q *Queries) FHFlightExisting(ctx context.Context, arg FHFlightExistingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHFlightExisting,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHFlightInsert = `-- name: FHFlightInsert :one
insert into connector_action_jobs(
        id,project_id,team_id,connector_instance_id,task_run_id,device_id,wayline_resource_id,target_resource_id,
        approval_request_id,requested_by_user_id,action_kind,idempotency_key,request_digest,request_envelope_json
      ) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
      on conflict(project_id,connector_instance_id,action_kind,idempotency_key) do nothing
      returning id::text,status
`

type FHFlightInsertParams struct {
	P1  uuid.UUID       `json:"p1"`
	P2  int32           `json:"p2"`
	P3  int32           `json:"p3"`
	P4  int64           `json:"p4"`
	P5  int32           `json:"p5"`
	P6  int32           `json:"p6"`
	P7  sql.NullInt64   `json:"p7"`
	P8  sql.NullInt64   `json:"p8"`
	P9  uuid.UUID       `json:"p9"`
	P10 int32           `json:"p10"`
	P11 string          `json:"p11"`
	P12 string          `json:"p12"`
	P13 string          `json:"p13"`
	P14 json.RawMessage `json:"p14"`
}

type FHFlightInsertRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FHFlightInsert(ctx context.Context, arg FHFlightInsertParams) (FHFlightInsertRow, error) {
	row := q.db.QueryRowContext(ctx, fHFlightInsert,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
		arg.P11,
		arg.P12,
		arg.P13,
		arg.P14,
	)
	var i FHFlightInsertRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const fHFlightLanding = `-- name: FHFlightLanding :many
SELECT to_jsonb(r) FROM (
select 1 from device_external_identities
        where project_id=$1 and adapter_id=$2 and device_id=$3
) r
`

type FHFlightLandingParams struct {
	P1 int32         `json:"p1"`
	P2 int64         `json:"p2"`
	P3 sql.NullInt32 `json:"p3"`
}

func (q *Queries) FHFlightLanding(ctx context.Context, arg FHFlightLandingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHFlightLanding, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHFlightRead = `-- name: FHFlightRead :many
SELECT to_jsonb(r) FROM (
select id::text,task_run_id as "taskRunId",action_kind as action,status,
      attempt_count as "attemptCount",reconciliation_count as "reconciliationCount",
      last_error_code as "lastErrorCode",accepted_at as "acceptedAt",reconciled_at as "reconciledAt",
      unknown_at as "unknownAt",completed_at as "completedAt",created_at as "createdAt"
    from connector_action_jobs where id=$1::uuid and project_id=$2 and connector_instance_id=$3
) r
`

type FHFlightReadParams struct {
	P1 uuid.UUID `json:"p1"`
	P2 int32     `json:"p2"`
	P3 int64     `json:"p3"`
}

func (q *Queries) FHFlightRead(ctx context.Context, arg FHFlightReadParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHFlightRead, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
