// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_geospatial_actions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const fHGeospatialAuthorize = `-- name: FHGeospatialAuthorize :many
SELECT to_jsonb(r) FROM (
select $1::int as "teamId",member.role,
      (member.role in('owner','admin') or exists(select 1 from project_permissions permission
        where permission.project_id=adapter.project_id and permission.team_id=adapter.team_id
          and permission.user_id=member.user_id and permission.permission='mission:operate')) as "hasOperatePermission",
      adapter.project_id as "connectorProjectId",adapter.team_id as "connectorTeamId",adapter.status as "connectorStatus",
      coalesce(flags.flighthub_action_flags_json @> jsonb_build_object($2::text,true),false) as "actionEnabled",
      exists(select 1 from connector_capability_snapshots capability
        where capability.project_id=adapter.project_id and capability.connector_instance_id=adapter.id
          and capability.capability_code=$3 and capability.status='supported'
		  and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
		  and capability.region='cn' and capability.deployment='cn-public-cloud'
          and capability.evidence_level='field-write' and (capability.expires_at is null or capability.expires_at>now())
          and capability.device_model is null and capability.firmware_version is null) as "capabilityFieldVerified",
      target.project_id as "targetProjectId",target.connector_instance_id as "targetConnectorId",
      target.resource_kind as "targetKind",target.status as "targetStatus",target.remote_version as "targetRemoteVersion"
     from device_adapters adapter
     join team_members member on member.team_id=adapter.team_id and member.user_id=$4
     left join project_feature_flags flags on flags.project_id=adapter.project_id
     left join connector_remote_resources target on target.id=$5 and target.project_id=adapter.project_id
       and target.connector_instance_id=adapter.id
     where adapter.id=$6 and adapter.project_id=$7 and adapter.team_id=$1
) r
`

type FHGeospatialAuthorizeParams struct {
	P3 int32  `json:"p3"`
	P7 string `json:"p7"`
	P6 string `json:"p6"`
	P4 int32  `json:"p4"`
	P5 int64  `json:"p5"`
	P2 int64  `json:"p2"`
	P1 int32  `json:"p1"`
}

func (q *Queries) FHGeospatialAuthorize(ctx context.Context, arg FHGeospatialAuthorizeParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHGeospatialAuthorize,
		arg.P3,
		arg.P7,
		arg.P6,
		arg.P4,
		arg.P5,
		arg.P2,
		arg.P1,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHGeospatialEnqueue = `-- name: FHGeospatialEnqueue :exec
insert into outbox_events(project_id,team_id,event_id,event_type,aggregate_type,aggregate_id,payload_json,max_attempts)
       values($1,$2,$3,'flighthub.geospatial_action.requested','connector_geospatial_action_job',$4,$5,8)
       on conflict(event_id) do nothing
`

type FHGeospatialEnqueueParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
	P4 sql.NullString  `json:"p4"`
	P5 json.RawMessage `json:"p5"`
}

func (q *Queries) FHGeospatialEnqueue(ctx context.Context, arg FHGeospatialEnqueueParams) error {
	_, err := q.db.ExecContext(ctx, fHGeospatialEnqueue,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
	)
	return err
}

const fHGeospatialExisting = `-- name: FHGeospatialExisting :many
SELECT to_jsonb(r) FROM (
select id::text,status,request_digest as "requestDigest",target_resource_id as "targetResourceId",
          expected_remote_version as "expectedRemoteVersion",requested_by_user_id as "requestedByUserId"
         from connector_geospatial_action_jobs
         where project_id=$1 and connector_instance_id=$2 and action_kind=$3 and idempotency_key=$4
) r
`

type FHGeospatialExistingParams struct {
	P1 int32  `json:"p1"`
	P2 int64  `json:"p2"`
	P3 string `json:"p3"`
	P4 string `json:"p4"`
}

func (q *Queries) FHGeospatialExisting(ctx context.Context, arg FHGeospatialExistingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHGeospatialExisting,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHGeospatialInsert = `-- name: FHGeospatialInsert :one
insert into connector_geospatial_action_jobs(
        id,project_id,team_id,connector_instance_id,target_resource_id,requested_by_user_id,
        action_kind,capability_code,feature_flag,idempotency_key,expected_remote_version,request_digest,request_envelope_json
      ) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
      on conflict do nothing returning id::text,status
`

type FHGeospatialInsertParams struct {
	P1  uuid.UUID       `json:"p1"`
	P2  int32           `json:"p2"`
	P3  int32           `json:"p3"`
	P4  int64           `json:"p4"`
	P5  sql.NullInt64   `json:"p5"`
	P6  int32           `json:"p6"`
	P7  string          `json:"p7"`
	P8  string          `json:"p8"`
	P9  string          `json:"p9"`
	P10 string          `json:"p10"`
	P11 sql.NullString  `json:"p11"`
	P12 string          `json:"p12"`
	P13 json.RawMessage `json:"p13"`
}

type FHGeospatialInsertRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FHGeospatialInsert(ctx context.Context, arg FHGeospatialInsertParams) (FHGeospatialInsertRow, error) {
	row := q.db.QueryRowContext(ctx, fHGeospatialInsert,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
		arg.P11,
		arg.P12,
		arg.P13,
	)
	var i FHGeospatialInsertRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const fHGeospatialRead = `-- name: FHGeospatialRead :many
SELECT to_jsonb(r) FROM (
select id::text,action_kind as action,capability_code as "capabilityCode",target_resource_id as "targetResourceId",
      expected_remote_version as "expectedRemoteVersion",status,attempt_count as "attemptCount",last_error_code as "lastErrorCode",
      result_json as result,attempted_at as "attemptedAt",unknown_at as "unknownAt",completed_at as "completedAt",
      created_at as "createdAt",updated_at as "updatedAt"
     from connector_geospatial_action_jobs where id=$1::uuid and project_id=$2 and connector_instance_id=$3
) r
`

type FHGeospatialReadParams struct {
	P1 uuid.UUID `json:"p1"`
	P2 int32     `json:"p2"`
	P3 int64     `json:"p3"`
}

func (q *Queries) FHGeospatialRead(ctx context.Context, arg FHGeospatialReadParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHGeospatialRead, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
