// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_live_actions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const fHLiveAuthorize = `-- name: FHLiveAuthorize :many
SELECT to_jsonb(r) FROM (
select $1::int as "teamId",member.role,
      (member.role in('owner','admin') or exists(select 1 from project_permissions permission
        where permission.project_id=adapter.project_id and permission.team_id=adapter.team_id
          and permission.user_id=member.user_id and permission.permission='mission:operate')) as "hasOperatePermission",
      adapter.project_id as "connectorProjectId",adapter.team_id as "connectorTeamId",adapter.status as "connectorStatus",
      coalesce(flags.flighthub_action_flags_json @> jsonb_build_object($2::text,true),false) as "actionEnabled",
      exists(select 1 from connector_capability_snapshots capability
        where capability.project_id=adapter.project_id and capability.connector_instance_id=adapter.id
          and capability.capability_code=$3 and capability.status='supported'
		  and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
		  and capability.region='cn' and capability.deployment='cn-public-cloud'
          and capability.evidence_level='field-write' and (capability.expires_at is null or capability.expires_at>now())
          and (($4='live-quality-set' and capability.device_model=device.device_model
                and capability.firmware_version=device.firmware_version)
            or ($4<>'live-quality-set' and capability.device_model is null and capability.firmware_version is null))) as "capabilityFieldVerified",
      device.project_id as "deviceProjectId",identity.id is not null as "deviceConnectorIdentityPresent",
      target.project_id as "targetProjectId",target.connector_instance_id as "targetConnectorId",
      target.resource_kind as "targetKind",target.status as "targetStatus"
     from device_adapters adapter
     join team_members member on member.team_id=adapter.team_id and member.user_id=$5
     left join project_feature_flags flags on flags.project_id=adapter.project_id
     left join devices device on device.id=$6 and device.project_id=adapter.project_id
     left join device_external_identities identity on identity.project_id=adapter.project_id and identity.adapter_id=adapter.id
       and identity.device_id=device.id
     left join connector_remote_resources target on target.id=$7 and target.project_id=adapter.project_id
     where adapter.id=$8 and adapter.project_id=$9 and adapter.team_id=$1
) r
`

type FHLiveAuthorizeParams struct {
	P3 int32       `json:"p3"`
	P7 string      `json:"p7"`
	P6 string      `json:"p6"`
	P9 interface{} `json:"p9"`
	P4 int32       `json:"p4"`
	P5 int32       `json:"p5"`
	P8 int64       `json:"p8"`
	P2 int64       `json:"p2"`
	P1 int32       `json:"p1"`
}

func (q *Queries) FHLiveAuthorize(ctx context.Context, arg FHLiveAuthorizeParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHLiveAuthorize,
		arg.P3,
		arg.P7,
		arg.P6,
		arg.P9,
		arg.P4,
		arg.P5,
		arg.P8,
		arg.P2,
		arg.P1,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHLiveEnqueue = `-- name: FHLiveEnqueue :exec
insert into outbox_events(project_id,team_id,event_id,event_type,aggregate_type,aggregate_id,payload_json,max_attempts)
       values($1,$2,$3,'flighthub.live_action.requested','connector_live_action_job',$4,$5,8)
       on conflict(event_id) do nothing
`

type FHLiveEnqueueParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
	P4 sql.NullString  `json:"p4"`
	P5 json.RawMessage `json:"p5"`
}

func (q *Queries) FHLiveEnqueue(ctx context.Context, arg FHLiveEnqueueParams) error {
	_, err := q.db.ExecContext(ctx, fHLiveEnqueue,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
	)
	return err
}

const fHLiveExisting = `-- name: FHLiveExisting :many
SELECT to_jsonb(r) FROM (
select id::text,status,request_digest as "requestDigest",device_id as "deviceId",
          target_resource_id as "targetResourceId",requested_by_user_id as "requestedByUserId"
         from connector_live_action_jobs
         where project_id=$1 and connector_instance_id=$2 and action_kind=$3 and idempotency_key=$4
) r
`

type FHLiveExistingParams struct {
	P1 int32  `json:"p1"`
	P2 int64  `json:"p2"`
	P3 string `json:"p3"`
	P4 string `json:"p4"`
}

func (q *Queries) FHLiveExisting(ctx context.Context, arg FHLiveExistingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHLiveExisting,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHLiveInsert = `-- name: FHLiveInsert :one
insert into connector_live_action_jobs(
        id,project_id,team_id,connector_instance_id,device_id,target_resource_id,requested_by_user_id,
        action_kind,capability_code,feature_flag,idempotency_key,request_digest,request_envelope_json
      ) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
      on conflict(project_id,connector_instance_id,action_kind,idempotency_key) do nothing returning id::text,status
`

type FHLiveInsertParams struct {
	P1  uuid.UUID       `json:"p1"`
	P2  int32           `json:"p2"`
	P3  int32           `json:"p3"`
	P4  int64           `json:"p4"`
	P5  sql.NullInt32   `json:"p5"`
	P6  sql.NullInt64   `json:"p6"`
	P7  int32           `json:"p7"`
	P8  string          `json:"p8"`
	P9  string          `json:"p9"`
	P10 string          `json:"p10"`
	P11 string          `json:"p11"`
	P12 string          `json:"p12"`
	P13 json.RawMessage `json:"p13"`
}

type FHLiveInsertRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FHLiveInsert(ctx context.Context, arg FHLiveInsertParams) (FHLiveInsertRow, error) {
	row := q.db.QueryRowContext(ctx, fHLiveInsert,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
		arg.P11,
		arg.P12,
		arg.P13,
	)
	var i FHLiveInsertRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const fHLiveRead = `-- name: FHLiveRead :many
SELECT to_jsonb(r) FROM (
select id::text,action_kind as action,capability_code as "capabilityCode",status,attempt_count as "attemptCount",
      last_error_code as "lastErrorCode",result_json as result,attempted_at as "attemptedAt",unknown_at as "unknownAt",
      completed_at as "completedAt",created_at as "createdAt",updated_at as "updatedAt"
     from connector_live_action_jobs where id=$1::uuid and project_id=$2 and connector_instance_id=$3
) r
`

type FHLiveReadParams struct {
	P1 uuid.UUID `json:"p1"`
	P2 int32     `json:"p2"`
	P3 int64     `json:"p3"`
}

func (q *Queries) FHLiveRead(ctx context.Context, arg FHLiveReadParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHLiveRead, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
