// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_lifecycle_main.sql

package sqlcgen

import (
	"context"
)

const fHExpireReadCapabilities = `-- name: FHExpireReadCapabilities :exec
update connector_capability_snapshots
set expires_at=case when verified_at<now() then now() else verified_at+interval '1 microsecond' end,updated_at=now()
where project_id=$1 and connector_instance_id=$2 and evidence_level='live-read'
`

type FHExpireReadCapabilitiesParams struct {
	ProjectID           int32 `json:"project_id"`
	ConnectorInstanceID int64 `json:"connector_instance_id"`
}

func (q *Queries) FHExpireReadCapabilities(ctx context.Context, arg FHExpireReadCapabilitiesParams) error {
	_, err := q.db.ExecContext(ctx, fHExpireReadCapabilities, arg.ProjectID, arg.ConnectorInstanceID)
	return err
}

const fHReconnect = `-- name: FHReconnect :exec
update device_adapters set status='connecting',lease_owner=null,lease_expires_at=null,
last_health_json='{}'::jsonb,last_checked_at=null,updated_at=now()
where id=$1 and project_id=$2 and status='disabled'
`

type FHReconnectParams struct {
	ID        int64 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) FHReconnect(ctx context.Context, arg FHReconnectParams) error {
	_, err := q.db.ExecContext(ctx, fHReconnect, arg.ID, arg.ProjectID)
	return err
}

const fHRestoreBindings = `-- name: FHRestoreBindings :execrows
update device_connector_bindings set status='active',unbound_at=null
where project_id=$1 and connector_instance_id=$2 and status='disabled'
`

type FHRestoreBindingsParams struct {
	ProjectID           int32 `json:"project_id"`
	ConnectorInstanceID int64 `json:"connector_instance_id"`
}

func (q *Queries) FHRestoreBindings(ctx context.Context, arg FHRestoreBindingsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, fHRestoreBindings, arg.ProjectID, arg.ConnectorInstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
