// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_member_actions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const fHMemberEnqueue = `-- name: FHMemberEnqueue :exec
insert into outbox_events(project_id,team_id,event_id,event_type,aggregate_type,aggregate_id,payload_json,max_attempts)
      values($1,$2,$3,'flighthub.management_write.requested','connector_management_write_job',$4,$5,8)
      on conflict(event_id) do nothing
`

type FHMemberEnqueueParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
	P4 sql.NullString  `json:"p4"`
	P5 json.RawMessage `json:"p5"`
}

func (q *Queries) FHMemberEnqueue(ctx context.Context, arg FHMemberEnqueueParams) error {
	_, err := q.db.ExecContext(ctx, fHMemberEnqueue,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
	)
	return err
}

const fHMemberExisting = `-- name: FHMemberExisting :many
SELECT to_jsonb(r) FROM (
select id::text,status,request_digest as "requestDigest",requested_by_user_id as "requestedByUserId"
          from connector_management_write_jobs where project_id=$1 and connector_instance_id=$2
            and action_kind='project-member-upsert' and idempotency_key=$3
) r
`

type FHMemberExistingParams struct {
	P1 int32  `json:"p1"`
	P2 int64  `json:"p2"`
	P3 string `json:"p3"`
}

func (q *Queries) FHMemberExisting(ctx context.Context, arg FHMemberExistingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHMemberExisting, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHMemberGrant = `-- name: FHMemberGrant :many
SELECT to_jsonb(r) FROM (
select 1 from project_permissions where project_id=$1 and team_id=$2
    and user_id=$3 and permission='organization:manage'
) r
`

type FHMemberGrantParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
	P3 int32 `json:"p3"`
}

func (q *Queries) FHMemberGrant(ctx context.Context, arg FHMemberGrantParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHMemberGrant, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHMemberInsert = `-- name: FHMemberInsert :one
insert into connector_management_write_jobs(
        id,project_id,team_id,connector_instance_id,requested_by_user_id,approval_request_id,action_kind,capability_code,
        feature_flag,idempotency_key,request_digest,request_envelope_json,preview_digest,preview_json)
      values($1,$2,$3,$4,$5,$6,'project-member-upsert',$7,$8,$9,$10,$11,$12,$13)
      on conflict(project_id,connector_instance_id,action_kind,idempotency_key) do nothing returning id::text,status
`

type FHMemberInsertParams struct {
	P1  uuid.UUID       `json:"p1"`
	P2  int32           `json:"p2"`
	P3  int32           `json:"p3"`
	P4  int64           `json:"p4"`
	P5  int32           `json:"p5"`
	P6  uuid.UUID       `json:"p6"`
	P7  string          `json:"p7"`
	P8  string          `json:"p8"`
	P9  string          `json:"p9"`
	P10 string          `json:"p10"`
	P11 json.RawMessage `json:"p11"`
	P12 string          `json:"p12"`
	P13 json.RawMessage `json:"p13"`
}

type FHMemberInsertRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FHMemberInsert(ctx context.Context, arg FHMemberInsertParams) (FHMemberInsertRow, error) {
	row := q.db.QueryRowContext(ctx, fHMemberInsert,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
		arg.P11,
		arg.P12,
		arg.P13,
	)
	var i FHMemberInsertRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const fHMemberRead = `-- name: FHMemberRead :many
SELECT to_jsonb(r) FROM (
select id::text,action_kind as action,capability_code as "capabilityCode",preview_digest as "previewDigest",
      status,attempt_count as "attemptCount",reconciliation_count as "reconciliationCount",last_error_code as "lastErrorCode",
      result_json as result,attempted_at as "attemptedAt",unknown_at as "unknownAt",completed_at as "completedAt",
      created_at as "createdAt",updated_at as "updatedAt"
    from connector_management_write_jobs where id=$1::uuid and project_id=$2 and connector_instance_id=$3
) r
`

type FHMemberReadParams struct {
	P1 uuid.UUID `json:"p1"`
	P2 int32     `json:"p2"`
	P3 int64     `json:"p3"`
}

func (q *Queries) FHMemberRead(ctx context.Context, arg FHMemberReadParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHMemberRead, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHMemberTarget = `-- name: FHMemberTarget :many
SELECT to_jsonb(r) FROM (
select project.team_id::int as "teamId",
      (member.role='owner' or exists(select 1 from project_permissions permission where permission.project_id=project.id
        and permission.team_id=project.team_id and permission.user_id=$1 and permission.permission='organization:manage')) as "managementGranted",
      adapter.project_id::int as "connectorProjectId",adapter.team_id::int as "connectorTeamId",adapter.status as "connectorStatus",
      project.name as "projectName",coalesce(organization.summary_json->>'name','') as "organizationName",
      (select count(*)::int from connector_remote_resources target where target.project_id=adapter.project_id
        and target.connector_instance_id=adapter.id and target.resource_kind='organization-user' and target.status='active'
        and target.remote_id=any($2::text[])) as "targetCount",
      coalesce(flags.flighthub_action_flags_json @> jsonb_build_object($3::text,true),false) as "featureEnabled",
      exists(select 1 from connector_capability_snapshots capability where capability.project_id=adapter.project_id
        and capability.connector_instance_id=adapter.id and capability.capability_code=$4 and capability.status='supported'
		and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
		and capability.region='cn' and capability.deployment='cn-public-cloud'
        and capability.evidence_level='field-write' and capability.device_model is null and capability.firmware_version is null
        and (capability.expires_at is null or capability.expires_at>now())) as "capabilityVerified",
      approval.project_id as "approvalProjectId",approval.team_id as "approvalTeamId",approval.resource_type as "approvalResourceType",
      approval.resource_id as "approvalResourceId",approval.action as "approvalAction",approval.status as "approvalStatus",
      coalesce(approval.expires_at>now(),false) as "approvalUnexpired",approval.context_json->>'previewDigest' as "approvalPreviewDigest"
    from projects project join team_members member on member.team_id=project.team_id and member.user_id=$1
    join device_adapters adapter on adapter.project_id=project.id and adapter.team_id=project.team_id
    join connector_definitions definition on definition.id=adapter.connector_definition_id
      and definition.connector_key='dji.flighthub2' and definition.version='1.0.0'
    left join project_feature_flags flags on flags.project_id=project.id
    left join connector_remote_resources organization on organization.project_id=adapter.project_id
      and organization.connector_instance_id=adapter.id and organization.resource_kind='organization' and organization.status='active'
    left join approval_requests approval on approval.id=$5::uuid and approval.project_id=project.id
    where project.id=$6 and adapter.id=$7 and adapter.team_id=$8
) r
`

type FHMemberTargetParams struct {
	P4 int32         `json:"p4"`
	P5 []string      `json:"p5"`
	P6 string        `json:"p6"`
	P7 string        `json:"p7"`
	P8 uuid.NullUUID `json:"p8"`
	P1 int32         `json:"p1"`
	P2 int64         `json:"p2"`
	P3 int32         `json:"p3"`
}

func (q *Queries) FHMemberTarget(ctx context.Context, arg FHMemberTargetParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHMemberTarget,
		arg.P4,
		pq.Array(arg.P5),
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P1,
		arg.P2,
		arg.P3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
