// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_management_workspace.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const readFHManagementAccess = `-- name: ReadFHManagementAccess :many
SELECT to_jsonb(r) FROM (
select membership.role,project.team_id::int as "teamId",adapter.project_id::int as "connectorProjectId",
        adapter.team_id::int as "connectorTeamId",adapter.id::text as "connectorId",adapter.name as "connectorName",adapter.status as "connectorStatus",
        exists(select 1 from connector_capability_snapshots capability where capability.project_id=adapter.project_id
          and capability.connector_instance_id=adapter.id and capability.capability_code='organization.read'
		  and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
		  and capability.region='cn' and capability.deployment='cn-public-cloud'
		  and capability.status='supported' and capability.evidence_level in('live-read','field-write')
          and (capability.expires_at is null or capability.expires_at>now())) as "managementCapabilityVerified"
      from projects project join team_members membership on membership.team_id=project.team_id and membership.user_id=$1
      join device_adapters adapter on adapter.project_id=project.id and adapter.team_id=project.team_id
      join connector_definitions definition on definition.id=adapter.connector_definition_id and definition.connector_key='dji.flighthub2' and definition.version='1.0.0'
      where project.id=$2 and adapter.id=$3
) r
`

type ReadFHManagementAccessParams struct {
	UserID      int32 `json:"user_id"`
	ProjectID   int32 `json:"project_id"`
	ConnectorID int64 `json:"connector_id"`
}

func (q *Queries) ReadFHManagementAccess(ctx context.Context, arg ReadFHManagementAccessParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, readFHManagementAccess, arg.UserID, arg.ProjectID, arg.ConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readFHManagementResources = `-- name: ReadFHManagementResources :many
SELECT to_jsonb(r) FROM (
select id::text,connector_instance_id::text as "connectorId",resource_kind as kind,status,summary_json as summary,
        last_seen_at as "lastSeenAt",missing_at as "missingAt"
      from connector_remote_resources where project_id=$1 and team_id=$2 and connector_instance_id=$3
        and resource_kind in('organization','organization-user','organization-role','organization-permission','project-user','project-member')
      order by resource_kind,last_seen_at desc,id desc limit 2000
) r
`

type ReadFHManagementResourcesParams struct {
	ProjectID   int32 `json:"project_id"`
	TeamID      int32 `json:"team_id"`
	ConnectorID int64 `json:"connector_id"`
}

func (q *Queries) ReadFHManagementResources(ctx context.Context, arg ReadFHManagementResourcesParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, readFHManagementResources, arg.ProjectID, arg.TeamID, arg.ConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readFHManagementState = `-- name: ReadFHManagementState :many
SELECT to_jsonb(r) FROM (
select status,attempt_count::int as "attemptCount",last_error_code as "lastErrorCode",last_started_at as "lastStartedAt",
        last_succeeded_at as "lastSucceededAt",next_attempt_at as "nextAttemptAt"
      from connector_resource_sync_states where project_id=$1 and team_id=$2 and connector_instance_id=$3 and resource_kind='organization'
) r
`

type ReadFHManagementStateParams struct {
	ProjectID   int32 `json:"project_id"`
	TeamID      int32 `json:"team_id"`
	ConnectorID int64 `json:"connector_id"`
}

func (q *Queries) ReadFHManagementState(ctx context.Context, arg ReadFHManagementStateParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, readFHManagementState, arg.ProjectID, arg.TeamID, arg.ConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
