// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fh_model_actions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const fHModelEnqueue = `-- name: FHModelEnqueue :exec
insert into outbox_events(project_id,team_id,event_id,event_type,aggregate_type,aggregate_id,payload_json,max_attempts)
      values($1,$2,$3,'flighthub.model_delete.requested','connector_model_delete_job',$4,$5,8)
      on conflict(event_id) do nothing
`

type FHModelEnqueueParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
	P4 sql.NullString  `json:"p4"`
	P5 json.RawMessage `json:"p5"`
}

func (q *Queries) FHModelEnqueue(ctx context.Context, arg FHModelEnqueueParams) error {
	_, err := q.db.ExecContext(ctx, fHModelEnqueue,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
	)
	return err
}

const fHModelExisting = `-- name: FHModelExisting :many
SELECT to_jsonb(r) FROM (
select id::text,status,request_digest as "requestDigest",
          requested_by_user_id as "requestedByUserId" from connector_model_delete_jobs
         where project_id=$1 and connector_instance_id=$2 and action_kind=$3 and idempotency_key=$4
) r
`

type FHModelExistingParams struct {
	P1 int32  `json:"p1"`
	P2 int64  `json:"p2"`
	P3 string `json:"p3"`
	P4 string `json:"p4"`
}

func (q *Queries) FHModelExisting(ctx context.Context, arg FHModelExistingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHModelExisting,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHModelGate = `-- name: FHModelGate :many
SELECT to_jsonb(r) FROM (
select
      coalesce(flags.flighthub_action_flags_json @> jsonb_build_object($1::text,true),false) as "actionEnabled",
      exists(select 1 from connector_capability_snapshots capability
        where capability.project_id=adapter.project_id and capability.connector_instance_id=adapter.id
          and capability.capability_code=$2 and capability.status='supported'
		  and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
		  and capability.region='cn' and capability.deployment='cn-public-cloud'
          and capability.evidence_level='field-write' and (capability.expires_at is null or capability.expires_at>now())
          and capability.device_model is null and capability.firmware_version is null) as "capabilityFieldVerified",
      approval.project_id as "approvalProjectId",approval.team_id as "approvalTeamId",
      approval.resource_type as "approvalResourceType",approval.resource_id as "approvalResourceId",
      approval.action as "approvalAction",approval.status as "approvalStatus",
      coalesce(approval.expires_at>now(),false) as "approvalUnexpired",
      approval.context_json->>'previewDigest' as "approvalPreviewDigest",
      approval.context_json->>'expectedRemoteVersion' as "approvalRemoteVersion"
     from device_adapters adapter
     left join project_feature_flags flags on flags.project_id=adapter.project_id
     left join approval_requests approval on approval.id=$3::uuid and approval.project_id=adapter.project_id
     where adapter.id=$4 and adapter.project_id=$5
) r
`

type FHModelGateParams struct {
	P4 string    `json:"p4"`
	P3 string    `json:"p3"`
	P5 uuid.UUID `json:"p5"`
	P2 int64     `json:"p2"`
	P1 int32     `json:"p1"`
}

func (q *Queries) FHModelGate(ctx context.Context, arg FHModelGateParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHModelGate,
		arg.P4,
		arg.P3,
		arg.P5,
		arg.P2,
		arg.P1,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHModelInsert = `-- name: FHModelInsert :one
insert into connector_model_delete_jobs(id,project_id,team_id,connector_instance_id,target_resource_id,
        approval_request_id,requested_by_user_id,action_kind,capability_code,feature_flag,idempotency_key,
        expected_remote_version,preview_digest,request_digest,request_envelope_json)
       values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
       on conflict do nothing returning id::text,status
`

type FHModelInsertParams struct {
	P1  uuid.UUID       `json:"p1"`
	P2  int32           `json:"p2"`
	P3  int32           `json:"p3"`
	P4  int64           `json:"p4"`
	P5  int64           `json:"p5"`
	P6  uuid.UUID       `json:"p6"`
	P7  int32           `json:"p7"`
	P8  string          `json:"p8"`
	P9  string          `json:"p9"`
	P10 string          `json:"p10"`
	P11 string          `json:"p11"`
	P12 string          `json:"p12"`
	P13 string          `json:"p13"`
	P14 string          `json:"p14"`
	P15 json.RawMessage `json:"p15"`
}

type FHModelInsertRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) FHModelInsert(ctx context.Context, arg FHModelInsertParams) (FHModelInsertRow, error) {
	row := q.db.QueryRowContext(ctx, fHModelInsert,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
		arg.P11,
		arg.P12,
		arg.P13,
		arg.P14,
		arg.P15,
	)
	var i FHModelInsertRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const fHModelRead = `-- name: FHModelRead :many
SELECT to_jsonb(r) FROM (
select id::text,action_kind as action,capability_code as "capabilityCode",
    target_resource_id as "targetResourceId",approval_request_id::text as "approvalRequestId",
    expected_remote_version as "expectedRemoteVersion",preview_digest as "previewDigest",status,
    attempt_count as "attemptCount",reconciliation_count as "reconciliationCount",last_error_code as "lastErrorCode",
    result_json as result,attempted_at as "attemptedAt",unknown_at as "unknownAt",completed_at as "completedAt",
    created_at as "createdAt",updated_at as "updatedAt"
   from connector_model_delete_jobs where id=$1::uuid and project_id=$2 and connector_instance_id=$3
) r
`

type FHModelReadParams struct {
	P1 uuid.UUID `json:"p1"`
	P2 int32     `json:"p2"`
	P3 int64     `json:"p3"`
}

func (q *Queries) FHModelRead(ctx context.Context, arg FHModelReadParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHModelRead, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fHModelTarget = `-- name: FHModelTarget :many
SELECT to_jsonb(r) FROM (
select $1::int as "teamId",member.role,adapter.project_id as "connectorProjectId",
      adapter.team_id as "connectorTeamId",adapter.status as "connectorStatus",
      target.project_id as "targetProjectId",target.connector_instance_id as "targetConnectorId",
      target.resource_kind as "targetKind",target.status as "targetStatus",target.remote_version as "targetRemoteVersion",
      case when target.canonical_target_type='asset' then target.canonical_target_id end as "assetId",
      asset.status as "assetStatus",
      coalesce((select count(*)::int from connector_asset_access_refs ref
        where ref.project_id=adapter.project_id and ref.connector_instance_id=adapter.id
          and ref.remote_resource_id=target.id),0) as "dependentReferenceCount"
     from device_adapters adapter
     join team_members member on member.team_id=adapter.team_id and member.user_id=$2
     left join connector_remote_resources target on target.id=$3 and target.project_id=adapter.project_id
       and target.connector_instance_id=adapter.id
     left join assets asset on target.canonical_target_type='asset' and asset.project_id=target.project_id
       and asset.id::text=target.canonical_target_id
     where adapter.id=$4 and adapter.project_id=$5 and adapter.team_id=$1
) r
`

type FHModelTargetParams struct {
	P3 int32 `json:"p3"`
	P4 int32 `json:"p4"`
	P5 int64 `json:"p5"`
	P2 int64 `json:"p2"`
	P1 int32 `json:"p1"`
}

func (q *Queries) FHModelTarget(ctx context.Context, arg FHModelTargetParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, fHModelTarget,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P2,
		arg.P1,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
