// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flighthub_writes.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const cancelFlightHubSyncQueue = `-- name: CancelFlightHubSyncQueue :exec
UPDATE outbox_events SET status='dead',last_error='CONNECTOR_DISCONNECTED',completed_at=now(),locked_by=null,locked_until=null
WHERE project_id=$1 AND event_type='connector.sync.requested' AND payload_json->>'connectorInstanceId'=$2::text AND status IN ('pending','processing')
`

type CancelFlightHubSyncQueueParams struct {
	ProjectID int32  `json:"project_id"`
	Column2   string `json:"column_2"`
}

func (q *Queries) CancelFlightHubSyncQueue(ctx context.Context, arg CancelFlightHubSyncQueueParams) error {
	_, err := q.db.ExecContext(ctx, cancelFlightHubSyncQueue, arg.ProjectID, arg.Column2)
	return err
}

const cancelFlightHubSyncRuns = `-- name: CancelFlightHubSyncRuns :exec
UPDATE connector_sync_runs SET status='cancelled',error_code='CONNECTOR_DISCONNECTED',started_at=coalesce(started_at,now()),finished_at=coalesce(finished_at,now())
WHERE project_id=$1 AND connector_instance_id=$2 AND status IN ('pending','running')
`

type CancelFlightHubSyncRunsParams struct {
	ProjectID           int32 `json:"project_id"`
	ConnectorInstanceID int64 `json:"connector_instance_id"`
}

func (q *Queries) CancelFlightHubSyncRuns(ctx context.Context, arg CancelFlightHubSyncRunsParams) error {
	_, err := q.db.ExecContext(ctx, cancelFlightHubSyncRuns, arg.ProjectID, arg.ConnectorInstanceID)
	return err
}

const createFlightHubConnector = `-- name: CreateFlightHubConnector :one
INSERT INTO device_adapters(project_id,team_id,name,adapter_type,connector_definition_id,vendor,protocol_version,status,config_json,capabilities_json,onboarding_policy,discovery_scope_json,external_scope_key)
SELECT $1,$2,$3,'dji-flighthub2',definition.id,'dji','flighthub-openapi-v2','connecting','{"region":"cn","readOnly":true}','{"inventoryRead":true,"stateRead":true}','review',$4::jsonb,$5::text
FROM connector_definitions definition WHERE connector_key='dji.flighthub2' AND version='1.0.0' AND status='active'
RETURNING id,status,created_at
`

type CreateFlightHubConnectorParams struct {
	ProjectID      int32           `json:"project_id"`
	TeamID         int32           `json:"team_id"`
	Name           string          `json:"name"`
	DiscoveryScope json.RawMessage `json:"discovery_scope"`
	ExternalScope  string          `json:"external_scope"`
}

type CreateFlightHubConnectorRow struct {
	ID        int64     `json:"id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateFlightHubConnector(ctx context.Context, arg CreateFlightHubConnectorParams) (CreateFlightHubConnectorRow, error) {
	row := q.db.QueryRowContext(ctx, createFlightHubConnector,
		arg.ProjectID,
		arg.TeamID,
		arg.Name,
		arg.DiscoveryScope,
		arg.ExternalScope,
	)
	var i CreateFlightHubConnectorRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const disableFlightHubBindings = `-- name: DisableFlightHubBindings :exec
UPDATE device_connector_bindings SET status='disabled',unbound_at=coalesce(unbound_at,now())
WHERE project_id=$1 AND connector_instance_id=$2 AND status<>'disabled'
`

type DisableFlightHubBindingsParams struct {
	ProjectID           int32 `json:"project_id"`
	ConnectorInstanceID int64 `json:"connector_instance_id"`
}

func (q *Queries) DisableFlightHubBindings(ctx context.Context, arg DisableFlightHubBindingsParams) error {
	_, err := q.db.ExecContext(ctx, disableFlightHubBindings, arg.ProjectID, arg.ConnectorInstanceID)
	return err
}

const disableFlightHubConnector = `-- name: DisableFlightHubConnector :execrows
UPDATE device_adapters SET status='disabled',lease_owner=null,lease_expires_at=null,
last_health_json='{"ok":false,"code":"CONNECTOR_DISCONNECTED"}',updated_at=now() WHERE id=$1 AND project_id=$2
`

type DisableFlightHubConnectorParams struct {
	ID        int64 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) DisableFlightHubConnector(ctx context.Context, arg DisableFlightHubConnectorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, disableFlightHubConnector, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findFlightHubConnector = `-- name: FindFlightHubConnector :one
SELECT adapter.id,adapter.status,coalesce(adapter.discovery_scope_json->>'projectUuid','')::text AS project_uuid,
coalesce(adapter.discovery_scope_json->>'projectName','')::text AS project_name
FROM device_adapters adapter JOIN connector_definitions definition ON definition.id=adapter.connector_definition_id
WHERE adapter.id=$1 AND adapter.project_id=$2 AND definition.connector_key='dji.flighthub2' AND definition.version='1.0.0'
`

type FindFlightHubConnectorParams struct {
	ID        int64 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

type FindFlightHubConnectorRow struct {
	ID          int64  `json:"id"`
	Status      string `json:"status"`
	ProjectUuid string `json:"project_uuid"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) FindFlightHubConnector(ctx context.Context, arg FindFlightHubConnectorParams) (FindFlightHubConnectorRow, error) {
	row := q.db.QueryRowContext(ctx, findFlightHubConnector, arg.ID, arg.ProjectID)
	var i FindFlightHubConnectorRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ProjectUuid,
		&i.ProjectName,
	)
	return i, err
}

const findQueuedFlightHubSync = `-- name: FindQueuedFlightHubSync :one
SELECT event_id FROM outbox_events WHERE project_id=$1 AND event_type='connector.sync.requested'
AND payload_json->>'connectorInstanceId'=$2::text AND status IN ('pending','processing') ORDER BY id LIMIT 1
`

type FindQueuedFlightHubSyncParams struct {
	ProjectID int32  `json:"project_id"`
	Column2   string `json:"column_2"`
}

func (q *Queries) FindQueuedFlightHubSync(ctx context.Context, arg FindQueuedFlightHubSyncParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findQueuedFlightHubSync, arg.ProjectID, arg.Column2)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}

const lockFlightHubConnector = `-- name: LockFlightHubConnector :one
SELECT adapter.id,adapter.status,coalesce(adapter.discovery_scope_json->>'projectUuid','')::text AS project_uuid,
coalesce(adapter.discovery_scope_json->>'projectName','')::text AS project_name
FROM device_adapters adapter JOIN connector_definitions definition ON definition.id=adapter.connector_definition_id
WHERE adapter.id=$1 AND adapter.project_id=$2 AND definition.connector_key='dji.flighthub2' AND definition.version='1.0.0'
FOR UPDATE OF adapter
`

type LockFlightHubConnectorParams struct {
	ID        int64 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

type LockFlightHubConnectorRow struct {
	ID          int64  `json:"id"`
	Status      string `json:"status"`
	ProjectUuid string `json:"project_uuid"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) LockFlightHubConnector(ctx context.Context, arg LockFlightHubConnectorParams) (LockFlightHubConnectorRow, error) {
	row := q.db.QueryRowContext(ctx, lockFlightHubConnector, arg.ID, arg.ProjectID)
	var i LockFlightHubConnectorRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ProjectUuid,
		&i.ProjectName,
	)
	return i, err
}

const lockFlightHubSyncQueue = `-- name: LockFlightHubSyncQueue :exec
SELECT pg_advisory_xact_lock(hashtext($1::text))
`

func (q *Queries) LockFlightHubSyncQueue(ctx context.Context, lockKey string) error {
	_, err := q.db.ExecContext(ctx, lockFlightHubSyncQueue, lockKey)
	return err
}

const updateFlightHubCredentials = `-- name: UpdateFlightHubCredentials :execrows
UPDATE device_adapters SET credential_envelope_json=$3::jsonb,status='connecting',last_health_json='{}',last_checked_at=now(),updated_at=now()
WHERE id=$1 AND project_id=$2
`

type UpdateFlightHubCredentialsParams struct {
	ID        int64           `json:"id"`
	ProjectID int32           `json:"project_id"`
	Column3   json.RawMessage `json:"column_3"`
}

func (q *Queries) UpdateFlightHubCredentials(ctx context.Context, arg UpdateFlightHubCredentialsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFlightHubCredentials, arg.ID, arg.ProjectID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
