// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: http_sessions.sql

package sqlcgen

import (
	"context"
	"time"
)

const commitHTTPSession = `-- name: CommitHTTPSession :exec
INSERT INTO sessions(token, data, expiry) VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET data = EXCLUDED.data, expiry = EXCLUDED.expiry
`

type CommitHTTPSessionParams struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

func (q *Queries) CommitHTTPSession(ctx context.Context, arg CommitHTTPSessionParams) error {
	_, err := q.db.ExecContext(ctx, commitHTTPSession, arg.Token, arg.Data, arg.Expiry)
	return err
}

const deleteExpiredHTTPSessions = `-- name: DeleteExpiredHTTPSessions :exec
DELETE FROM sessions WHERE expiry < current_timestamp
`

func (q *Queries) DeleteExpiredHTTPSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredHTTPSessions)
	return err
}

const deleteHTTPSession = `-- name: DeleteHTTPSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteHTTPSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteHTTPSession, token)
	return err
}

const findHTTPSession = `-- name: FindHTTPSession :one
SELECT data FROM sessions WHERE token = $1 AND current_timestamp < expiry
`

func (q *Queries) FindHTTPSession(ctx context.Context, token string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, findHTTPSession, token)
	var data []byte
	err := row.Scan(&data)
	return data, err
}
