// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_feedback.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const feedbackEvent = `-- name: FeedbackEvent :exec
insert into issue_events(project_id,issue_id,event_type,body,metadata_json,actor_user_id,client_key)
      values($1,$2,$3,$4,$5,$6,$7)
`

type FeedbackEventParams struct {
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 string          `json:"p3"`
	P4 sql.NullString  `json:"p4"`
	P5 json.RawMessage `json:"p5"`
	P6 sql.NullInt32   `json:"p6"`
	P7 sql.NullString  `json:"p7"`
}

func (q *Queries) FeedbackEvent(ctx context.Context, arg FeedbackEventParams) error {
	_, err := q.db.ExecContext(ctx, feedbackEvent,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
	)
	return err
}

const feedbackEvidence = `-- name: FeedbackEvidence :many
SELECT to_jsonb(r) FROM (
select issue.project_id as "issueProjectId",issue.state_version as "issueVersion",detection.id::int as "detectionId",
      detection.label as "originalLabel",run.algorithm_definition_version_id::int as "algorithmDefinitionVersionId",
      issue.task_version_id::int as "taskVersionId",(
        select case when link.target_id~'^[0-9]+$' then link.target_id::bigint end from issue_links link
        where link.project_id=issue.project_id and link.issue_id=issue.id and link.link_type='task_step' order by link.id desc limit 1
      )::int as "taskRunStepId"
      from issues issue join issue_links detection_link on detection_link.project_id=issue.project_id
        and detection_link.issue_id=issue.id and detection_link.link_type='detection'
      join detections detection on detection.project_id=detection_link.project_id
        and detection.id=case when detection_link.target_id~'^[0-9]+$' then detection_link.target_id::bigint end
      join algorithm_runs run on run.id=detection.algorithm_run_id and run.project_id=detection.project_id
      where issue.project_id=$1 and issue.id=$2 and detection.id=$3 for update of issue
) r
`

type FeedbackEvidenceParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
	P3 int64 `json:"p3"`
}

func (q *Queries) FeedbackEvidence(ctx context.Context, arg FeedbackEvidenceParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, feedbackEvidence, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feedbackInsert = `-- name: FeedbackInsert :one
insert into issue_feedback(
      project_id,team_id,issue_id,detection_id,algorithm_definition_version_id,task_version_id,task_run_step_id,
      action,corrected_label,disposition,reason,client_key,evidence_snapshot_json,actor_user_id)
      values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning id,created_at as "createdAt"
`

type FeedbackInsertParams struct {
	P1  int32           `json:"p1"`
	P2  int32           `json:"p2"`
	P3  int32           `json:"p3"`
	P4  int64           `json:"p4"`
	P5  int64           `json:"p5"`
	P6  sql.NullInt64   `json:"p6"`
	P7  sql.NullInt64   `json:"p7"`
	P8  string          `json:"p8"`
	P9  sql.NullString  `json:"p9"`
	P10 sql.NullString  `json:"p10"`
	P11 string          `json:"p11"`
	P12 uuid.UUID       `json:"p12"`
	P13 json.RawMessage `json:"p13"`
	P14 int32           `json:"p14"`
}

type FeedbackInsertRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) FeedbackInsert(ctx context.Context, arg FeedbackInsertParams) (FeedbackInsertRow, error) {
	row := q.db.QueryRowContext(ctx, feedbackInsert,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
		arg.P11,
		arg.P12,
		arg.P13,
		arg.P14,
	)
	var i FeedbackInsertRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const feedbackReplay = `-- name: FeedbackReplay :many
SELECT to_jsonb(r) FROM (
select id,action,created_at as "createdAt" from issue_feedback
      where project_id=$1 and issue_id=$2 and client_key=$3
) r
`

type FeedbackReplayParams struct {
	P1 int32     `json:"p1"`
	P2 int32     `json:"p2"`
	P3 uuid.UUID `json:"p3"`
}

func (q *Queries) FeedbackReplay(ctx context.Context, arg FeedbackReplayParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, feedbackReplay, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feedbackUpdate = `-- name: FeedbackUpdate :exec
update issues set state_version=state_version+1,updated_at=now() where project_id=$1 and id=$2
`

type FeedbackUpdateParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
}

func (q *Queries) FeedbackUpdate(ctx context.Context, arg FeedbackUpdateParams) error {
	_, err := q.db.ExecContext(ctx, feedbackUpdate, arg.P1, arg.P2)
	return err
}
