// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_writes.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addIssueAssignee = `-- name: AddIssueAssignee :exec
INSERT INTO issue_assignees(project_id,team_id,issue_id,assignee_type,user_id,agent_id,assigned_by_user_id)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type AddIssueAssigneeParams struct {
	ProjectID    int32         `json:"project_id"`
	TeamID       int32         `json:"team_id"`
	IssueID      int32         `json:"issue_id"`
	AssigneeType string        `json:"assignee_type"`
	UserID       sql.NullInt32 `json:"user_id"`
	AgentID      sql.NullInt32 `json:"agent_id"`
	ActorUserID  int32         `json:"actor_user_id"`
}

func (q *Queries) AddIssueAssignee(ctx context.Context, arg AddIssueAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, addIssueAssignee,
		arg.ProjectID,
		arg.TeamID,
		arg.IssueID,
		arg.AssigneeType,
		arg.UserID,
		arg.AgentID,
		arg.ActorUserID,
	)
	return err
}

const createIssueCopilotSession = `-- name: CreateIssueCopilotSession :one
INSERT INTO agent_sessions(project_id,agent_id,issue_id,started_by_user_id,summary)
VALUES($1,$2,$3,$4,$5) RETURNING id
`

type CreateIssueCopilotSessionParams struct {
	ProjectID       int32          `json:"project_id"`
	AgentID         sql.NullInt32  `json:"agent_id"`
	IssueID         sql.NullInt32  `json:"issue_id"`
	StartedByUserID sql.NullInt32  `json:"started_by_user_id"`
	Summary         sql.NullString `json:"summary"`
}

func (q *Queries) CreateIssueCopilotSession(ctx context.Context, arg CreateIssueCopilotSessionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createIssueCopilotSession,
		arg.ProjectID,
		arg.AgentID,
		arg.IssueID,
		arg.StartedByUserID,
		arg.Summary,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const ensureIssueCopilot = `-- name: EnsureIssueCopilot :one
INSERT INTO agents(project_id,name,description,status,config_json)
VALUES($1,'Copilot','项目级 AI 助手，可通过案件评论提及或负责人指派触发。','active','{"kind":"copilot","builtIn":true}'::jsonb)
ON CONFLICT(project_id,(config_json->>'kind')) WHERE config_json->>'kind'='copilot'
DO UPDATE SET status='active' RETURNING id
`

func (q *Queries) EnsureIssueCopilot(ctx context.Context, projectID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, ensureIssueCopilot, projectID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertIssueActivity = `-- name: InsertIssueActivity :one
INSERT INTO issue_events(project_id,issue_id,event_type,body,metadata_json,actor_user_id,client_key)
VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id
`

type InsertIssueActivityParams struct {
	ProjectID   int32           `json:"project_id"`
	IssueID     int32           `json:"issue_id"`
	EventType   string          `json:"event_type"`
	Body        sql.NullString  `json:"body"`
	Metadata    json.RawMessage `json:"metadata"`
	ActorUserID sql.NullInt32   `json:"actor_user_id"`
	ClientKey   sql.NullString  `json:"client_key"`
}

func (q *Queries) InsertIssueActivity(ctx context.Context, arg InsertIssueActivityParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertIssueActivity,
		arg.ProjectID,
		arg.IssueID,
		arg.EventType,
		arg.Body,
		arg.Metadata,
		arg.ActorUserID,
		arg.ClientKey,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const issueAssigneeActive = `-- name: IssueAssigneeActive :one
SELECT EXISTS(SELECT 1 FROM issue_assignees WHERE project_id=$1 AND issue_id=$2
 AND (user_id=$3 OR agent_id=$4) AND active)::boolean
`

type IssueAssigneeActiveParams struct {
	ProjectID int32         `json:"project_id"`
	IssueID   int32         `json:"issue_id"`
	UserID    sql.NullInt32 `json:"user_id"`
	AgentID   sql.NullInt32 `json:"agent_id"`
}

func (q *Queries) IssueAssigneeActive(ctx context.Context, arg IssueAssigneeActiveParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, issueAssigneeActive,
		arg.ProjectID,
		arg.IssueID,
		arg.UserID,
		arg.AgentID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const issueMutationReplayed = `-- name: IssueMutationReplayed :one
SELECT EXISTS(SELECT 1 FROM issue_events WHERE project_id=$1 AND issue_id=$2 AND client_key=$3)::boolean
`

type IssueMutationReplayedParams struct {
	ProjectID int32          `json:"project_id"`
	IssueID   int32          `json:"issue_id"`
	ClientKey sql.NullString `json:"client_key"`
}

func (q *Queries) IssueMutationReplayed(ctx context.Context, arg IssueMutationReplayedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, issueMutationReplayed, arg.ProjectID, arg.IssueID, arg.ClientKey)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const lockIssueAssigneeAgent = `-- name: LockIssueAssigneeAgent :one
SELECT id,name,coalesce(config_json->>'kind','')::text AS kind FROM agents WHERE project_id=$1 AND id=$2 AND status='active' FOR SHARE
`

type LockIssueAssigneeAgentParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int32 `json:"id"`
}

type LockIssueAssigneeAgentRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) LockIssueAssigneeAgent(ctx context.Context, arg LockIssueAssigneeAgentParams) (LockIssueAssigneeAgentRow, error) {
	row := q.db.QueryRowContext(ctx, lockIssueAssigneeAgent, arg.ProjectID, arg.ID)
	var i LockIssueAssigneeAgentRow
	err := row.Scan(&i.ID, &i.Name, &i.Kind)
	return i, err
}

const lockIssueAssigneeUser = `-- name: LockIssueAssigneeUser :one
SELECT user_id FROM team_members WHERE team_id=$1 AND user_id=$2 FOR SHARE
`

type LockIssueAssigneeUserParams struct {
	TeamID int32 `json:"team_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) LockIssueAssigneeUser(ctx context.Context, arg LockIssueAssigneeUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockIssueAssigneeUser, arg.TeamID, arg.UserID)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const lockIssueMutation = `-- name: LockIssueMutation :one
SELECT state_version FROM issues WHERE project_id=$1 AND id=$2 FOR UPDATE
`

type LockIssueMutationParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int32 `json:"id"`
}

func (q *Queries) LockIssueMutation(ctx context.Context, arg LockIssueMutationParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockIssueMutation, arg.ProjectID, arg.ID)
	var state_version int32
	err := row.Scan(&state_version)
	return state_version, err
}

const queueIssueCopilot = `-- name: QueueIssueCopilot :one
INSERT INTO agent_tool_jobs(project_id,team_id,session_id,requested_by_user_id,issue_id,trigger_issue_event_id,trigger_type,idempotency_key,
 tool_name,required_permission,args_json,context_expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,
 'issue_copilot','agent:use',jsonb_build_object('issueId',$5::int,'triggerEventId',$6::int),now()+interval '24 hours')
ON CONFLICT(project_id,idempotency_key) WHERE idempotency_key IS NOT NULL DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING id
`

type QueueIssueCopilotParams struct {
	ProjectID      int32          `json:"project_id"`
	TeamID         int32          `json:"team_id"`
	SessionID      int32          `json:"session_id"`
	ActorUserID    int32          `json:"actor_user_id"`
	IssueID        sql.NullInt32  `json:"issue_id"`
	ActivityID     sql.NullInt32  `json:"activity_id"`
	TriggerType    sql.NullString `json:"trigger_type"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
}

func (q *Queries) QueueIssueCopilot(ctx context.Context, arg QueueIssueCopilotParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, queueIssueCopilot,
		arg.ProjectID,
		arg.TeamID,
		arg.SessionID,
		arg.ActorUserID,
		arg.IssueID,
		arg.ActivityID,
		arg.TriggerType,
		arg.IdempotencyKey,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const removeIssueAssignee = `-- name: RemoveIssueAssignee :exec
UPDATE issue_assignees SET active=false,removed_at=now() WHERE project_id=$1 AND issue_id=$2
 AND (user_id=$3 OR agent_id=$4) AND active
`

type RemoveIssueAssigneeParams struct {
	ProjectID int32         `json:"project_id"`
	IssueID   int32         `json:"issue_id"`
	UserID    sql.NullInt32 `json:"user_id"`
	AgentID   sql.NullInt32 `json:"agent_id"`
}

func (q *Queries) RemoveIssueAssignee(ctx context.Context, arg RemoveIssueAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, removeIssueAssignee,
		arg.ProjectID,
		arg.IssueID,
		arg.UserID,
		arg.AgentID,
	)
	return err
}

const updateIssueMutation = `-- name: UpdateIssueMutation :one
UPDATE issues SET status=coalesce($1::text,status),labels_json=coalesce($2::jsonb,labels_json),
 state_version=$3,updated_at=now(),
 closed_at=CASE WHEN $1::text='closed' THEN now() WHEN $1::text='open' THEN null ELSE closed_at END
WHERE project_id=$4 AND id=$5 AND state_version=$6
RETURNING state_version
`

type UpdateIssueMutationParams struct {
	Status          sql.NullString        `json:"status"`
	Labels          pqtype.NullRawMessage `json:"labels"`
	NextVersion     int32                 `json:"next_version"`
	ProjectID       int32                 `json:"project_id"`
	IssueID         int32                 `json:"issue_id"`
	ExpectedVersion int32                 `json:"expected_version"`
}

func (q *Queries) UpdateIssueMutation(ctx context.Context, arg UpdateIssueMutationParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateIssueMutation,
		arg.Status,
		arg.Labels,
		arg.NextVersion,
		arg.ProjectID,
		arg.IssueID,
		arg.ExpectedVersion,
	)
	var state_version int32
	err := row.Scan(&state_version)
	return state_version, err
}
