// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live_playback.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const authorizeFlightHubPlayback = `-- name: AuthorizeFlightHubPlayback :one
UPDATE live_streams SET last_playback_at=now(),
 playback_locator_expires_at=least(supplier_credential_expires_at,now()+interval '60 seconds'),updated_at=now()
 WHERE project_id=$1 AND id=$2 AND source_type='dji_flighthub'
 AND status IN ('starting','live','degraded') AND (status<>'starting' OR start_accepted_at IS NOT NULL)
 AND local_authorization_revoked_at IS NULL AND supplier_credential_expires_at>now()
 AND supplier_credential_envelope_json IS NOT NULL
 RETURNING supplier,supplier_protocol,supplier_adapter_version,supplier_credential_envelope_json,playback_locator_expires_at
`

type AuthorizeFlightHubPlaybackParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

type AuthorizeFlightHubPlaybackRow struct {
	Supplier                       sql.NullString        `json:"supplier"`
	SupplierProtocol               sql.NullString        `json:"supplier_protocol"`
	SupplierAdapterVersion         sql.NullString        `json:"supplier_adapter_version"`
	SupplierCredentialEnvelopeJson pqtype.NullRawMessage `json:"supplier_credential_envelope_json"`
	PlaybackLocatorExpiresAt       sql.NullTime          `json:"playback_locator_expires_at"`
}

func (q *Queries) AuthorizeFlightHubPlayback(ctx context.Context, arg AuthorizeFlightHubPlaybackParams) (AuthorizeFlightHubPlaybackRow, error) {
	row := q.db.QueryRowContext(ctx, authorizeFlightHubPlayback, arg.ProjectID, arg.ID)
	var i AuthorizeFlightHubPlaybackRow
	err := row.Scan(
		&i.Supplier,
		&i.SupplierProtocol,
		&i.SupplierAdapterVersion,
		&i.SupplierCredentialEnvelopeJson,
		&i.PlaybackLocatorExpiresAt,
	)
	return i, err
}

const lockLivePlayback = `-- name: LockLivePlayback :one
SELECT stream.id,stream.device_id,stream.stream_key,stream.source_type,stream.status,stream.playback_ref,stream.last_active_at,stream.status_reason,
 stream.start_accepted_at,stream.local_authorization_revoked_at,stream.supplier_credential_expires_at,
 device.device_type_id,coalesce(channel.capability_code,'camera.live')::text AS capability_code,
 coalesce(profile.media_playback_base_url,'')::text AS hls_base_url,coalesce(profile.config_json->>'webrtcPlaybackBaseUrl','')::text AS webrtc_base_url
FROM live_streams stream JOIN devices device ON device.id=stream.device_id AND device.project_id=stream.project_id
LEFT JOIN device_stream_channels channel ON channel.id=stream.stream_channel_id AND channel.project_id=stream.project_id
LEFT JOIN device_adapters adapter ON adapter.id=stream.adapter_id AND adapter.project_id=stream.project_id
LEFT JOIN device_network_profiles profile ON profile.id=adapter.network_profile_id AND profile.project_id=adapter.project_id
WHERE stream.project_id=$1 AND stream.id=$2 FOR UPDATE OF stream
`

type LockLivePlaybackParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

type LockLivePlaybackRow struct {
	ID                          int64          `json:"id"`
	DeviceID                    int32          `json:"device_id"`
	StreamKey                   string         `json:"stream_key"`
	SourceType                  string         `json:"source_type"`
	Status                      string         `json:"status"`
	PlaybackRef                 sql.NullString `json:"playback_ref"`
	LastActiveAt                sql.NullTime   `json:"last_active_at"`
	StatusReason                sql.NullString `json:"status_reason"`
	StartAcceptedAt             sql.NullTime   `json:"start_accepted_at"`
	LocalAuthorizationRevokedAt sql.NullTime   `json:"local_authorization_revoked_at"`
	SupplierCredentialExpiresAt sql.NullTime   `json:"supplier_credential_expires_at"`
	DeviceTypeID                int64          `json:"device_type_id"`
	CapabilityCode              string         `json:"capability_code"`
	HlsBaseUrl                  string         `json:"hls_base_url"`
	WebrtcBaseUrl               string         `json:"webrtc_base_url"`
}

func (q *Queries) LockLivePlayback(ctx context.Context, arg LockLivePlaybackParams) (LockLivePlaybackRow, error) {
	row := q.db.QueryRowContext(ctx, lockLivePlayback, arg.ProjectID, arg.ID)
	var i LockLivePlaybackRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.StreamKey,
		&i.SourceType,
		&i.Status,
		&i.PlaybackRef,
		&i.LastActiveAt,
		&i.StatusReason,
		&i.StartAcceptedAt,
		&i.LocalAuthorizationRevokedAt,
		&i.SupplierCredentialExpiresAt,
		&i.DeviceTypeID,
		&i.CapabilityCode,
		&i.HlsBaseUrl,
		&i.WebrtcBaseUrl,
	)
	return i, err
}

const setLivePlaybackExpiry = `-- name: SetLivePlaybackExpiry :exec
UPDATE live_streams SET playback_locator_expires_at=$3,updated_at=now() WHERE project_id=$1 AND id=$2
`

type SetLivePlaybackExpiryParams struct {
	ProjectID                int32        `json:"project_id"`
	ID                       int64        `json:"id"`
	PlaybackLocatorExpiresAt sql.NullTime `json:"playback_locator_expires_at"`
}

func (q *Queries) SetLivePlaybackExpiry(ctx context.Context, arg SetLivePlaybackExpiryParams) error {
	_, err := q.db.ExecContext(ctx, setLivePlaybackExpiry, arg.ProjectID, arg.ID, arg.PlaybackLocatorExpiresAt)
	return err
}
