// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live_start.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countLiveStartSessions = `-- name: CountLiveStartSessions :one
SELECT count(*)::int FROM live_streams WHERE project_id=$1 AND device_id=$2 AND status IN ('requested','starting','live','degraded','stopping')
`

type CountLiveStartSessionsParams struct {
	ProjectID int32 `json:"project_id"`
	DeviceID  int32 `json:"device_id"`
}

func (q *Queries) CountLiveStartSessions(ctx context.Context, arg CountLiveStartSessionsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countLiveStartSessions, arg.ProjectID, arg.DeviceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const findLiveStartReplay = `-- name: FindLiveStartReplay :one
SELECT id FROM live_streams WHERE project_id=$1 AND device_id=$2 AND stream_key=$3 AND status IN ('requested','starting','live','degraded','stopping') LIMIT 1
`

type FindLiveStartReplayParams struct {
	ProjectID int32  `json:"project_id"`
	DeviceID  int32  `json:"device_id"`
	StreamKey string `json:"stream_key"`
}

func (q *Queries) FindLiveStartReplay(ctx context.Context, arg FindLiveStartReplayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findLiveStartReplay, arg.ProjectID, arg.DeviceID, arg.StreamKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLiveStartSession = `-- name: InsertLiveStartSession :one
INSERT INTO live_streams(project_id,team_id,device_id,adapter_id,stream_key,stream_channel_id,source_type,status,ingest_ref,vendor_stream_ref,playback_ref,started_by_user_id,last_active_at,lease_owner,lease_expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,
CASE WHEN $8::text='live' THEN now() ELSE null END,$13,CASE WHEN $13::text IS NULL THEN null ELSE now()+interval '45 seconds' END) RETURNING id
`

type InsertLiveStartSessionParams struct {
	ProjectID   int32          `json:"project_id"`
	TeamID      int32          `json:"team_id"`
	DeviceID    int32          `json:"device_id"`
	AdapterID   sql.NullInt64  `json:"adapter_id"`
	StreamKey   string         `json:"stream_key"`
	ChannelID   sql.NullInt64  `json:"channel_id"`
	SourceType  string         `json:"source_type"`
	Status      string         `json:"status"`
	IngestRef   sql.NullString `json:"ingest_ref"`
	VendorRef   sql.NullString `json:"vendor_ref"`
	PlaybackRef sql.NullString `json:"playback_ref"`
	ActorUserID sql.NullInt32  `json:"actor_user_id"`
	LeaseOwner  sql.NullString `json:"lease_owner"`
}

func (q *Queries) InsertLiveStartSession(ctx context.Context, arg InsertLiveStartSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertLiveStartSession,
		arg.ProjectID,
		arg.TeamID,
		arg.DeviceID,
		arg.AdapterID,
		arg.StreamKey,
		arg.ChannelID,
		arg.SourceType,
		arg.Status,
		arg.IngestRef,
		arg.VendorRef,
		arg.PlaybackRef,
		arg.ActorUserID,
		arg.LeaseOwner,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockLiveStartDevice = `-- name: LockLiveStartDevice :one
SELECT device.status,device.adapter_id,adapter.adapter_type,device.device_type_id,
 coalesce((SELECT array_agg(c.capability_code) FROM device_capabilities c WHERE c.device_id=device.id AND c.project_id=device.project_id AND c.availability='available'),'{}')::text[] AS capabilities,
 coalesce((SELECT greatest(1,least(16,coalesce((c.constraints_json->>'maxConcurrentSessions')::int,1))) FROM device_capabilities c
 WHERE c.device_id=device.id AND c.project_id=device.project_id AND c.capability_code IN ('stream.video.control','camera.live') AND c.availability='available'
 ORDER BY c.capability_code='stream.video.control' DESC LIMIT 1),1)::int AS max_concurrent_sessions,
 profile.media_ingest_base_url,adapter.credential_envelope_json,definition.connector_key,
 coalesce((flags.flighthub_action_flags_json->>'live.control')::boolean,false)::boolean as live_action_enabled,
 exists(select 1 from connector_capability_snapshots capability where capability.project_id=device.project_id
 and capability.connector_instance_id=adapter.id and capability.capability_code='live.control' and capability.status='supported'
 and capability.account_fingerprint=adapter.discovery_scope_json->>'accountFingerprint'
 and capability.region='cn' and capability.deployment='cn-public-cloud' and capability.evidence_level='field-write'
 and capability.device_model=device.device_model and capability.firmware_version is null
 and (capability.expires_at is null or capability.expires_at>now())) as live_capability_verified
FROM devices device LEFT JOIN device_adapters adapter ON adapter.id=device.adapter_id AND adapter.project_id=device.project_id
LEFT JOIN connector_definitions definition ON definition.id=adapter.connector_definition_id
LEFT JOIN project_feature_flags flags ON flags.project_id=device.project_id
LEFT JOIN device_network_profiles profile ON profile.id=adapter.network_profile_id AND profile.project_id=adapter.project_id
WHERE device.project_id=$1 AND device.id=$2 FOR UPDATE OF device
`

type LockLiveStartDeviceParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int32 `json:"id"`
}

type LockLiveStartDeviceRow struct {
	Status                 string                `json:"status"`
	AdapterID              sql.NullInt64         `json:"adapter_id"`
	AdapterType            sql.NullString        `json:"adapter_type"`
	DeviceTypeID           int64                 `json:"device_type_id"`
	Capabilities           []string              `json:"capabilities"`
	MaxConcurrentSessions  int32                 `json:"max_concurrent_sessions"`
	MediaIngestBaseUrl     sql.NullString        `json:"media_ingest_base_url"`
	CredentialEnvelopeJson pqtype.NullRawMessage `json:"credential_envelope_json"`
	ConnectorKey           sql.NullString        `json:"connector_key"`
	LiveActionEnabled      bool                  `json:"live_action_enabled"`
	LiveCapabilityVerified bool                  `json:"live_capability_verified"`
}

func (q *Queries) LockLiveStartDevice(ctx context.Context, arg LockLiveStartDeviceParams) (LockLiveStartDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, lockLiveStartDevice, arg.ProjectID, arg.ID)
	var i LockLiveStartDeviceRow
	err := row.Scan(
		&i.Status,
		&i.AdapterID,
		&i.AdapterType,
		&i.DeviceTypeID,
		pq.Array(&i.Capabilities),
		&i.MaxConcurrentSessions,
		&i.MediaIngestBaseUrl,
		&i.CredentialEnvelopeJson,
		&i.ConnectorKey,
		&i.LiveActionEnabled,
		&i.LiveCapabilityVerified,
	)
	return i, err
}

const readDJILiveTopology = `-- name: ReadDJILiveTopology :one
SELECT parent_identity.external_device_id,(camera_identity.identity_json->>'productType')::int AS camera_type,(camera_identity.identity_json->>'productSubtype')::int AS camera_subtype
FROM device_external_identities camera_identity JOIN device_relationships relation ON relation.project_id=camera_identity.project_id AND relation.to_device_id=camera_identity.device_id AND relation.valid_until IS NULL AND relation.relation_type IN ('contains','mounted-on')
JOIN device_external_identities parent_identity ON parent_identity.project_id=relation.project_id AND parent_identity.adapter_id=camera_identity.adapter_id AND parent_identity.device_id=relation.from_device_id
WHERE camera_identity.project_id=$1 AND camera_identity.device_id=$2 ORDER BY relation.valid_from DESC LIMIT 1
`

type ReadDJILiveTopologyParams struct {
	ProjectID int32         `json:"project_id"`
	DeviceID  sql.NullInt32 `json:"device_id"`
}

type ReadDJILiveTopologyRow struct {
	ExternalDeviceID string `json:"external_device_id"`
	CameraType       int32  `json:"camera_type"`
	CameraSubtype    int32  `json:"camera_subtype"`
}

func (q *Queries) ReadDJILiveTopology(ctx context.Context, arg ReadDJILiveTopologyParams) (ReadDJILiveTopologyRow, error) {
	row := q.db.QueryRowContext(ctx, readDJILiveTopology, arg.ProjectID, arg.DeviceID)
	var i ReadDJILiveTopologyRow
	err := row.Scan(&i.ExternalDeviceID, &i.CameraType, &i.CameraSubtype)
	return i, err
}

const readLiveStartChannel = `-- name: ReadLiveStartChannel :one
SELECT id,channel_key FROM device_stream_channels WHERE project_id=$1 AND device_id=$2 AND data_type='video' AND availability='available'
AND ($3::text IS NULL OR channel_key=$3::text) ORDER BY channel_key LIMIT 1
`

type ReadLiveStartChannelParams struct {
	ProjectID int32          `json:"project_id"`
	DeviceID  int32          `json:"device_id"`
	StreamKey sql.NullString `json:"stream_key"`
}

type ReadLiveStartChannelRow struct {
	ID         int64  `json:"id"`
	ChannelKey string `json:"channel_key"`
}

func (q *Queries) ReadLiveStartChannel(ctx context.Context, arg ReadLiveStartChannelParams) (ReadLiveStartChannelRow, error) {
	row := q.db.QueryRowContext(ctx, readLiveStartChannel, arg.ProjectID, arg.DeviceID, arg.StreamKey)
	var i ReadLiveStartChannelRow
	err := row.Scan(&i.ID, &i.ChannelKey)
	return i, err
}
