// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live_playback.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const lockLivePlayback = `-- name: LockLivePlayback :one
SELECT stream.id,stream.device_id,stream.stream_key,stream.source_type,stream.status,stream.playback_ref,stream.last_active_at,stream.status_reason,
 device.device_type_id,coalesce(channel.capability_code,'camera.live')::text AS capability_code,
 coalesce(profile.media_playback_base_url,'')::text AS hls_base_url,coalesce(profile.config_json->>'webrtcPlaybackBaseUrl','')::text AS webrtc_base_url
FROM live_streams stream JOIN devices device ON device.id=stream.device_id AND device.project_id=stream.project_id
LEFT JOIN device_stream_channels channel ON channel.id=stream.stream_channel_id AND channel.project_id=stream.project_id
LEFT JOIN device_adapters adapter ON adapter.id=stream.adapter_id AND adapter.project_id=stream.project_id
LEFT JOIN device_network_profiles profile ON profile.id=adapter.network_profile_id AND profile.project_id=adapter.project_id
WHERE stream.project_id=$1 AND stream.id=$2 FOR UPDATE OF stream
`

type LockLivePlaybackParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

type LockLivePlaybackRow struct {
	ID             int64          `json:"id"`
	DeviceID       int32          `json:"device_id"`
	StreamKey      string         `json:"stream_key"`
	SourceType     string         `json:"source_type"`
	Status         string         `json:"status"`
	PlaybackRef    sql.NullString `json:"playback_ref"`
	LastActiveAt   sql.NullTime   `json:"last_active_at"`
	StatusReason   sql.NullString `json:"status_reason"`
	DeviceTypeID   int64          `json:"device_type_id"`
	CapabilityCode string         `json:"capability_code"`
	HlsBaseUrl     string         `json:"hls_base_url"`
	WebrtcBaseUrl  string         `json:"webrtc_base_url"`
}

func (q *Queries) LockLivePlayback(ctx context.Context, arg LockLivePlaybackParams) (LockLivePlaybackRow, error) {
	row := q.db.QueryRowContext(ctx, lockLivePlayback, arg.ProjectID, arg.ID)
	var i LockLivePlaybackRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.StreamKey,
		&i.SourceType,
		&i.Status,
		&i.PlaybackRef,
		&i.LastActiveAt,
		&i.StatusReason,
		&i.DeviceTypeID,
		&i.CapabilityCode,
		&i.HlsBaseUrl,
		&i.WebrtcBaseUrl,
	)
	return i, err
}

const setLivePlaybackExpiry = `-- name: SetLivePlaybackExpiry :exec
UPDATE live_streams SET playback_locator_expires_at=$3,updated_at=now() WHERE project_id=$1 AND id=$2
`

type SetLivePlaybackExpiryParams struct {
	ProjectID                int32        `json:"project_id"`
	ID                       int64        `json:"id"`
	PlaybackLocatorExpiresAt sql.NullTime `json:"playback_locator_expires_at"`
}

func (q *Queries) SetLivePlaybackExpiry(ctx context.Context, arg SetLivePlaybackExpiryParams) error {
	_, err := q.db.ExecContext(ctx, setLivePlaybackExpiry, arg.ProjectID, arg.ID, arg.PlaybackLocatorExpiresAt)
	return err
}
