// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live_control.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const insertLiveControlCommand = `-- name: InsertLiveControlCommand :one
INSERT INTO device_commands(id,project_id,team_id,device_id,live_stream_id,command_key,idempotency_key,capability_code,parameters_json,safety_context_json,status,priority,deadline_at,requested_by_user_id)
VALUES($1,$2,$3,$4,$5,$6,$7,'stream.video.control',$8,$9,'dispatchable',$10,now()+interval '30 seconds',$11)
ON CONFLICT(live_stream_id,command_key) WHERE live_stream_id IS NOT NULL DO UPDATE SET command_key=excluded.command_key RETURNING id
`

type InsertLiveControlCommandParams struct {
	ID             uuid.UUID       `json:"id"`
	ProjectID      int32           `json:"project_id"`
	TeamID         int32           `json:"team_id"`
	DeviceID       int32           `json:"device_id"`
	StreamID       sql.NullInt64   `json:"stream_id"`
	CommandKey     string          `json:"command_key"`
	IdempotencyKey string          `json:"idempotency_key"`
	Parameters     json.RawMessage `json:"parameters"`
	Safety         json.RawMessage `json:"safety"`
	Priority       int32           `json:"priority"`
	ActorUserID    sql.NullInt32   `json:"actor_user_id"`
}

func (q *Queries) InsertLiveControlCommand(ctx context.Context, arg InsertLiveControlCommandParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertLiveControlCommand,
		arg.ID,
		arg.ProjectID,
		arg.TeamID,
		arg.DeviceID,
		arg.StreamID,
		arg.CommandKey,
		arg.IdempotencyKey,
		arg.Parameters,
		arg.Safety,
		arg.Priority,
		arg.ActorUserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockLiveControlDevice = `-- name: LockLiveControlDevice :one
SELECT device.id FROM devices device JOIN live_streams stream ON stream.device_id=device.id AND stream.project_id=device.project_id
WHERE stream.project_id=$1 AND stream.id=$2 FOR UPDATE OF device
`

type LockLiveControlDeviceParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) LockLiveControlDevice(ctx context.Context, arg LockLiveControlDeviceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockLiveControlDevice, arg.ProjectID, arg.ID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const lockLiveControlSession = `-- name: LockLiveControlSession :one
SELECT id,device_id,stream_key,source_type,status,playback_ref,last_active_at,status_reason,vendor_stream_ref,start_attempted_at
FROM live_streams WHERE project_id=$1 AND id=$2 FOR UPDATE
`

type LockLiveControlSessionParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

type LockLiveControlSessionRow struct {
	ID               int64          `json:"id"`
	DeviceID         int32          `json:"device_id"`
	StreamKey        string         `json:"stream_key"`
	SourceType       string         `json:"source_type"`
	Status           string         `json:"status"`
	PlaybackRef      sql.NullString `json:"playback_ref"`
	LastActiveAt     sql.NullTime   `json:"last_active_at"`
	StatusReason     sql.NullString `json:"status_reason"`
	VendorStreamRef  sql.NullString `json:"vendor_stream_ref"`
	StartAttemptedAt sql.NullTime   `json:"start_attempted_at"`
}

func (q *Queries) LockLiveControlSession(ctx context.Context, arg LockLiveControlSessionParams) (LockLiveControlSessionRow, error) {
	row := q.db.QueryRowContext(ctx, lockLiveControlSession, arg.ProjectID, arg.ID)
	var i LockLiveControlSessionRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.StreamKey,
		&i.SourceType,
		&i.Status,
		&i.PlaybackRef,
		&i.LastActiveAt,
		&i.StatusReason,
		&i.VendorStreamRef,
		&i.StartAttemptedAt,
	)
	return i, err
}

const stopFlightHubLiveSession = `-- name: StopFlightHubLiveSession :exec
UPDATE live_streams SET
status=case when status='requested' and start_attempted_at is null then 'stopped' else 'stopping' end,
ended_at=case when status='requested' and start_attempted_at is null then now() else null end,
playback_ref=null,playback_locator_expires_at=null,supplier_credential_envelope_json=null,
local_authorization_revoked_at=coalesce(local_authorization_revoked_at,now()),
status_reason=case when status='requested' and start_attempted_at is null then 'FLIGHTHUB_LIVE_STOPPED_BEFORE_DISPATCH' else 'FLIGHTHUB_LIVE_STOP_REMOTE_UNCONFIRMED' end,
lease_owner=null,lease_expires_at=null,updated_at=now()
WHERE project_id=$1 AND id=$2 AND source_type='dji_flighthub' AND status in('requested','starting','live','degraded')
`

type StopFlightHubLiveSessionParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) StopFlightHubLiveSession(ctx context.Context, arg StopFlightHubLiveSessionParams) error {
	_, err := q.db.ExecContext(ctx, stopFlightHubLiveSession, arg.ProjectID, arg.ID)
	return err
}

const stopLiveControlSession = `-- name: StopLiveControlSession :exec
UPDATE live_streams SET status=$1,
 ended_at=CASE WHEN $1::text='stopping' THEN null ELSE now() END,
 playback_ref=CASE WHEN $1::text='stopping' THEN playback_ref ELSE null END,
 playback_locator_expires_at=null,
 lease_owner=CASE WHEN $1::text='stopping' THEN $2::text ELSE null END,
 lease_expires_at=CASE WHEN $1::text='stopping' THEN now()+interval '45 seconds' ELSE null END,
 updated_at=now() WHERE project_id=$3 AND id=$4
`

type StopLiveControlSessionParams struct {
	Status     string `json:"status"`
	LeaseOwner string `json:"lease_owner"`
	ProjectID  int32  `json:"project_id"`
	ID         int64  `json:"id"`
}

func (q *Queries) StopLiveControlSession(ctx context.Context, arg StopLiveControlSessionParams) error {
	_, err := q.db.ExecContext(ctx, stopLiveControlSession,
		arg.Status,
		arg.LeaseOwner,
		arg.ProjectID,
		arg.ID,
	)
	return err
}
