// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: map_registration.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const registerMapDevice = `-- name: RegisterMapDevice :one
INSERT INTO devices(project_id,registration_key,name,type,device_type_id,config_json,status,status_reason,data_freshness)
SELECT $1,$2,$3,
 CASE category WHEN 'camera' THEN 'fixed_sensor' WHEN 'sensor' THEN 'fixed_sensor' WHEN 'ground_robot' THEN 'ground_robot' ELSE 'other' END,
 id,$4::jsonb,'offline','尚未接入设备','unknown'
FROM device_types WHERE type_key=$5 AND status='active' AND type_key LIKE 'registered.%'
ORDER BY version DESC LIMIT 1
ON CONFLICT(project_id,registration_key) WHERE registration_key IS NOT NULL DO UPDATE SET registration_key=EXCLUDED.registration_key
RETURNING id
`

type RegisterMapDeviceParams struct {
	ProjectID       int32           `json:"project_id"`
	RegistrationKey sql.NullString  `json:"registration_key"`
	Name            string          `json:"name"`
	ConfigJson      json.RawMessage `json:"config_json"`
	TypeKey         string          `json:"type_key"`
}

func (q *Queries) RegisterMapDevice(ctx context.Context, arg RegisterMapDeviceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, registerMapDevice,
		arg.ProjectID,
		arg.RegistrationKey,
		arg.Name,
		arg.ConfigJson,
		arg.TypeKey,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const registerMapRegion = `-- name: RegisterMapRegion :one
INSERT INTO project_map_regions(project_id,team_id,registration_key,name,geometry)
SELECT $1,$2,$3,$4,shape.geom
FROM (SELECT ST_Multi(ST_SetSRID(ST_GeomFromGeoJSON($5::text),4326)) AS geom) shape
WHERE ST_IsValid(shape.geom) AND NOT ST_IsEmpty(shape.geom)
ON CONFLICT(project_id,registration_key) DO UPDATE SET registration_key=EXCLUDED.registration_key
RETURNING id
`

type RegisterMapRegionParams struct {
	ProjectID       int32  `json:"project_id"`
	TeamID          int32  `json:"team_id"`
	RegistrationKey string `json:"registration_key"`
	Name            string `json:"name"`
	GeometryJson    string `json:"geometry_json"`
}

func (q *Queries) RegisterMapRegion(ctx context.Context, arg RegisterMapRegionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, registerMapRegion,
		arg.ProjectID,
		arg.TeamID,
		arg.RegistrationKey,
		arg.Name,
		arg.GeometryJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const snapshotMapRegions = `-- name: SnapshotMapRegions :many
SELECT jsonb_build_object('id',id::text,'projectId',project_id,'name',name,'geometry',ST_AsGeoJSON(geometry)::jsonb)
FROM project_map_regions WHERE project_id=$1 ORDER BY id
`

func (q *Queries) SnapshotMapRegions(ctx context.Context, projectID int32) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, snapshotMapRegions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var jsonb_build_object json.RawMessage
		if err := rows.Scan(&jsonb_build_object); err != nil {
			return nil, err
		}
		items = append(items, jsonb_build_object)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
