// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_auth.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const readMediaPublishCredential = `-- name: ReadMediaPublishCredential :one
SELECT stream.project_id,adapter.id AS adapter_id,adapter.credential_envelope_json
FROM live_streams stream JOIN device_adapters adapter ON adapter.id=stream.adapter_id AND adapter.project_id=stream.project_id
WHERE stream.ingest_ref=$1 AND stream.status IN ('requested','starting','live','degraded') LIMIT 1
`

type ReadMediaPublishCredentialRow struct {
	ProjectID              int32                 `json:"project_id"`
	AdapterID              int64                 `json:"adapter_id"`
	CredentialEnvelopeJson pqtype.NullRawMessage `json:"credential_envelope_json"`
}

func (q *Queries) ReadMediaPublishCredential(ctx context.Context, ingestRef sql.NullString) (ReadMediaPublishCredentialRow, error) {
	row := q.db.QueryRowContext(ctx, readMediaPublishCredential, ingestRef)
	var i ReadMediaPublishCredentialRow
	err := row.Scan(&i.ProjectID, &i.AdapterID, &i.CredentialEnvelopeJson)
	return i, err
}
