// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_access.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const readMediaAccessAsset = `-- name: ReadMediaAccessAsset :one
SELECT asset.id,asset.project_id,asset.storage_key,asset.mime_type,asset.kind,
 coalesce(nullif(asset.metadata_json->>'uploadFileName',''),nullif(asset.metadata_json->>'name',''),nullif(asset.metadata_json->>'fileName',''),nullif(asset.metadata_json->>'filename',''),'')::text AS file_name,
 (coalesce(asset.metadata_json->>'sensitive','false')='true' OR coalesce(asset.metadata_json->>'legacyPublishedEvidence','false')='true')::boolean AS sensitive
FROM assets asset
WHERE asset.project_id=$1 AND asset.id=$2 AND asset.status='available'
`

type ReadMediaAccessAssetParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int32 `json:"id"`
}

type ReadMediaAccessAssetRow struct {
	ID         int32          `json:"id"`
	ProjectID  int32          `json:"project_id"`
	StorageKey string         `json:"storage_key"`
	MimeType   sql.NullString `json:"mime_type"`
	Kind       string         `json:"kind"`
	FileName   string         `json:"file_name"`
	Sensitive  bool           `json:"sensitive"`
}

func (q *Queries) ReadMediaAccessAsset(ctx context.Context, arg ReadMediaAccessAssetParams) (ReadMediaAccessAssetRow, error) {
	row := q.db.QueryRowContext(ctx, readMediaAccessAsset, arg.ProjectID, arg.ID)
	var i ReadMediaAccessAssetRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StorageKey,
		&i.MimeType,
		&i.Kind,
		&i.FileName,
		&i.Sensitive,
	)
	return i, err
}
