// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mission_audit.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getEmergencyDrillDevice = `-- name: GetEmergencyDrillDevice :one
SELECT (device.status IN('online','degraded'))::boolean AS connected,
 (EXISTS(SELECT 1 FROM device_capabilities capability WHERE capability.device_id=device.id AND capability.project_id=device.project_id
 AND capability.capability_code IN('safety.emergency_stop','flight.return_home','command.rth')))::boolean AS capability_declared
FROM task_runs run JOIN devices device ON device.id=run.selected_device_id AND device.project_id=run.project_id
WHERE run.project_id=$1 AND run.id=$2
`

type GetEmergencyDrillDeviceParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int32 `json:"id"`
}

type GetEmergencyDrillDeviceRow struct {
	Connected          bool `json:"connected"`
	CapabilityDeclared bool `json:"capability_declared"`
}

func (q *Queries) GetEmergencyDrillDevice(ctx context.Context, arg GetEmergencyDrillDeviceParams) (GetEmergencyDrillDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getEmergencyDrillDevice, arg.ProjectID, arg.ID)
	var i GetEmergencyDrillDeviceRow
	err := row.Scan(&i.Connected, &i.CapabilityDeclared)
	return i, err
}

const getMissionAuditApproval = `-- name: GetMissionAuditApproval :one
SELECT request.id,request.status,request.required_approvals,count(decision.id)::int AS received_approvals
FROM approval_requests request LEFT JOIN approvals decision ON decision.approval_request_id=request.id AND decision.project_id=request.project_id
WHERE request.project_id=$1 AND request.id=$2 GROUP BY request.id
`

type GetMissionAuditApprovalParams struct {
	ProjectID int32     `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

type GetMissionAuditApprovalRow struct {
	ID                uuid.UUID `json:"id"`
	Status            string    `json:"status"`
	RequiredApprovals int32     `json:"required_approvals"`
	ReceivedApprovals int32     `json:"received_approvals"`
}

func (q *Queries) GetMissionAuditApproval(ctx context.Context, arg GetMissionAuditApprovalParams) (GetMissionAuditApprovalRow, error) {
	row := q.db.QueryRowContext(ctx, getMissionAuditApproval, arg.ProjectID, arg.ID)
	var i GetMissionAuditApprovalRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequiredApprovals,
		&i.ReceivedApprovals,
	)
	return i, err
}

const getMissionAuditCommands = `-- name: GetMissionAuditCommands :many
SELECT to_jsonb(r) FROM (
 SELECT command.id::text,command.command_key AS action,command.capability_code AS "capabilityCode",command.status,command.priority,
 attempt.attempt,attempt.status AS "attemptStatus",attempt.error_code AS "errorCode"
 FROM device_commands command LEFT JOIN LATERAL (
  SELECT item.attempt,item.status,item.error_code FROM command_attempts item
  WHERE item.command_id=command.id AND item.project_id=command.project_id ORDER BY item.attempt DESC LIMIT 1
 ) attempt ON true
 WHERE command.project_id=$1 AND command.task_run_id=$2 ORDER BY command.created_at
) r
`

type GetMissionAuditCommandsParams struct {
	ProjectID int32         `json:"project_id"`
	TaskRunID sql.NullInt32 `json:"task_run_id"`
}

func (q *Queries) GetMissionAuditCommands(ctx context.Context, arg GetMissionAuditCommandsParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMissionAuditCommands, arg.ProjectID, arg.TaskRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMissionAuditRequest = `-- name: GetMissionAuditRequest :one
SELECT request_id,action,actor_user_id,actor_agent_id,created_at FROM audit_events
WHERE project_id=$1 AND ((resource_type='task_run' AND resource_id=$2::text)
 OR (resource_type='task_version' AND resource_id=$3::text))
ORDER BY CASE WHEN action IN('agent.request_mission_start','task_run.transition','task_run.emergency_stop') THEN 0 ELSE 1 END,created_at LIMIT 1
`

type GetMissionAuditRequestParams struct {
	ProjectID int32          `json:"project_id"`
	RunID     string         `json:"run_id"`
	VersionID sql.NullString `json:"version_id"`
}

type GetMissionAuditRequestRow struct {
	RequestID    string        `json:"request_id"`
	Action       string        `json:"action"`
	ActorUserID  sql.NullInt32 `json:"actor_user_id"`
	ActorAgentID sql.NullInt32 `json:"actor_agent_id"`
	CreatedAt    time.Time     `json:"created_at"`
}

func (q *Queries) GetMissionAuditRequest(ctx context.Context, arg GetMissionAuditRequestParams) (GetMissionAuditRequestRow, error) {
	row := q.db.QueryRowContext(ctx, getMissionAuditRequest, arg.ProjectID, arg.RunID, arg.VersionID)
	var i GetMissionAuditRequestRow
	err := row.Scan(
		&i.RequestID,
		&i.Action,
		&i.ActorUserID,
		&i.ActorAgentID,
		&i.CreatedAt,
	)
	return i, err
}

const getMissionAuditRun = `-- name: GetMissionAuditRun :one
SELECT trigger_source,task_version_id,safety_policy_version_id,approval_request_id,preflight_snapshot_json
FROM task_runs WHERE project_id=$1 AND id=$2
`

type GetMissionAuditRunParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int32 `json:"id"`
}

type GetMissionAuditRunRow struct {
	TriggerSource         string          `json:"trigger_source"`
	TaskVersionID         sql.NullInt64   `json:"task_version_id"`
	SafetyPolicyVersionID sql.NullInt64   `json:"safety_policy_version_id"`
	ApprovalRequestID     uuid.NullUUID   `json:"approval_request_id"`
	PreflightSnapshotJson json.RawMessage `json:"preflight_snapshot_json"`
}

func (q *Queries) GetMissionAuditRun(ctx context.Context, arg GetMissionAuditRunParams) (GetMissionAuditRunRow, error) {
	row := q.db.QueryRowContext(ctx, getMissionAuditRun, arg.ProjectID, arg.ID)
	var i GetMissionAuditRunRow
	err := row.Scan(
		&i.TriggerSource,
		&i.TaskVersionID,
		&i.SafetyPolicyVersionID,
		&i.ApprovalRequestID,
		&i.PreflightSnapshotJson,
	)
	return i, err
}
