// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mission_control.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const approveMissionControlRun = `-- name: ApproveMissionControlRun :exec
INSERT INTO approvals(project_id,team_id,approval_request_id,approver_user_id,decision,reason)
VALUES($1,$2,$3,$4,'approved',$5)
`

type ApproveMissionControlRunParams struct {
	ProjectID         int32     `json:"project_id"`
	TeamID            int32     `json:"team_id"`
	ApprovalRequestID uuid.UUID `json:"approval_request_id"`
	ApproverUserID    int32     `json:"approver_user_id"`
	Reason            string    `json:"reason"`
}

func (q *Queries) ApproveMissionControlRun(ctx context.Context, arg ApproveMissionControlRunParams) error {
	_, err := q.db.ExecContext(ctx, approveMissionControlRun,
		arg.ProjectID,
		arg.TeamID,
		arg.ApprovalRequestID,
		arg.ApproverUserID,
		arg.Reason,
	)
	return err
}

const lockMissionControlRun = `-- name: LockMissionControlRun :one
SELECT status,state_version,approval_request_id FROM task_runs WHERE project_id=$1 AND id=$2 FOR UPDATE
`

type LockMissionControlRunParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int32 `json:"id"`
}

type LockMissionControlRunRow struct {
	Status            string        `json:"status"`
	StateVersion      int32         `json:"state_version"`
	ApprovalRequestID uuid.NullUUID `json:"approval_request_id"`
}

func (q *Queries) LockMissionControlRun(ctx context.Context, arg LockMissionControlRunParams) (LockMissionControlRunRow, error) {
	row := q.db.QueryRowContext(ctx, lockMissionControlRun, arg.ProjectID, arg.ID)
	var i LockMissionControlRunRow
	err := row.Scan(&i.Status, &i.StateVersion, &i.ApprovalRequestID)
	return i, err
}

const updateMissionControlRun = `-- name: UpdateMissionControlRun :one
UPDATE task_runs SET status=$4,state_version=state_version+1,state_reason=$5
WHERE project_id=$1 AND id=$2 AND state_version=$3 RETURNING id,status,state_version
`

type UpdateMissionControlRunParams struct {
	ProjectID    int32          `json:"project_id"`
	ID           int32          `json:"id"`
	StateVersion int32          `json:"state_version"`
	Status       string         `json:"status"`
	StateReason  sql.NullString `json:"state_reason"`
}

type UpdateMissionControlRunRow struct {
	ID           int32  `json:"id"`
	Status       string `json:"status"`
	StateVersion int32  `json:"state_version"`
}

func (q *Queries) UpdateMissionControlRun(ctx context.Context, arg UpdateMissionControlRunParams) (UpdateMissionControlRunRow, error) {
	row := q.db.QueryRowContext(ctx, updateMissionControlRun,
		arg.ProjectID,
		arg.ID,
		arg.StateVersion,
		arg.Status,
		arg.StateReason,
	)
	var i UpdateMissionControlRunRow
	err := row.Scan(&i.ID, &i.Status, &i.StateVersion)
	return i, err
}
