// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_features.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const ensureProjectFeatures = `-- name: EnsureProjectFeatures :exec
INSERT INTO project_feature_flags(project_id) VALUES($1) ON CONFLICT(project_id) DO NOTHING
`

func (q *Queries) EnsureProjectFeatures(ctx context.Context, projectID int32) error {
	_, err := q.db.ExecContext(ctx, ensureProjectFeatures, projectID)
	return err
}

const lockProjectFeatures = `-- name: LockProjectFeatures :one
SELECT project_id, device_commands_enabled, operations_overview_enabled, object_storage_enabled, external_algorithms_enabled, automatic_ai_enabled, dependency_health_json, updated_by_user_id, updated_at, flighthub_action_flags_json FROM project_feature_flags WHERE project_id=$1 FOR UPDATE
`

func (q *Queries) LockProjectFeatures(ctx context.Context, projectID int32) (ProjectFeatureFlag, error) {
	row := q.db.QueryRowContext(ctx, lockProjectFeatures, projectID)
	var i ProjectFeatureFlag
	err := row.Scan(
		&i.ProjectID,
		&i.DeviceCommandsEnabled,
		&i.OperationsOverviewEnabled,
		&i.ObjectStorageEnabled,
		&i.ExternalAlgorithmsEnabled,
		&i.AutomaticAiEnabled,
		&i.DependencyHealthJson,
		&i.UpdatedByUserID,
		&i.UpdatedAt,
		&i.FlighthubActionFlagsJson,
	)
	return i, err
}

const readProjectFeatures = `-- name: ReadProjectFeatures :one
SELECT (coalesce(f.flighthub_action_flags_json,'{}'::jsonb) || jsonb_build_object(
 'operations.overview',coalesce(f.operations_overview_enabled,false),
 'devices.commands',coalesce(f.device_commands_enabled,false),
 'storage.objects',coalesce(f.object_storage_enabled,false),
 'algorithms.external',coalesce(f.external_algorithms_enabled,false)
))::jsonb AS values
FROM projects p LEFT JOIN project_feature_flags f ON f.project_id=p.id WHERE p.id=$1
`

func (q *Queries) ReadProjectFeatures(ctx context.Context, id int32) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, readProjectFeatures, id)
	var values json.RawMessage
	err := row.Scan(&values)
	return values, err
}

const saveProjectFeatures = `-- name: SaveProjectFeatures :exec
UPDATE project_feature_flags SET
 operations_overview_enabled=$2,device_commands_enabled=$3,
 object_storage_enabled=$4,external_algorithms_enabled=$5,
 flighthub_action_flags_json=flighthub_action_flags_json || $7::jsonb,
 updated_by_user_id=$6,updated_at=now()
WHERE project_id=$1
`

type SaveProjectFeaturesParams struct {
	ProjectID                 int32           `json:"project_id"`
	OperationsOverviewEnabled bool            `json:"operations_overview_enabled"`
	DeviceCommandsEnabled     bool            `json:"device_commands_enabled"`
	ObjectStorageEnabled      bool            `json:"object_storage_enabled"`
	ExternalAlgorithmsEnabled bool            `json:"external_algorithms_enabled"`
	UpdatedByUserID           sql.NullInt32   `json:"updated_by_user_id"`
	ActionChanges             json.RawMessage `json:"action_changes"`
}

func (q *Queries) SaveProjectFeatures(ctx context.Context, arg SaveProjectFeaturesParams) error {
	_, err := q.db.ExecContext(ctx, saveProjectFeatures,
		arg.ProjectID,
		arg.OperationsOverviewEnabled,
		arg.DeviceCommandsEnabled,
		arg.ObjectStorageEnabled,
		arg.ExternalAlgorithmsEnabled,
		arg.UpdatedByUserID,
		arg.ActionChanges,
	)
	return err
}
