// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

type Querier interface {
	AdminOverview(ctx context.Context) (AdminOverviewRow, error)
	ApproveMissionControlRun(ctx context.Context, arg ApproveMissionControlRunParams) error
	BindDiscoveredDevice(ctx context.Context, arg BindDiscoveredDeviceParams) error
	CancelFlightHubSyncQueue(ctx context.Context, arg CancelFlightHubSyncQueueParams) error
	CancelFlightHubSyncRuns(ctx context.Context, arg CancelFlightHubSyncRunsParams) error
	ChannelGrants(ctx context.Context, arg ChannelGrantsParams) ([]ChannelGrantsRow, error)
	CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) (int64, error)
	CompletePlatformAudit(ctx context.Context, arg CompletePlatformAuditParams) (int64, error)
	CompleteProjectAudit(ctx context.Context, arg CompleteProjectAuditParams) (int64, error)
	CountDeviceCommandConflicts(ctx context.Context, arg CountDeviceCommandConflictsParams) (int32, error)
	CreateDefaultAdmin(ctx context.Context, password sql.NullString) error
	CreateFlightHubConnector(ctx context.Context, arg CreateFlightHubConnectorParams) (CreateFlightHubConnectorRow, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (int32, error)
	CreateTeam(ctx context.Context, name string) (int32, error)
	CreateTeamOwner(ctx context.Context, arg CreateTeamOwnerParams) error
	DeclareDiscoveredCapability(ctx context.Context, arg DeclareDiscoveredCapabilityParams) error
	DisableFlightHubBindings(ctx context.Context, arg DisableFlightHubBindingsParams) error
	DisableFlightHubConnector(ctx context.Context, arg DisableFlightHubConnectorParams) (int64, error)
	EnqueueProjectEvent(ctx context.Context, arg EnqueueProjectEventParams) error
	FindExistingDeviceCommand(ctx context.Context, arg FindExistingDeviceCommandParams) (FindExistingDeviceCommandRow, error)
	FindFlightHubConnector(ctx context.Context, arg FindFlightHubConnectorParams) (FindFlightHubConnectorRow, error)
	FindLoginUser(ctx context.Context, username string) (FindLoginUserRow, error)
	FindQueuedFlightHubSync(ctx context.Context, arg FindQueuedFlightHubSyncParams) (string, error)
	GetAdapterNetworkProfile(ctx context.Context, arg GetAdapterNetworkProfileParams) (GetAdapterNetworkProfileRow, error)
	GetEmergencyDrillDevice(ctx context.Context, arg GetEmergencyDrillDeviceParams) (GetEmergencyDrillDeviceRow, error)
	GetMissionAuditApproval(ctx context.Context, arg GetMissionAuditApprovalParams) (GetMissionAuditApprovalRow, error)
	GetMissionAuditCommands(ctx context.Context, arg GetMissionAuditCommandsParams) ([]json.RawMessage, error)
	GetMissionAuditRequest(ctx context.Context, arg GetMissionAuditRequestParams) (GetMissionAuditRequestRow, error)
	GetMissionAuditRun(ctx context.Context, arg GetMissionAuditRunParams) (GetMissionAuditRunRow, error)
	GetMissionWorkbenchRun(ctx context.Context, arg GetMissionWorkbenchRunParams) (json.RawMessage, error)
	GetMissionWorkbenchSteps(ctx context.Context, arg GetMissionWorkbenchStepsParams) ([]json.RawMessage, error)
	GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error)
	GetProjectAccess(ctx context.Context, arg GetProjectAccessParams) (GetProjectAccessRow, error)
	GetProjectDevice(ctx context.Context, arg GetProjectDeviceParams) (json.RawMessage, error)
	GetTeam(ctx context.Context, arg GetTeamParams) (GetTeamRow, error)
	GetTeamManager(ctx context.Context, arg GetTeamManagerParams) (int32, error)
	GetUser(ctx context.Context, id int32) (GetUserRow, error)
	HasUsers(ctx context.Context) (bool, error)
	InsertDJINetworkProfile(ctx context.Context, arg InsertDJINetworkProfileParams) (int64, error)
	InsertDJISetupAdapter(ctx context.Context, arg InsertDJISetupAdapterParams) (json.RawMessage, error)
	InsertDeviceAdapter(ctx context.Context, arg InsertDeviceAdapterParams) (json.RawMessage, error)
	InsertDeviceCommand(ctx context.Context, arg InsertDeviceCommandParams) (InsertDeviceCommandRow, error)
	InsertDiscoveredDevice(ctx context.Context, arg InsertDiscoveredDeviceParams) (int32, error)
	InsertPlatformAudit(ctx context.Context, arg InsertPlatformAuditParams) (int64, error)
	InsertProjectAudit(ctx context.Context, arg InsertProjectAuditParams) (int64, error)
	ListAdminProjects(ctx context.Context) ([]ListAdminProjectsRow, error)
	ListAdminTeams(ctx context.Context) ([]ListAdminTeamsRow, error)
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
	ListDeviceAdapters(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListFlightHubConnections(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListFlightHubIdentities(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListFlightHubSyncRuns(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListMissionRuns(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListProfileTeams(ctx context.Context, userID int32) ([]ListProfileTeamsRow, error)
	ListProjectDevices(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListTeamProjects(ctx context.Context, teamID int32) ([]ListTeamProjectsRow, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error)
	LockDJIAdapterEnvelope(ctx context.Context, arg LockDJIAdapterEnvelopeParams) (pqtype.NullRawMessage, error)
	LockDeviceCommandGrants(ctx context.Context, arg LockDeviceCommandGrantsParams) ([]LockDeviceCommandGrantsRow, error)
	LockDeviceCommandTarget(ctx context.Context, arg LockDeviceCommandTargetParams) (LockDeviceCommandTargetRow, error)
	LockDiscoveredDevice(ctx context.Context, arg LockDiscoveredDeviceParams) (LockDiscoveredDeviceRow, error)
	LockFlightHubConnector(ctx context.Context, arg LockFlightHubConnectorParams) (LockFlightHubConnectorRow, error)
	LockFlightHubSyncQueue(ctx context.Context, lockKey string) error
	LockMissionControlRun(ctx context.Context, arg LockMissionControlRunParams) (LockMissionControlRunRow, error)
	LockProjectMembership(ctx context.Context, arg LockProjectMembershipParams) (LockProjectMembershipRow, error)
	LockProjectPermissions(ctx context.Context, arg LockProjectPermissionsParams) ([]string, error)
	PublishProjectEvent(ctx context.Context, arg PublishProjectEventParams) (int64, error)
	ReadChannelEvents(ctx context.Context, arg ReadChannelEventsParams) ([]ReadChannelEventsRow, error)
	ReadChannelTelemetry(ctx context.Context, arg ReadChannelTelemetryParams) ([]ReadChannelTelemetryRow, error)
	ReadDeviceRelations(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ReadDeviceTree(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ReadIdempotency(ctx context.Context, arg ReadIdempotencyParams) (ReadIdempotencyRow, error)
	ReadProjectEvents(ctx context.Context, arg ReadProjectEventsParams) ([]ReadProjectEventsRow, error)
	RecordAdapterHealth(ctx context.Context, arg RecordAdapterHealthParams) error
	RecordNetworkValidation(ctx context.Context, arg RecordNetworkValidationParams) error
	ReplayEvents(ctx context.Context, arg ReplayEventsParams) ([]json.RawMessage, error)
	ReplayMedia(ctx context.Context, arg ReplayMediaParams) ([]json.RawMessage, error)
	ReplayPoses(ctx context.Context, arg ReplayPosesParams) ([]json.RawMessage, error)
	ReserveIdempotency(ctx context.Context, arg ReserveIdempotencyParams) (int64, error)
	ResolveChannel(ctx context.Context, arg ResolveChannelParams) (ResolveChannelRow, error)
	SetDeviceAdapterEnabled(ctx context.Context, arg SetDeviceAdapterEnabledParams) (SetDeviceAdapterEnabledRow, error)
	SnapshotActiveTasks(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotAlerts(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotDeviceGrants(ctx context.Context, arg SnapshotDeviceGrantsParams) ([]json.RawMessage, error)
	SnapshotDevices(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotDiagnostics(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotIssues(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotLiveStreams(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotMedia(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotProjectScope(ctx context.Context, arg SnapshotProjectScopeParams) (SnapshotProjectScopeRow, error)
	SnapshotRealtimeChannels(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotSuspectedConstruction(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotTracks(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	StoreDeviceAdapterEnvelope(ctx context.Context, arg StoreDeviceAdapterEnvelopeParams) error
	UpdateDJIAdapterEnvelope(ctx context.Context, arg UpdateDJIAdapterEnvelopeParams) error
	UpdateFlightHubCredentials(ctx context.Context, arg UpdateFlightHubCredentialsParams) (int64, error)
	UpdateMissionControlRun(ctx context.Context, arg UpdateMissionControlRunParams) (UpdateMissionControlRunRow, error)
}

var _ Querier = (*Queries)(nil)
