// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Querier interface {
	AddIssueAssignee(ctx context.Context, arg AddIssueAssigneeParams) error
	AdminOverview(ctx context.Context) (AdminOverviewRow, error)
	ApproveMissionControlRun(ctx context.Context, arg ApproveMissionControlRunParams) error
	BindDiscoveredDevice(ctx context.Context, arg BindDiscoveredDeviceParams) error
	CancelFlightHubSyncQueue(ctx context.Context, arg CancelFlightHubSyncQueueParams) error
	CancelFlightHubSyncRuns(ctx context.Context, arg CancelFlightHubSyncRunsParams) error
	ChannelGrants(ctx context.Context, arg ChannelGrantsParams) ([]ChannelGrantsRow, error)
	CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) (int64, error)
	CompletePlatformAudit(ctx context.Context, arg CompletePlatformAuditParams) (int64, error)
	CompleteProjectAudit(ctx context.Context, arg CompleteProjectAuditParams) (int64, error)
	CountDeviceCommandConflicts(ctx context.Context, arg CountDeviceCommandConflictsParams) (int32, error)
	CreateAlgorithmDefinition(ctx context.Context, arg CreateAlgorithmDefinitionParams) (int64, error)
	CreateAlgorithmProvider(ctx context.Context, arg CreateAlgorithmProviderParams) (int64, error)
	CreateDefaultAdmin(ctx context.Context, password sql.NullString) error
	CreateFlightHubConnector(ctx context.Context, arg CreateFlightHubConnectorParams) (CreateFlightHubConnectorRow, error)
	CreateIssueCopilotSession(ctx context.Context, arg CreateIssueCopilotSessionParams) (int32, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (int32, error)
	CreateTeam(ctx context.Context, name string) (int32, error)
	CreateTeamOwner(ctx context.Context, arg CreateTeamOwnerParams) error
	DeclareDiscoveredCapability(ctx context.Context, arg DeclareDiscoveredCapabilityParams) error
	DisableFlightHubBindings(ctx context.Context, arg DisableFlightHubBindingsParams) error
	DisableFlightHubConnector(ctx context.Context, arg DisableFlightHubConnectorParams) (int64, error)
	EnqueueProjectEvent(ctx context.Context, arg EnqueueProjectEventParams) error
	EnsureIssueCopilot(ctx context.Context, projectID int32) (int32, error)
	ExportPublishedReport(ctx context.Context, arg ExportPublishedReportParams) (json.RawMessage, error)
	FindExistingDeviceCommand(ctx context.Context, arg FindExistingDeviceCommandParams) (FindExistingDeviceCommandRow, error)
	FindFlightHubConnector(ctx context.Context, arg FindFlightHubConnectorParams) (FindFlightHubConnectorRow, error)
	FindLoginUser(ctx context.Context, username string) (FindLoginUserRow, error)
	FindQueuedFlightHubSync(ctx context.Context, arg FindQueuedFlightHubSyncParams) (string, error)
	GetAdapterNetworkProfile(ctx context.Context, arg GetAdapterNetworkProfileParams) (GetAdapterNetworkProfileRow, error)
	GetEmergencyDrillDevice(ctx context.Context, arg GetEmergencyDrillDeviceParams) (GetEmergencyDrillDeviceRow, error)
	GetLegacyPerceptionDetections(ctx context.Context, arg GetLegacyPerceptionDetectionsParams) ([]json.RawMessage, error)
	GetLegacyPerceptionEvent(ctx context.Context, arg GetLegacyPerceptionEventParams) (json.RawMessage, error)
	GetLegacyPerceptionFeedback(ctx context.Context, arg GetLegacyPerceptionFeedbackParams) ([]json.RawMessage, error)
	GetMissionAuditApproval(ctx context.Context, arg GetMissionAuditApprovalParams) (GetMissionAuditApprovalRow, error)
	GetMissionAuditCommands(ctx context.Context, arg GetMissionAuditCommandsParams) ([]json.RawMessage, error)
	GetMissionAuditRequest(ctx context.Context, arg GetMissionAuditRequestParams) (GetMissionAuditRequestRow, error)
	GetMissionAuditRun(ctx context.Context, arg GetMissionAuditRunParams) (GetMissionAuditRunRow, error)
	GetMissionWorkbenchRun(ctx context.Context, arg GetMissionWorkbenchRunParams) (json.RawMessage, error)
	GetMissionWorkbenchSteps(ctx context.Context, arg GetMissionWorkbenchStepsParams) ([]json.RawMessage, error)
	GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error)
	GetProjectAccess(ctx context.Context, arg GetProjectAccessParams) (GetProjectAccessRow, error)
	GetProjectDevice(ctx context.Context, arg GetProjectDeviceParams) (json.RawMessage, error)
	GetTaskDefinition(ctx context.Context, arg GetTaskDefinitionParams) (json.RawMessage, error)
	GetTeam(ctx context.Context, arg GetTeamParams) (GetTeamRow, error)
	GetTeamManager(ctx context.Context, arg GetTeamManagerParams) (int32, error)
	GetUser(ctx context.Context, id int32) (GetUserRow, error)
	HasUsers(ctx context.Context) (bool, error)
	InsertAlgorithmConfiguration(ctx context.Context, arg InsertAlgorithmConfigurationParams) (int64, error)
	InsertCatalogAlgorithmRun(ctx context.Context, arg InsertCatalogAlgorithmRunParams) error
	InsertDJINetworkProfile(ctx context.Context, arg InsertDJINetworkProfileParams) (int64, error)
	InsertDJISetupAdapter(ctx context.Context, arg InsertDJISetupAdapterParams) (json.RawMessage, error)
	InsertDeviceAdapter(ctx context.Context, arg InsertDeviceAdapterParams) (json.RawMessage, error)
	InsertDeviceCommand(ctx context.Context, arg InsertDeviceCommandParams) (InsertDeviceCommandRow, error)
	InsertDiscoveredDevice(ctx context.Context, arg InsertDiscoveredDeviceParams) (int32, error)
	InsertIssueActivity(ctx context.Context, arg InsertIssueActivityParams) (int32, error)
	InsertPlatformAudit(ctx context.Context, arg InsertPlatformAuditParams) (int64, error)
	InsertProjectAudit(ctx context.Context, arg InsertProjectAuditParams) (int64, error)
	InsertReportDraft(ctx context.Context, arg InsertReportDraftParams) (uuid.UUID, error)
	InsertReportEvidence(ctx context.Context, arg InsertReportEvidenceParams) error
	IssueAssigneeActive(ctx context.Context, arg IssueAssigneeActiveParams) (bool, error)
	IssueMutationReplayed(ctx context.Context, arg IssueMutationReplayedParams) (bool, error)
	ListAdminProjects(ctx context.Context) ([]ListAdminProjectsRow, error)
	ListAdminTeams(ctx context.Context) ([]ListAdminTeamsRow, error)
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
	ListAlgorithmCatalog(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListAlgorithmProviders(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListAlgorithmRuns(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListDeviceAdapters(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListFlightHubConnections(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListFlightHubIdentities(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListFlightHubSyncRuns(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListLegacyPerceptionEvents(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListMissionRuns(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListProfileTeams(ctx context.Context, userID int32) ([]ListProfileTeamsRow, error)
	ListProjectDevices(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListProjectIssues(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListTaskDefinitions(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ListTeamProjects(ctx context.Context, teamID int32) ([]ListTeamProjectsRow, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error)
	LockAlgorithmDefinition(ctx context.Context, arg LockAlgorithmDefinitionParams) (int64, error)
	LockAlgorithmDefinitionProvider(ctx context.Context, arg LockAlgorithmDefinitionProviderParams) (int32, error)
	LockAlgorithmProviderCredential(ctx context.Context, arg LockAlgorithmProviderCredentialParams) (LockAlgorithmProviderCredentialRow, error)
	LockAlgorithmRetrySource(ctx context.Context, arg LockAlgorithmRetrySourceParams) (LockAlgorithmRetrySourceRow, error)
	LockDJIAdapterEnvelope(ctx context.Context, arg LockDJIAdapterEnvelopeParams) (pqtype.NullRawMessage, error)
	LockDeviceCommandGrants(ctx context.Context, arg LockDeviceCommandGrantsParams) ([]LockDeviceCommandGrantsRow, error)
	LockDeviceCommandTarget(ctx context.Context, arg LockDeviceCommandTargetParams) (LockDeviceCommandTargetRow, error)
	LockDiscoveredDevice(ctx context.Context, arg LockDiscoveredDeviceParams) (LockDiscoveredDeviceRow, error)
	LockFlightHubConnector(ctx context.Context, arg LockFlightHubConnectorParams) (LockFlightHubConnectorRow, error)
	LockFlightHubSyncQueue(ctx context.Context, lockKey string) error
	LockIssueAssigneeAgent(ctx context.Context, arg LockIssueAssigneeAgentParams) (LockIssueAssigneeAgentRow, error)
	LockIssueAssigneeUser(ctx context.Context, arg LockIssueAssigneeUserParams) (int32, error)
	LockIssueMutation(ctx context.Context, arg LockIssueMutationParams) (int32, error)
	LockMissionControlRun(ctx context.Context, arg LockMissionControlRunParams) (LockMissionControlRunRow, error)
	LockProjectMembership(ctx context.Context, arg LockProjectMembershipParams) (LockProjectMembershipRow, error)
	LockProjectPermissions(ctx context.Context, arg LockProjectPermissionsParams) ([]string, error)
	LockReportDraft(ctx context.Context, arg LockReportDraftParams) (LockReportDraftRow, error)
	LockReportPublication(ctx context.Context, arg LockReportPublicationParams) (uuid.UUID, error)
	NextAlgorithmConfigurationVersion(ctx context.Context, arg NextAlgorithmConfigurationVersionParams) (int32, error)
	NextReportVersion(ctx context.Context, generatedReportID uuid.UUID) (int32, error)
	PointPublishedReport(ctx context.Context, arg PointPublishedReportParams) error
	PublishProjectEvent(ctx context.Context, arg PublishProjectEventParams) (int64, error)
	PublishReportVersion(ctx context.Context, arg PublishReportVersionParams) error
	QueueIssueCopilot(ctx context.Context, arg QueueIssueCopilotParams) (uuid.UUID, error)
	ReadAlgorithmProviderEndpoint(ctx context.Context, arg ReadAlgorithmProviderEndpointParams) (ReadAlgorithmProviderEndpointRow, error)
	ReadAlgorithmProviderPublic(ctx context.Context, arg ReadAlgorithmProviderPublicParams) (json.RawMessage, error)
	ReadAlgorithmRunAttempts(ctx context.Context, arg ReadAlgorithmRunAttemptsParams) ([]json.RawMessage, error)
	ReadAlgorithmRunDetail(ctx context.Context, arg ReadAlgorithmRunDetailParams) (json.RawMessage, error)
	ReadAlgorithmRunSource(ctx context.Context, arg ReadAlgorithmRunSourceParams) (ReadAlgorithmRunSourceRow, error)
	ReadChannelEvents(ctx context.Context, arg ReadChannelEventsParams) ([]ReadChannelEventsRow, error)
	ReadChannelTelemetry(ctx context.Context, arg ReadChannelTelemetryParams) ([]ReadChannelTelemetryRow, error)
	ReadDeviceRelations(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ReadDeviceTree(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ReadIdempotency(ctx context.Context, arg ReadIdempotencyParams) (ReadIdempotencyRow, error)
	ReadIssueAgents(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	ReadIssueAssets(ctx context.Context, arg ReadIssueAssetsParams) ([]json.RawMessage, error)
	ReadIssueAssignees(ctx context.Context, arg ReadIssueAssigneesParams) ([]json.RawMessage, error)
	ReadIssueDetections(ctx context.Context, arg ReadIssueDetectionsParams) ([]json.RawMessage, error)
	ReadIssueDrafts(ctx context.Context, arg ReadIssueDraftsParams) ([]json.RawMessage, error)
	ReadIssueEvents(ctx context.Context, arg ReadIssueEventsParams) ([]json.RawMessage, error)
	ReadIssueLinks(ctx context.Context, arg ReadIssueLinksParams) ([]json.RawMessage, error)
	ReadIssueMembers(ctx context.Context, id int32) ([]json.RawMessage, error)
	ReadProjectEvents(ctx context.Context, arg ReadProjectEventsParams) ([]ReadProjectEventsRow, error)
	ReadProjectIssue(ctx context.Context, arg ReadProjectIssueParams) (json.RawMessage, error)
	ReadReportSources(ctx context.Context, arg ReadReportSourcesParams) (json.RawMessage, error)
	RecordAdapterHealth(ctx context.Context, arg RecordAdapterHealthParams) error
	RecordNetworkValidation(ctx context.Context, arg RecordNetworkValidationParams) error
	RemoveIssueAssignee(ctx context.Context, arg RemoveIssueAssigneeParams) error
	ReplayEvents(ctx context.Context, arg ReplayEventsParams) ([]json.RawMessage, error)
	ReplayMedia(ctx context.Context, arg ReplayMediaParams) ([]json.RawMessage, error)
	ReplayPoses(ctx context.Context, arg ReplayPosesParams) ([]json.RawMessage, error)
	ReserveIdempotency(ctx context.Context, arg ReserveIdempotencyParams) (int64, error)
	ResolveChannel(ctx context.Context, arg ResolveChannelParams) (ResolveChannelRow, error)
	RetainReportAssets(ctx context.Context, arg RetainReportAssetsParams) error
	RetireAlgorithmConfigurations(ctx context.Context, arg RetireAlgorithmConfigurationsParams) error
	RetirePublishedReport(ctx context.Context, arg RetirePublishedReportParams) error
	RetireReportDrafts(ctx context.Context, arg RetireReportDraftsParams) error
	SetAlgorithmCurrentConfiguration(ctx context.Context, arg SetAlgorithmCurrentConfigurationParams) error
	SetAlgorithmProviderCredential(ctx context.Context, arg SetAlgorithmProviderCredentialParams) error
	SetDeviceAdapterEnabled(ctx context.Context, arg SetDeviceAdapterEnabledParams) (SetDeviceAdapterEnabledRow, error)
	SnapshotActiveTasks(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotAlerts(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotDeviceGrants(ctx context.Context, arg SnapshotDeviceGrantsParams) ([]json.RawMessage, error)
	SnapshotDevices(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotDiagnostics(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotIssues(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotLiveStreams(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotMedia(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotProjectScope(ctx context.Context, arg SnapshotProjectScopeParams) (SnapshotProjectScopeRow, error)
	SnapshotRealtimeChannels(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotSuspectedConstruction(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	SnapshotTracks(ctx context.Context, projectID int32) ([]json.RawMessage, error)
	StoreDeviceAdapterEnvelope(ctx context.Context, arg StoreDeviceAdapterEnvelopeParams) error
	UpdateAlgorithmDefinition(ctx context.Context, arg UpdateAlgorithmDefinitionParams) error
	UpdateAlgorithmProvider(ctx context.Context, arg UpdateAlgorithmProviderParams) error
	UpdateDJIAdapterEnvelope(ctx context.Context, arg UpdateDJIAdapterEnvelopeParams) error
	UpdateFlightHubCredentials(ctx context.Context, arg UpdateFlightHubCredentialsParams) (int64, error)
	UpdateIssueMutation(ctx context.Context, arg UpdateIssueMutationParams) (int32, error)
	UpdateMissionControlRun(ctx context.Context, arg UpdateMissionControlRunParams) (UpdateMissionControlRunRow, error)
	UpsertDraftReport(ctx context.Context, arg UpsertDraftReportParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
