// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const exportPublishedReport = `-- name: ExportPublishedReport :one
SELECT to_jsonb(r) FROM (
 SELECT report.id::text,report.title,version.version,version.completeness,version.content_json AS content,
 version.data_gaps_json AS "dataGaps",version.published_at AS "publishedAt"
 FROM generated_reports report JOIN generated_report_versions version ON version.id=report.current_published_version_id AND version.project_id=report.project_id
 WHERE report.project_id=$1 AND report.id=$2 AND version.status='published'
) r
`

type ExportPublishedReportParams struct {
	ProjectID int32     `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) ExportPublishedReport(ctx context.Context, arg ExportPublishedReportParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, exportPublishedReport, arg.ProjectID, arg.ID)
	var to_jsonb json.RawMessage
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const lockReportDraft = `-- name: LockReportDraft :one
SELECT id,completeness,content_json FROM generated_report_versions WHERE project_id=$1 AND generated_report_id=$2 AND status='draft' FOR UPDATE
`

type LockReportDraftParams struct {
	ProjectID         int32     `json:"project_id"`
	GeneratedReportID uuid.UUID `json:"generated_report_id"`
}

type LockReportDraftRow struct {
	ID           uuid.UUID       `json:"id"`
	Completeness string          `json:"completeness"`
	ContentJson  json.RawMessage `json:"content_json"`
}

func (q *Queries) LockReportDraft(ctx context.Context, arg LockReportDraftParams) (LockReportDraftRow, error) {
	row := q.db.QueryRowContext(ctx, lockReportDraft, arg.ProjectID, arg.GeneratedReportID)
	var i LockReportDraftRow
	err := row.Scan(&i.ID, &i.Completeness, &i.ContentJson)
	return i, err
}

const lockReportPublication = `-- name: LockReportPublication :one
SELECT id FROM generated_reports WHERE project_id=$1 AND id=$2 FOR UPDATE
`

type LockReportPublicationParams struct {
	ProjectID int32     `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) LockReportPublication(ctx context.Context, arg LockReportPublicationParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, lockReportPublication, arg.ProjectID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const pointPublishedReport = `-- name: PointPublishedReport :exec
UPDATE generated_reports SET current_published_version_id=$3,updated_at=now() WHERE project_id=$1 AND id=$2
`

type PointPublishedReportParams struct {
	ProjectID                 int32         `json:"project_id"`
	ID                        uuid.UUID     `json:"id"`
	CurrentPublishedVersionID uuid.NullUUID `json:"current_published_version_id"`
}

func (q *Queries) PointPublishedReport(ctx context.Context, arg PointPublishedReportParams) error {
	_, err := q.db.ExecContext(ctx, pointPublishedReport, arg.ProjectID, arg.ID, arg.CurrentPublishedVersionID)
	return err
}

const publishReportVersion = `-- name: PublishReportVersion :exec
UPDATE generated_report_versions SET status='published',published_by_user_id=$3,published_at=now() WHERE project_id=$1 AND id=$2
`

type PublishReportVersionParams struct {
	ProjectID         int32         `json:"project_id"`
	ID                uuid.UUID     `json:"id"`
	PublishedByUserID sql.NullInt32 `json:"published_by_user_id"`
}

func (q *Queries) PublishReportVersion(ctx context.Context, arg PublishReportVersionParams) error {
	_, err := q.db.ExecContext(ctx, publishReportVersion, arg.ProjectID, arg.ID, arg.PublishedByUserID)
	return err
}

const retainReportAssets = `-- name: RetainReportAssets :exec
UPDATE assets SET legal_hold=true,retention_reason='published-report:'||$2::text
WHERE project_id=$1 AND id=ANY($3::int[])
`

type RetainReportAssetsParams struct {
	ProjectID int32   `json:"project_id"`
	ReportID  string  `json:"report_id"`
	AssetIds  []int32 `json:"asset_ids"`
}

func (q *Queries) RetainReportAssets(ctx context.Context, arg RetainReportAssetsParams) error {
	_, err := q.db.ExecContext(ctx, retainReportAssets, arg.ProjectID, arg.ReportID, pq.Array(arg.AssetIds))
	return err
}

const retirePublishedReport = `-- name: RetirePublishedReport :exec
UPDATE generated_report_versions SET status='retired' WHERE project_id=$1 AND generated_report_id=$2 AND status='published'
`

type RetirePublishedReportParams struct {
	ProjectID         int32     `json:"project_id"`
	GeneratedReportID uuid.UUID `json:"generated_report_id"`
}

func (q *Queries) RetirePublishedReport(ctx context.Context, arg RetirePublishedReportParams) error {
	_, err := q.db.ExecContext(ctx, retirePublishedReport, arg.ProjectID, arg.GeneratedReportID)
	return err
}
