// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streams.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const channelGrants = `-- name: ChannelGrants :many
SELECT scope_type,device_type_id,device_id,action_pattern,effect
FROM device_capability_grants
WHERE project_id=$1 AND user_id=$2 AND (expires_at IS NULL OR expires_at>now())
 AND (scope_type='project' OR (scope_type='device_type' AND device_type_id=$3) OR (scope_type='device' AND device_id=$4))
`

type ChannelGrantsParams struct {
	ProjectID    int32         `json:"project_id"`
	UserID       int32         `json:"user_id"`
	DeviceTypeID sql.NullInt64 `json:"device_type_id"`
	DeviceID     sql.NullInt32 `json:"device_id"`
}

type ChannelGrantsRow struct {
	ScopeType     string        `json:"scope_type"`
	DeviceTypeID  sql.NullInt64 `json:"device_type_id"`
	DeviceID      sql.NullInt32 `json:"device_id"`
	ActionPattern string        `json:"action_pattern"`
	Effect        string        `json:"effect"`
}

func (q *Queries) ChannelGrants(ctx context.Context, arg ChannelGrantsParams) ([]ChannelGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, channelGrants,
		arg.ProjectID,
		arg.UserID,
		arg.DeviceTypeID,
		arg.DeviceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelGrantsRow{}
	for rows.Next() {
		var i ChannelGrantsRow
		if err := rows.Scan(
			&i.ScopeType,
			&i.DeviceTypeID,
			&i.DeviceID,
			&i.ActionPattern,
			&i.Effect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readChannelEvents = `-- name: ReadChannelEvents :many
SELECT cursor::text,event_id,occurred_at AS captured_at,payload_json,'{}'::jsonb AS quality_json
FROM project_events WHERE project_id=$1 AND cursor>$3::bigint AND payload_json->>'deviceId'=$2::text ORDER BY project_events.cursor LIMIT 501
`

type ReadChannelEventsParams struct {
	ProjectID int32  `json:"project_id"`
	Column2   string `json:"column_2"`
	Column3   int64  `json:"column_3"`
}

type ReadChannelEventsRow struct {
	Cursor      string          `json:"cursor"`
	EventID     string          `json:"event_id"`
	CapturedAt  time.Time       `json:"captured_at"`
	PayloadJson json.RawMessage `json:"payload_json"`
	QualityJson json.RawMessage `json:"quality_json"`
}

func (q *Queries) ReadChannelEvents(ctx context.Context, arg ReadChannelEventsParams) ([]ReadChannelEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, readChannelEvents, arg.ProjectID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadChannelEventsRow{}
	for rows.Next() {
		var i ReadChannelEventsRow
		if err := rows.Scan(
			&i.Cursor,
			&i.EventID,
			&i.CapturedAt,
			&i.PayloadJson,
			&i.QualityJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readChannelTelemetry = `-- name: ReadChannelTelemetry :many
SELECT id::text AS cursor,event_id,captured_at,payload_json,quality_json
FROM device_telemetry WHERE project_id=$1 AND device_id=$2 AND id>$3::bigint ORDER BY id LIMIT 501
`

type ReadChannelTelemetryParams struct {
	ProjectID int32 `json:"project_id"`
	DeviceID  int32 `json:"device_id"`
	Column3   int64 `json:"column_3"`
}

type ReadChannelTelemetryRow struct {
	Cursor      string          `json:"cursor"`
	EventID     string          `json:"event_id"`
	CapturedAt  time.Time       `json:"captured_at"`
	PayloadJson json.RawMessage `json:"payload_json"`
	QualityJson json.RawMessage `json:"quality_json"`
}

func (q *Queries) ReadChannelTelemetry(ctx context.Context, arg ReadChannelTelemetryParams) ([]ReadChannelTelemetryRow, error) {
	rows, err := q.db.QueryContext(ctx, readChannelTelemetry, arg.ProjectID, arg.DeviceID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadChannelTelemetryRow{}
	for rows.Next() {
		var i ReadChannelTelemetryRow
		if err := rows.Scan(
			&i.Cursor,
			&i.EventID,
			&i.CapturedAt,
			&i.PayloadJson,
			&i.QualityJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readProjectEvents = `-- name: ReadProjectEvents :many
SELECT cursor::text,event_id,event_type,payload_json,occurred_at
FROM project_events WHERE project_id=$1 AND cursor>$2::bigint ORDER BY project_events.cursor LIMIT 501
`

type ReadProjectEventsParams struct {
	ProjectID int32 `json:"project_id"`
	Column2   int64 `json:"column_2"`
}

type ReadProjectEventsRow struct {
	Cursor      string          `json:"cursor"`
	EventID     string          `json:"event_id"`
	EventType   string          `json:"event_type"`
	PayloadJson json.RawMessage `json:"payload_json"`
	OccurredAt  time.Time       `json:"occurred_at"`
}

func (q *Queries) ReadProjectEvents(ctx context.Context, arg ReadProjectEventsParams) ([]ReadProjectEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, readProjectEvents, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadProjectEventsRow{}
	for rows.Next() {
		var i ReadProjectEventsRow
		if err := rows.Scan(
			&i.Cursor,
			&i.EventID,
			&i.EventType,
			&i.PayloadJson,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChannel = `-- name: ResolveChannel :one
SELECT channel.stable_channel_id,channel.device_id,channel.data_type,membership.role,
 device.device_type_id,channel.capability_code,channel.availability
FROM device_stream_channels channel
JOIN devices device ON device.id=channel.device_id AND device.project_id=channel.project_id
JOIN projects project ON project.id=channel.project_id
JOIN team_members membership ON membership.team_id=project.team_id AND membership.user_id=$1
WHERE channel.project_id=$2 AND channel.stable_channel_id=$3
`

type ResolveChannelParams struct {
	UserID    int32  `json:"user_id"`
	ProjectID int32  `json:"project_id"`
	ChannelID string `json:"channel_id"`
}

type ResolveChannelRow struct {
	StableChannelID string `json:"stable_channel_id"`
	DeviceID        int32  `json:"device_id"`
	DataType        string `json:"data_type"`
	Role            string `json:"role"`
	DeviceTypeID    int64  `json:"device_type_id"`
	CapabilityCode  string `json:"capability_code"`
	Availability    string `json:"availability"`
}

func (q *Queries) ResolveChannel(ctx context.Context, arg ResolveChannelParams) (ResolveChannelRow, error) {
	row := q.db.QueryRowContext(ctx, resolveChannel, arg.UserID, arg.ProjectID, arg.ChannelID)
	var i ResolveChannelRow
	err := row.Scan(
		&i.StableChannelID,
		&i.DeviceID,
		&i.DataType,
		&i.Role,
		&i.DeviceTypeID,
		&i.CapabilityCode,
		&i.Availability,
	)
	return i, err
}
