// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_drafts.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const taskDraftCopySteps = `-- name: TaskDraftCopySteps :exec
insert into task_steps (
             project_id, team_id, task_version_id, position, step_key, name, capability_code,
             action, parameters_json, failure_policy_json, media_requirements_json, uses,
             input_schema_json, output_schema_json, condition_json, depends_on_json, timeout_seconds, retry_policy_json
           ) select project_id, team_id, $1, position, step_key, name, capability_code,
                    action, parameters_json, failure_policy_json, media_requirements_json, uses,
                    input_schema_json, output_schema_json, condition_json, depends_on_json, timeout_seconds, retry_policy_json
               from task_steps where task_steps.project_id = $2 and task_steps.task_version_id = $3
`

type TaskDraftCopyStepsParams struct {
	P3 int64 `json:"p3"`
	P1 int32 `json:"p1"`
	P2 int64 `json:"p2"`
}

func (q *Queries) TaskDraftCopySteps(ctx context.Context, arg TaskDraftCopyStepsParams) error {
	_, err := q.db.ExecContext(ctx, taskDraftCopySteps, arg.P3, arg.P1, arg.P2)
	return err
}

const taskDraftCreate = `-- name: TaskDraftCreate :one
insert into task_versions (
           project_id, team_id, task_id, version, status, definition_json, script, input_schema_json,
           trigger_json, concurrency_limit, created_by_user_id
         ) values ($1, $2, $3, $4, 'draft', $5, $6, $7, $8, $9, $10) returning id, project_id as "projectId", task_id as "taskId", version, status,
  definition_json as definition, script, input_schema_json as "inputSchema", trigger_json as trigger,
  concurrency_limit as "concurrencyLimit"
`

type TaskDraftCreateParams struct {
	P1  int32           `json:"p1"`
	P2  int32           `json:"p2"`
	P3  int32           `json:"p3"`
	P4  int32           `json:"p4"`
	P5  json.RawMessage `json:"p5"`
	P6  string          `json:"p6"`
	P7  json.RawMessage `json:"p7"`
	P8  json.RawMessage `json:"p8"`
	P9  int32           `json:"p9"`
	P10 sql.NullInt32   `json:"p10"`
}

type TaskDraftCreateRow struct {
	ID               int64           `json:"id"`
	ProjectId        int32           `json:"projectId"`
	TaskId           int32           `json:"taskId"`
	Version          int32           `json:"version"`
	Status           string          `json:"status"`
	Definition       json.RawMessage `json:"definition"`
	Script           string          `json:"script"`
	InputSchema      json.RawMessage `json:"inputSchema"`
	Trigger          json.RawMessage `json:"trigger"`
	ConcurrencyLimit int32           `json:"concurrencyLimit"`
}

func (q *Queries) TaskDraftCreate(ctx context.Context, arg TaskDraftCreateParams) (TaskDraftCreateRow, error) {
	row := q.db.QueryRowContext(ctx, taskDraftCreate,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
	)
	var i TaskDraftCreateRow
	err := row.Scan(
		&i.ID,
		&i.ProjectId,
		&i.TaskId,
		&i.Version,
		&i.Status,
		&i.Definition,
		&i.Script,
		&i.InputSchema,
		&i.Trigger,
		&i.ConcurrencyLimit,
	)
	return i, err
}

const taskDraftDeleteSteps = `-- name: TaskDraftDeleteSteps :exec
delete from task_steps where project_id=$1 and task_version_id=$2
`

type TaskDraftDeleteStepsParams struct {
	P1 int32 `json:"p1"`
	P2 int64 `json:"p2"`
}

func (q *Queries) TaskDraftDeleteSteps(ctx context.Context, arg TaskDraftDeleteStepsParams) error {
	_, err := q.db.ExecContext(ctx, taskDraftDeleteSteps, arg.P1, arg.P2)
	return err
}

const taskDraftExisting = `-- name: TaskDraftExisting :many
SELECT to_jsonb(r) FROM (
select id, project_id as "projectId", task_id as "taskId", version, status,
  definition_json as definition, script, input_schema_json as "inputSchema", trigger_json as trigger,
  concurrency_limit as "concurrencyLimit" from task_versions where project_id = $1 and task_id = $2 and status = 'draft'
) r
`

type TaskDraftExistingParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
}

func (q *Queries) TaskDraftExisting(ctx context.Context, arg TaskDraftExistingParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, taskDraftExisting, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskDraftInsertStep = `-- name: TaskDraftInsertStep :exec
insert into task_steps(
        project_id,team_id,task_version_id,position,step_key,name,capability_code,action,parameters_json,
        failure_policy_json,media_requirements_json,uses,input_schema_json,output_schema_json,condition_json,
        depends_on_json,timeout_seconds,retry_policy_json)
        values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
`

type TaskDraftInsertStepParams struct {
	P1  int32                 `json:"p1"`
	P2  int32                 `json:"p2"`
	P3  int64                 `json:"p3"`
	P4  int32                 `json:"p4"`
	P5  string                `json:"p5"`
	P6  string                `json:"p6"`
	P7  sql.NullString        `json:"p7"`
	P8  string                `json:"p8"`
	P9  json.RawMessage       `json:"p9"`
	P10 json.RawMessage       `json:"p10"`
	P11 json.RawMessage       `json:"p11"`
	P12 string                `json:"p12"`
	P13 json.RawMessage       `json:"p13"`
	P14 json.RawMessage       `json:"p14"`
	P15 pqtype.NullRawMessage `json:"p15"`
	P16 json.RawMessage       `json:"p16"`
	P17 int32                 `json:"p17"`
	P18 json.RawMessage       `json:"p18"`
}

func (q *Queries) TaskDraftInsertStep(ctx context.Context, arg TaskDraftInsertStepParams) error {
	_, err := q.db.ExecContext(ctx, taskDraftInsertStep,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P8,
		arg.P9,
		arg.P10,
		arg.P11,
		arg.P12,
		arg.P13,
		arg.P14,
		arg.P15,
		arg.P16,
		arg.P17,
		arg.P18,
	)
	return err
}

const taskDraftList = `-- name: TaskDraftList :many
SELECT to_jsonb(r) FROM (
select id, project_id as "projectId", task_id as "taskId", version, status,
  definition_json as definition, script, input_schema_json as "inputSchema", trigger_json as trigger,
  concurrency_limit as "concurrencyLimit" from task_versions where project_id = $1 and task_id = $2 order by version desc
) r
`

type TaskDraftListParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
}

func (q *Queries) TaskDraftList(ctx context.Context, arg TaskDraftListParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, taskDraftList, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskDraftLockDraft = `-- name: TaskDraftLockDraft :many
SELECT to_jsonb(r) FROM (
select id from task_versions where project_id=$1 and task_id=$2 and id=$3 and status='draft' for update
) r
`

type TaskDraftLockDraftParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
	P3 int64 `json:"p3"`
}

func (q *Queries) TaskDraftLockDraft(ctx context.Context, arg TaskDraftLockDraftParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, taskDraftLockDraft, arg.P1, arg.P2, arg.P3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskDraftLockVersion = `-- name: TaskDraftLockVersion :many
SELECT to_jsonb(r) FROM (
select id, project_id as "projectId", task_id as "taskId", version, status,
  definition_json as definition, script, input_schema_json as "inputSchema", trigger_json as trigger,
  concurrency_limit as "concurrencyLimit" from task_versions where project_id = $1 and id = $2 for update
) r
`

type TaskDraftLockVersionParams struct {
	P1 int32 `json:"p1"`
	P2 int64 `json:"p2"`
}

func (q *Queries) TaskDraftLockVersion(ctx context.Context, arg TaskDraftLockVersionParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, taskDraftLockVersion, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskDraftNextVersion = `-- name: TaskDraftNextVersion :one
select coalesce(max(version),0)::int+1 as version from task_versions where task_id=$1
`

func (q *Queries) TaskDraftNextVersion(ctx context.Context, taskID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, taskDraftNextVersion, taskID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const taskDraftPublish = `-- name: TaskDraftPublish :one
update task_versions set status = 'published', published_by_user_id = $1, published_at = now()
          where project_id = $2 and id = $3 and status = 'draft' returning id, project_id as "projectId", task_id as "taskId", version, status,
  definition_json as definition, script, input_schema_json as "inputSchema", trigger_json as trigger,
  concurrency_limit as "concurrencyLimit"
`

type TaskDraftPublishParams struct {
	P3 sql.NullInt32 `json:"p3"`
	P1 int32         `json:"p1"`
	P2 int64         `json:"p2"`
}

type TaskDraftPublishRow struct {
	ID               int64           `json:"id"`
	ProjectId        int32           `json:"projectId"`
	TaskId           int32           `json:"taskId"`
	Version          int32           `json:"version"`
	Status           string          `json:"status"`
	Definition       json.RawMessage `json:"definition"`
	Script           string          `json:"script"`
	InputSchema      json.RawMessage `json:"inputSchema"`
	Trigger          json.RawMessage `json:"trigger"`
	ConcurrencyLimit int32           `json:"concurrencyLimit"`
}

func (q *Queries) TaskDraftPublish(ctx context.Context, arg TaskDraftPublishParams) (TaskDraftPublishRow, error) {
	row := q.db.QueryRowContext(ctx, taskDraftPublish, arg.P3, arg.P1, arg.P2)
	var i TaskDraftPublishRow
	err := row.Scan(
		&i.ID,
		&i.ProjectId,
		&i.TaskId,
		&i.Version,
		&i.Status,
		&i.Definition,
		&i.Script,
		&i.InputSchema,
		&i.Trigger,
		&i.ConcurrencyLimit,
	)
	return i, err
}

const taskDraftSave = `-- name: TaskDraftSave :exec
update task_versions set definition_json=$1,script='typed-task-v1',input_schema_json=$2,
      trigger_json=$3,concurrency_limit=$4 where project_id=$5 and task_id=$6 and id=$7
`

type TaskDraftSaveParams struct {
	P4 json.RawMessage `json:"p4"`
	P5 json.RawMessage `json:"p5"`
	P6 json.RawMessage `json:"p6"`
	P7 int32           `json:"p7"`
	P1 int32           `json:"p1"`
	P2 int32           `json:"p2"`
	P3 int64           `json:"p3"`
}

func (q *Queries) TaskDraftSave(ctx context.Context, arg TaskDraftSaveParams) error {
	_, err := q.db.ExecContext(ctx, taskDraftSave,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P7,
		arg.P1,
		arg.P2,
		arg.P3,
	)
	return err
}

const taskDraftSource = `-- name: TaskDraftSource :many
SELECT to_jsonb(r) FROM (
select definition_json as definition, script, input_schema_json as "inputSchema", trigger_json as trigger,
                  concurrency_limit as "concurrencyLimit" from task_versions where project_id = $1 and id = $2
) r
`

type TaskDraftSourceParams struct {
	P1 int32 `json:"p1"`
	P2 int64 `json:"p2"`
}

func (q *Queries) TaskDraftSource(ctx context.Context, arg TaskDraftSourceParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, taskDraftSource, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskDraftSteps = `-- name: TaskDraftSteps :many
SELECT to_jsonb(r) FROM (
select position, step_key as "stepKey", name, capability_code as "capabilityCode", action,
                parameters_json as parameters, failure_policy_json as "failurePolicy",
                media_requirements_json as "mediaRequirements" from task_steps
          where project_id = $1 and task_version_id = $2 order by position
) r
`

type TaskDraftStepsParams struct {
	P1 int32 `json:"p1"`
	P2 int64 `json:"p2"`
}

func (q *Queries) TaskDraftSteps(ctx context.Context, arg TaskDraftStepsParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, taskDraftSteps, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskDraftTask = `-- name: TaskDraftTask :many
SELECT to_jsonb(r) FROM (
select task.team_id as "teamId", task.current_published_version_id as "currentVersionId",
                task.script, jsonb_build_object('name', task.name, 'description', task.description,
                  'triggerType', task.trigger_type, 'targetSelector', task.target_selector_json,
                  'schedule', task.schedule, 'eventRule', task.event_rule_json) as definition
           from tasks task where task.project_id = $1 and task.id = $2 for update
) r
`

type TaskDraftTaskParams struct {
	P1 int32 `json:"p1"`
	P2 int32 `json:"p2"`
}

func (q *Queries) TaskDraftTask(ctx context.Context, arg TaskDraftTaskParams) ([]json.RawMessage, error) {
	rows, err := q.db.QueryContext(ctx, taskDraftTask, arg.P1, arg.P2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var to_jsonb json.RawMessage
		if err := rows.Scan(&to_jsonb); err != nil {
			return nil, err
		}
		items = append(items, to_jsonb)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskDraftUpdateTask = `-- name: TaskDraftUpdateTask :exec
update tasks set current_published_version_id=$1,name=coalesce(nullif($2,''),name),
          description=coalesce($3,description),trigger_type=$4,updated_at=now() where project_id=$5 and id=$6
`

type TaskDraftUpdateTaskParams struct {
	P3 sql.NullInt64  `json:"p3"`
	P4 interface{}    `json:"p4"`
	P5 sql.NullString `json:"p5"`
	P6 string         `json:"p6"`
	P1 int32          `json:"p1"`
	P2 int32          `json:"p2"`
}

func (q *Queries) TaskDraftUpdateTask(ctx context.Context, arg TaskDraftUpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, taskDraftUpdateTask,
		arg.P3,
		arg.P4,
		arg.P5,
		arg.P6,
		arg.P1,
		arg.P2,
	)
	return err
}
