// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_triggers.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countActiveTriggeredRuns = `-- name: CountActiveTriggeredRuns :one
SELECT count(*) FROM task_runs WHERE project_id=$1 AND task_version_id=$2
AND status IN ('queued','blocked','ready','dispatching','running','paused','canceling')
`

type CountActiveTriggeredRunsParams struct {
	ProjectID     int32         `json:"project_id"`
	TaskVersionID sql.NullInt64 `json:"task_version_id"`
}

func (q *Queries) CountActiveTriggeredRuns(ctx context.Context, arg CountActiveTriggeredRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTriggeredRuns, arg.ProjectID, arg.TaskVersionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTriggeredRun = `-- name: InsertTriggeredRun :one
INSERT INTO task_runs(project_id,team_id,task_id,task_version_id,trigger_source,trigger_key,status,input_snapshot_json,created_by_user_id,state_reason)
VALUES($1,$2,$3,$4,$5,$6,'queued',$7,$8,'trigger-accepted') RETURNING id,status
`

type InsertTriggeredRunParams struct {
	ProjectID         int32           `json:"project_id"`
	TeamID            int32           `json:"team_id"`
	TaskID            int32           `json:"task_id"`
	TaskVersionID     sql.NullInt64   `json:"task_version_id"`
	TriggerSource     string          `json:"trigger_source"`
	TriggerKey        sql.NullString  `json:"trigger_key"`
	InputSnapshotJson json.RawMessage `json:"input_snapshot_json"`
	CreatedByUserID   sql.NullInt32   `json:"created_by_user_id"`
}

type InsertTriggeredRunRow struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) InsertTriggeredRun(ctx context.Context, arg InsertTriggeredRunParams) (InsertTriggeredRunRow, error) {
	row := q.db.QueryRowContext(ctx, insertTriggeredRun,
		arg.ProjectID,
		arg.TeamID,
		arg.TaskID,
		arg.TaskVersionID,
		arg.TriggerSource,
		arg.TriggerKey,
		arg.InputSnapshotJson,
		arg.CreatedByUserID,
	)
	var i InsertTriggeredRunRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const insertTriggeredSteps = `-- name: InsertTriggeredSteps :exec
INSERT INTO task_run_steps(project_id,team_id,task_run_id,task_step_id,position,status,execution_key)
SELECT step.project_id,step.team_id,$3,step.id,step.position,'pending',$4::text||':step:'||step.step_key
FROM task_steps step WHERE step.project_id=$1 AND step.task_version_id=$2 ORDER BY step.position
`

type InsertTriggeredStepsParams struct {
	ProjectID     int32  `json:"project_id"`
	TaskVersionID int64  `json:"task_version_id"`
	TaskRunID     int32  `json:"task_run_id"`
	Column4       string `json:"column_4"`
}

func (q *Queries) InsertTriggeredSteps(ctx context.Context, arg InsertTriggeredStepsParams) error {
	_, err := q.db.ExecContext(ctx, insertTriggeredSteps,
		arg.ProjectID,
		arg.TaskVersionID,
		arg.TaskRunID,
		arg.Column4,
	)
	return err
}

const lockTaskTrigger = `-- name: LockTaskTrigger :exec
SELECT pg_advisory_xact_lock($1::integer,$2::integer)
`

type LockTaskTriggerParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
}

func (q *Queries) LockTaskTrigger(ctx context.Context, arg LockTaskTriggerParams) error {
	_, err := q.db.ExecContext(ctx, lockTaskTrigger, arg.Column1, arg.Column2)
	return err
}

const readTaskTriggerVersion = `-- name: ReadTaskTriggerVersion :one
SELECT task.project_id,task.team_id,task.id AS task_id,task.status AS task_status,
 version.id AS task_version_id,version.status AS task_version_status,version.trigger_json,
 version.input_schema_json,version.concurrency_limit
FROM tasks task JOIN task_versions version ON version.id=task.current_published_version_id AND version.project_id=task.project_id
WHERE task.project_id=$1 AND task.id=$2 FOR UPDATE OF task,version
`

type ReadTaskTriggerVersionParams struct {
	ProjectID int32 `json:"project_id"`
	ID        int32 `json:"id"`
}

type ReadTaskTriggerVersionRow struct {
	ProjectID         int32           `json:"project_id"`
	TeamID            int32           `json:"team_id"`
	TaskID            int32           `json:"task_id"`
	TaskStatus        string          `json:"task_status"`
	TaskVersionID     int64           `json:"task_version_id"`
	TaskVersionStatus string          `json:"task_version_status"`
	TriggerJson       json.RawMessage `json:"trigger_json"`
	InputSchemaJson   json.RawMessage `json:"input_schema_json"`
	ConcurrencyLimit  int32           `json:"concurrency_limit"`
}

func (q *Queries) ReadTaskTriggerVersion(ctx context.Context, arg ReadTaskTriggerVersionParams) (ReadTaskTriggerVersionRow, error) {
	row := q.db.QueryRowContext(ctx, readTaskTriggerVersion, arg.ProjectID, arg.ID)
	var i ReadTaskTriggerVersionRow
	err := row.Scan(
		&i.ProjectID,
		&i.TeamID,
		&i.TaskID,
		&i.TaskStatus,
		&i.TaskVersionID,
		&i.TaskVersionStatus,
		&i.TriggerJson,
		&i.InputSchemaJson,
		&i.ConcurrencyLimit,
	)
	return i, err
}

const readTriggeredRun = `-- name: ReadTriggeredRun :one
SELECT id,status FROM task_runs WHERE project_id=$1 AND task_version_id=$2 AND trigger_key=$3
`

type ReadTriggeredRunParams struct {
	ProjectID     int32          `json:"project_id"`
	TaskVersionID sql.NullInt64  `json:"task_version_id"`
	TriggerKey    sql.NullString `json:"trigger_key"`
}

type ReadTriggeredRunRow struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) ReadTriggeredRun(ctx context.Context, arg ReadTriggeredRunParams) (ReadTriggeredRunRow, error) {
	row := q.db.QueryRowContext(ctx, readTriggeredRun, arg.ProjectID, arg.TaskVersionID, arg.TriggerKey)
	var i ReadTriggeredRunRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}
