// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: writes.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const completeIdempotency = `-- name: CompleteIdempotency :execrows
UPDATE idempotency_records SET status='completed',response_json=$2,completed_at=now() WHERE id=$1
`

type CompleteIdempotencyParams struct {
	ID           int64                 `json:"id"`
	ResponseJson pqtype.NullRawMessage `json:"response_json"`
}

func (q *Queries) CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeIdempotency, arg.ID, arg.ResponseJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completePlatformAudit = `-- name: CompletePlatformAudit :execrows
UPDATE platform_audit_events SET status='completed',result_hash=$2,completed_at=now() WHERE id=$1
`

type CompletePlatformAuditParams struct {
	ID         int64          `json:"id"`
	ResultHash sql.NullString `json:"result_hash"`
}

func (q *Queries) CompletePlatformAudit(ctx context.Context, arg CompletePlatformAuditParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completePlatformAudit, arg.ID, arg.ResultHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeProjectAudit = `-- name: CompleteProjectAudit :execrows
UPDATE audit_events SET status='completed',result_hash=$2,completed_at=now() WHERE id=$1 AND project_id=$3
`

type CompleteProjectAuditParams struct {
	ID         int64          `json:"id"`
	ResultHash sql.NullString `json:"result_hash"`
	ProjectID  int32          `json:"project_id"`
}

func (q *Queries) CompleteProjectAudit(ctx context.Context, arg CompleteProjectAuditParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeProjectAudit, arg.ID, arg.ResultHash, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueProjectEvent = `-- name: EnqueueProjectEvent :exec
INSERT INTO outbox_events(project_id,team_id,event_id,event_type,payload_json,max_attempts)
VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(event_id) DO NOTHING
`

type EnqueueProjectEventParams struct {
	ProjectID   int32           `json:"project_id"`
	TeamID      int32           `json:"team_id"`
	EventID     string          `json:"event_id"`
	EventType   string          `json:"event_type"`
	PayloadJson json.RawMessage `json:"payload_json"`
	MaxAttempts int32           `json:"max_attempts"`
}

func (q *Queries) EnqueueProjectEvent(ctx context.Context, arg EnqueueProjectEventParams) error {
	_, err := q.db.ExecContext(ctx, enqueueProjectEvent,
		arg.ProjectID,
		arg.TeamID,
		arg.EventID,
		arg.EventType,
		arg.PayloadJson,
		arg.MaxAttempts,
	)
	return err
}

const insertPlatformAudit = `-- name: InsertPlatformAudit :one
INSERT INTO platform_audit_events(actor_user_id,request_id,action,resource_type,resource_id,input_hash)
VALUES($1,$2,$3,$4,$5,$6) RETURNING id
`

type InsertPlatformAuditParams struct {
	ActorUserID  int32          `json:"actor_user_id"`
	RequestID    string         `json:"request_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   sql.NullString `json:"resource_id"`
	InputHash    string         `json:"input_hash"`
}

func (q *Queries) InsertPlatformAudit(ctx context.Context, arg InsertPlatformAuditParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPlatformAudit,
		arg.ActorUserID,
		arg.RequestID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.InputHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertProjectAudit = `-- name: InsertProjectAudit :one
INSERT INTO audit_events(project_id,team_id,request_id,idempotency_key,actor_user_id,actor_agent_id,action,resource_type,resource_id,input_hash,policy_result_json)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id
`

type InsertProjectAuditParams struct {
	ProjectID      int32           `json:"project_id"`
	TeamID         int32           `json:"team_id"`
	RequestID      string          `json:"request_id"`
	IdempotencyKey sql.NullString  `json:"idempotency_key"`
	ActorUserID    sql.NullInt32   `json:"actor_user_id"`
	ActorAgentID   sql.NullInt32   `json:"actor_agent_id"`
	Action         string          `json:"action"`
	ResourceType   string          `json:"resource_type"`
	ResourceID     sql.NullString  `json:"resource_id"`
	InputHash      string          `json:"input_hash"`
	PolicyResult   json.RawMessage `json:"policy_result"`
}

func (q *Queries) InsertProjectAudit(ctx context.Context, arg InsertProjectAuditParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertProjectAudit,
		arg.ProjectID,
		arg.TeamID,
		arg.RequestID,
		arg.IdempotencyKey,
		arg.ActorUserID,
		arg.ActorAgentID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.InputHash,
		arg.PolicyResult,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockProjectMembership = `-- name: LockProjectMembership :one
SELECT p.id AS project_id,p.team_id,tm.role FROM projects p
JOIN team_members tm ON tm.team_id=p.team_id AND tm.user_id=$1
WHERE p.id=$2 FOR SHARE OF p,tm
`

type LockProjectMembershipParams struct {
	UserID    int32 `json:"user_id"`
	ProjectID int32 `json:"project_id"`
}

type LockProjectMembershipRow struct {
	ProjectID int32  `json:"project_id"`
	TeamID    int32  `json:"team_id"`
	Role      string `json:"role"`
}

func (q *Queries) LockProjectMembership(ctx context.Context, arg LockProjectMembershipParams) (LockProjectMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, lockProjectMembership, arg.UserID, arg.ProjectID)
	var i LockProjectMembershipRow
	err := row.Scan(&i.ProjectID, &i.TeamID, &i.Role)
	return i, err
}

const lockProjectPermissions = `-- name: LockProjectPermissions :many
SELECT permission FROM project_permissions
WHERE project_id=$1 AND team_id=$2 AND user_id=$3 FOR SHARE
`

type LockProjectPermissionsParams struct {
	ProjectID int32 `json:"project_id"`
	TeamID    int32 `json:"team_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) LockProjectPermissions(ctx context.Context, arg LockProjectPermissionsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, lockProjectPermissions, arg.ProjectID, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishProjectEvent = `-- name: PublishProjectEvent :one
INSERT INTO project_events(project_id,team_id,event_id,event_type,payload_json,occurred_at)
VALUES($1,$2,$3,$4,$5,coalesce($6::timestamptz,now()))
ON CONFLICT(event_id) DO UPDATE SET event_id=excluded.event_id RETURNING cursor
`

type PublishProjectEventParams struct {
	ProjectID   int32           `json:"project_id"`
	TeamID      int32           `json:"team_id"`
	EventID     string          `json:"event_id"`
	EventType   string          `json:"event_type"`
	PayloadJson json.RawMessage `json:"payload_json"`
	OccurredAt  sql.NullTime    `json:"occurred_at"`
}

func (q *Queries) PublishProjectEvent(ctx context.Context, arg PublishProjectEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, publishProjectEvent,
		arg.ProjectID,
		arg.TeamID,
		arg.EventID,
		arg.EventType,
		arg.PayloadJson,
		arg.OccurredAt,
	)
	var cursor int64
	err := row.Scan(&cursor)
	return cursor, err
}

const readIdempotency = `-- name: ReadIdempotency :one
SELECT request_hash,status,response_json,error_code FROM idempotency_records
WHERE project_id=$1 AND actor_key=$2 AND operation=$3 AND idempotency_key=$4
`

type ReadIdempotencyParams struct {
	ProjectID      int32  `json:"project_id"`
	ActorKey       string `json:"actor_key"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
}

type ReadIdempotencyRow struct {
	RequestHash  string                `json:"request_hash"`
	Status       string                `json:"status"`
	ResponseJson pqtype.NullRawMessage `json:"response_json"`
	ErrorCode    sql.NullString        `json:"error_code"`
}

func (q *Queries) ReadIdempotency(ctx context.Context, arg ReadIdempotencyParams) (ReadIdempotencyRow, error) {
	row := q.db.QueryRowContext(ctx, readIdempotency,
		arg.ProjectID,
		arg.ActorKey,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i ReadIdempotencyRow
	err := row.Scan(
		&i.RequestHash,
		&i.Status,
		&i.ResponseJson,
		&i.ErrorCode,
	)
	return i, err
}

const reserveIdempotency = `-- name: ReserveIdempotency :one
INSERT INTO idempotency_records(project_id,team_id,actor_key,operation,idempotency_key,request_hash)
VALUES($1,$2,$3,$4,$5,$6)
ON CONFLICT(project_id,actor_key,operation,idempotency_key) DO NOTHING RETURNING id
`

type ReserveIdempotencyParams struct {
	ProjectID      int32  `json:"project_id"`
	TeamID         int32  `json:"team_id"`
	ActorKey       string `json:"actor_key"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
	RequestHash    string `json:"request_hash"`
}

func (q *Queries) ReserveIdempotency(ctx context.Context, arg ReserveIdempotencyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, reserveIdempotency,
		arg.ProjectID,
		arg.TeamID,
		arg.ActorKey,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
